### ISSUE TITLE
Error happens when getting the source code of linux kernel

### ISSUE THREAD

**Issue by bigbearishappy** [agherzan/meta-raspberrypi#1026]
**Description**
I am trying to compile the meta-raspberrypi on branch master.
But the error happens, it says it can not find the revision of the kernel source that I need.

**Steps to reproduce the issue:**
1 prepare the build environment for yocto.
2 clone the repo of poky on branch master
3 clone the repo of meta-raspberrypi on branch master
4 bitbake linux-raspberrypi -c do_fetch

**Describe the results you received:**
I get the following error log:
```
ERROR: linux-raspberrypi-1_5.15.24+gitAUTOINC+e1b976ee4f_ac66b3f757-r0 do_fetch: Fetcher failure: Unable to find revision ac66b3f757a3a6c84c6641356fb81c9fce3e89e9 in branch rpi-5.15.y even from upstream
ERROR: linux-raspberrypi-1_5.15.24+gitAUTOINC+e1b976ee4f_ac66b3f757-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'git://github.com/raspberrypi/linux.git;name=machine;branch=rpi-5.15.y;protocol=https')
ERROR: Logfile of failure stored in: /home/xiongjian/source_code/yocto_reterminal/poky/build/tmp/work/raspberrypi4_64-poky-linux/linux-raspberrypi/1_5.15.24+gitAUTOINC+e1b976ee4f_ac66b3f757-r0/temp/log.do_fetch.3544561
ERROR: Task (/home/xiongjian/source_code/yocto_reterminal/poky/meta-raspberrypi/recipes-kernel/linux/linux-raspberrypi_5.15.bb:do_fetch) failed with exit code '1'
```

**Additional details (revisions used, host distro, etc.):**
I have tried to take a look into the log file of the error output.I find that the build system try many different kernel source website to download.
But unfortunately, all of those are failed.

How can I fix this problem?
Waiting for your reply~

**Comment by agherzan** [comment]
@bigbearishappy try to update and see if it is fixed. https://github.com/agherzan/meta-raspberrypi/pull/1025 should have fixed it.

**Comment by kraj** [comment]
I think upstream linux-raspberry repo has switch default branch to 5.15 but then they rebased it :(
I am keeping an eye on it, if it gets rebased again, I will send a patch to keep using 5.10 until they stop rebasing 5.15
branch. Its not normal to rebase your default branches that you want your users to use sigh !!

**Comment by bigbearishappy** [comment]
Thank you for your reply.
