### ISSUE TITLE
Query - Are GPIO Filters supported in config.txt?

### ISSUE THREAD

**Issue by GilchristT** [agherzan/meta-raspberrypi#1029]
Hi

I'm trying to use GPIO filters in my config.txt i.e. conditional configurations depending on the state of a GPIO at boot.

This doesn't appear to be working but GPIO filters seem to be temperamental at the best of times so I just wanted to check if anyone knows if they're definitely implemented or definitely not implemented before I waste too much time troubleshooting.

Thanks

**Comment by agherzan** [comment]
@GilchristT I haven't played with them until now and also haven't seen people around do it either. have you tried to reach out on the RPi's forum? We use the latest stable firmware version so you should have the same functionality as in upstream/Raspbian.
