### ISSUE TITLE
Yocto Zeus unable to find revision in RPi-Distro/firmware-nonfree

### ISSUE THREAD

**Issue by domenicogaeni** [agherzan/meta-raspberrypi#1048]
**Description**

Hi there!
I was trying to build an image for Raspberry Pi 4 using the Zeus version of Yocto Project, but I encountered an error related to [this file](https://github.com/agherzan/meta-raspberrypi/blob/zeus/recipes-kernel/linux-firmware-rpidistro/linux-firmware-rpidistro_git.bb):
It appears that the SRC_URI variable is referencing the master branch, which no longer exists on [https://github.com/RPi-Distro/firmware-nonfree](https://github.com/RPi-Distro/firmware-nonfree).

**Steps to reproduce the issue:**

1. Switch to the zeus branch
2. Try to build

**Describe the results you received:**

```
ERROR: linux-firmware-rpidistro-0.0+gitAUTOINC+f0ad1a42b0-r0 do_fetch: Fetcher failure: Unable to find revision f0ad1a42b051aa9da1d9e1dc606dd68ec2f163a5 in branch master even from upstream
ERROR: linux-firmware-rpidistro-0.0+gitAUTOINC+f0ad1a42b0-r0 do_fetch: Fetcher failure for URL: 'git://github.com/RPi-Distro/firmware-nonfree'. Unable to fetch URL from any source.
ERROR: Logfile of failure stored in: /home/bbb/raspberry/build/tmp/work/all-poky-linux/linux-firmware-rpidistro/0.0+gitAUTOINC+f0ad1a42b0-r0/temp/log.do_fetch.18822
ERROR: Task (/home/bbb/raspberry/meta-raspberrypi/recipes-kernel/linux-firmware-rpidistro/linux-firmware-rpidistro_git.bb:do_fetch) failed with exit code '1'
```

**Describe the results you expected:**

The build to be completed succesfully

**Additional details (revisions used, host distro, etc.):**

Yocto Project Version: Zeus
Host Distro: Ubuntu 18.04

**Comment by agherzan** [comment]
`zeus` is not a branch we still maintain but I'm fine if you push an MR that fixes this specific issue (as opposed to the current MR which adds tons of other changes). That being said, I do recommend you move on to a newer version.
