### ISSUE TITLE
[kirkstone] No soundcards on rpi3

### ISSUE THREAD

**Issue by Ossanes** [agherzan/meta-raspberrypi#1065]
**Description**
No soundcards found on RaspberryPi3

No soundcards can be found at /proc/asound/cards. 
Also I tested using speaker-test utility (from alsa-utils) with no success.

**Steps to reproduce the issue:**
1. Build a core-image-base using Poky distro at Kirkstone;
2. Run image on the board;
3. cat /proc/asound/cards

**Describe the results you received:**
"--- no soundcards ---"

**Describe the results you expected:**
A list with at least HDMI audio output

**Additional information you deem important (e.g. issue happens only occasionally):**
I also tested usign "dtparam=audio=on" on /boot/config.txt
The same results are received.

**Additional details (revisions used, host distro, etc.):**
All layers at Kirkstone
Kernel 5.15.34-v7

**Comment by agherzan** [comment]
Hi @Ossanes. Can you please give it a try with an updated kirkstone oe-core/poky repository? I suspect this is the same issue as https://github.com/agherzan/meta-raspberrypi/issues/1054 which is fixed in oe-core.
