### ISSUE TITLE
set_image_size number of sectors 81920 not a multiple of sectors per track 63  

### ISSUE THREAD

**Issue by ehrenmann1977** [agherzan/meta-raspberrypi#108]
**Description**

**Steps to reproduce the issue:**
1. Yocto-Morthy
2. meta-raspberrypi
3. meta-diet
4. enable the systemd in local.conf

**Describe the results you received:**
failed due to image size

**Comment by betafive** [comment]
Please could you send us the full bitbake output including the error.

**Comment by agherzan** [comment]
@ehrenmann1977 were you able to find the roots of the problem? We would like to find out if so. Otherwise we will be closing this issue.

**Comment by ehrenmann1977** [comment]
hi there,

yes i could solve this issue, i created a file at ~/.mtoosrc

Add mtools_skip_check=1 to skip this test

**Comment by jku** [comment]
Are you 100% sure this is on morty or newer? I'm fairly confident I've fixed this before morty release in oe-core (commit "mtools: Patch out a useless sanity check").

**Comment by betafive** [comment]
Closing this as there's a workaround in place and the issue should be fixed in oe-core as per comment above from @jku. Feel free to re-open if needed.
