### ISSUE TITLE
Build fails due to gstreamer1.0-omx update in poky

### ISSUE THREAD

**Issue by agherzan** [agherzan/meta-raspberrypi#111]
**Description**

The build fails with current poky master.

**Steps to reproduce the issue:**
1. poky master
2. build rpi-test-image

**Describe the results you received:**

```
ERROR: No recipes available for:
  /work/yocto/raspberrypi/meta-raspberrypi/recipes-multimedia/gstreamer/gstreamer1.0-omx_1.10%.bbappend
```

**Describe the results you expected:**

Successful build.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Additional details (revisions used, host distro, etc.):**

**Comment by agherzan** [comment]
@kraj I'm going to try to port the patches to 1.12.

**Comment by kraj** [comment]
I had patch on my fork already just proposed it for master

**Comment by agherzan** [comment]
I thought so. OK. I'll let the builds finish and merge it. Thanks.

**Comment by kraj** [comment]
this should be closed
