### ISSUE TITLE
ERROR: Nothing RPROVIDES 'linux-firmware-rpidistro-bcm43455'

### ISSUE THREAD

**Issue by gitgonewithwind** [agherzan/meta-raspberrypi#1111]
Hi all,
I just have git pulled  meta-raspberrypi   (update to. commit 93dadf336ce11e3ed3ba75c7638b57fad60d6fdb) and pull others meta- as normal, but bitbake bitbake  core-image-base as before.
but error happened:

ERROR: Nothing RPROVIDES 'linux-firmware-rpidistro-bcm43455' (but /z/oe/pi4-v1.4/updated/layers/poky/meta/recipes-core/packagegroups/packagegroup-base.bb RDEPENDS on or otherwise requires it)
linux-firmware-rpidistro RPROVIDES linux-firmware-rpidistro-bcm43455 but was skipped: because it has a restricted license 'synaptics-killswitch'. Which is not listed in LICENSE_FLAGS_ACCEPTED

how to fix ?
thank you so much.

**Comment by agherzan** [comment]
Check this documentation: https://meta-raspberrypi.readthedocs.io/en/latest/ipcompliance.html#linux-firmware-rpidistro. Also, the error body above provides you with the exact solution too: define `LICENSE_FLAGS_ACCEPTED`.
