### ISSUE TITLE
when  we can use  Linux kernel 6.1.21?or checkout  old kernel 5.15.76,  5.15.84 ,so that I can install DSI touchscreen driver.

### ISSUE THREAD

**Issue by gitgonewithwind** [agherzan/meta-raspberrypi#1193]
Hi all,
I need to connect to a Waveshare-DSI-LCD  DSI touchscreen,but the company has the newest  Linux kernel 6.1.21 driver .KO. it can support raspbian image 2023-05-03-raspios-bullseye-arm64.img .
but currently yocto image is  6.1.20. I can not install the driver.
sudo bash ./WS
Driver Start Settings
modprobe: ERROR: could not insert 'WS_xinchDSI_Touch': Exec format error
modprobe: ERROR: could not insert 'WS_xinchDSI_Screen': Exec format error
It already exists and does not need to be added
It already exists and does not need to be added
It already exists and does not need to be added
It already exists and does not need to be added
Driver end Settings

--
how can I do?

the drivers can support kernel 5.10.103,  5.15.61,  5.15.76,  5.15.84,  6.1.21 .

but  we can not get 6.1.21 now, how can I checkout 5.15.84 or some others old kernel branch from here  [meta-raspberrypi](https://github.com/agherzan/meta-raspberrypi) so I just can install the anyone driver?

Thank you very much.

**Comment by agherzan** [comment]
If you have a hard dependency on the kernel version, I recommend having an extra layer with a provider of that version that says with your product/use-case. So in your case, have a local provider for one of the supported kernel versions.

**Comment by gitgonewithwind** [comment]
> If you have a hard dependency on the kernel version, I recommend having an extra layer with a provider of that version that says with your product/use-case. So in your case, have a local provider for one of the supported kernel versions.

Thank you.
if I use kernel 6.1.21 source  from scratch,but for   there are a lot of patch for raspberry? if it is complex for me to do that?
do you think I can directly use [meta-raspberrypi](https://github.com/agherzan/meta-raspberrypi) and only change kernel to 6.1.21?
or in [meta-raspberrypi](https://github.com/agherzan/meta-raspberrypi)  which commit can just fix 5.10.103, 5.15.61, 5.15.76, 5.15.84 ?
my last checkout is meta-raspberrypi e1014d41ef459af807f95cb7ff9105f077bc6daa which kernel is lower than 5.10.103

**Comment by gitgonewithwind** [comment]
> If you have a hard dependency on the kernel version, I recommend having an extra layer with a provider of that version that says with your product/use-case. So in your case, have a local provider for one of the supported kernel versions.

can I use kernel here https://github.com/raspberrypi/linux and modified current [meta-raspberrypi] (https://github.com/agherzan/meta-raspberrypi) to fit the supported kerenls driver?

**Comment by gitgonewithwind** [comment]
> > If you have a hard dependency on the kernel version, I recommend having an extra layer with a provider of that version that says with your product/use-case. So in your case, have a local provider for one of the supported kernel versions.
> 
> can I use kernel here https://github.com/raspberrypi/linux and modified current [meta-raspberrypi] (https://github.com/agherzan/meta-raspberrypi) to fit the supported kerenls driver?

@agherzan 

can I directly change file:meta-raspberrypi/recipes-kernel/linux/linux-raspberrypi_6.1.bb


LINUX_VERSION ?= "6.1.20"
LINUX_RPI_BRANCH ?= "rpi-6.1.y"
LINUX_RPI_KMETA_BRANCH ?= "yocto-6.1"
...


to 
LINUX_VERSION ?= "6.1.21"
something else 
 to try ?
