### ISSUE TITLE
Raspberry pi 0 2w kernel crashed during startup

### ISSUE THREAD

**Issue by ivrabie** [agherzan/meta-raspberrypi#1212]
I tried to build core-image-base for raspberry pi 0 2w.
After build when the image starts I get kernel panic like in the startup_log.txt, also here is the log for startup  rpi-test-image in the file startup_log_rpi_test.txt

**Steps to reproduce the issue:**
0. Kirkstone revision
1. Use local.conf attached in this issue
2. bitbake core-image-base
3.Flash sd-image on the sdcard

**Describe the results you received:**
Expect the image to start and I should be able to login.

**Describe the results you expected:**
Kernel crashes during startup

[startu_log.txt](https://github.com/agherzan/meta-raspberrypi/files/12333322/startu_log.txt)
[local.conf.txt](https://github.com/agherzan/meta-raspberrypi/files/12333327/local.conf.txt)
[startu_log_rpi_test.txt](https://github.com/agherzan/meta-raspberrypi/files/12333442/startu_log_rpi_test.txt)

**Comment by agherzan** [comment]
@ivrabie is this happening on master too?

**Comment by ivrabie** [comment]
It works fine also with WiFi I will close this.
