### ISSUE TITLE
Wrong version gstreamer1.0-omx_1.10%.bbappend in pyro branch

### ISSUE THREAD

**Issue by wian007** [agherzan/meta-raspberrypi#122]
**Description**
recipes-multimedia/gstreamer/gstreamer1.0-omx_1.10%.bbappend  generates the error 
"ERROR: No recipes available for:" on the pyro branch.

Poky pyro switched to:
meta/recipes-multimedia/gstreamer/gstreamer1.0-omx_1.12.2.bb

This master branch has the correct bbappend.

**Steps to reproduce the issue:**
1. Clone the poky pyro branch
2. Clone the meta-raspberrypi pyro branch
3. Bitbake

**Comment by wian007** [comment]
Suggested fix, merge master to pyro for gstreamer1.0* recipes

**Comment by betafive** [comment]
Looks like it's still 1.10.x on pyro: http://git.yoctoproject.org/cgit/cgit.cgi/poky/tree/meta/recipes-multimedia/gstreamer?h=pyro

Are you sure you have the correct Poky branch checked out?

**Comment by wian007** [comment]
I'm so sorry, though I double checked it but it seems I have the wrong branch checked out.
Guess I need more sleep

**Comment by agherzan** [comment]
Don't worry about it @wian007 . Glad you found the issue.
