### ISSUE TITLE
how to install Latex(or texlive) in raspberry pi4 yocto image in .bb files.

### ISSUE THREAD

**Issue by gitgonewithwind** [agherzan/meta-raspberrypi#1225]
Hi all,
sorry to bother you again.
I need to add Latex(or texlive) in my yocto image both in raspberry pi4 and nxp maaxboard.
but it seems nobody did before. I post as same question at https://community.nxp.com/t5/i-MX-Processors/how-to-install-latex-or-texlive-in-imx8/m-p/1349791    2 years ago. but no solutions.
I know in raspberry pi desktop. we can use below command to install it:
sudo apt-get update

sudo apt-get install texlive-base

sudo apt-get install texlive-latex-recommended

sudo apt-get install texlive

sudo apt-get install texlive-latex-extra

sudo apt-get install texlive-lang-cjk

sudo apt-get install texlive-lang-english

sudo apt-get install texlive-lang-european

sudo apt-get install texlive-lang-spanish

sudo apt-get install texlive-fonts-extra

after that I directly copy the installed binary executable code to my yocto image in pi4. but can I copy them to nxp board?(same arm64 ) . 
finally I want to know how to create a .bb file in yocto to auoto build it? it seems both raspberry pi yocto and nxp yocto do not do it.
any help ?

Thank you so much.

**Comment by agherzan** [comment]
I am sadly not aware of any lexlive integration in Yocto, so you will have to go down to do that if you require it. I will close this issue as this is not a BSP-specific issue but feel free to come back with details if you get this sorted.
