### ISSUE TITLE
nanbield branch?

### ISSUE THREAD

**Issue by williamspatrick** [agherzan/meta-raspberrypi#1253]
**Description**

There currently isn't a nanbield branch but most other meta-layers have created one, since Yocto released nanbield.  Can this be created for meta-raspberrypi?

**Steps to reproduce the issue:**
1. `git clone`
2. `(git branch -r | grep nanbield) || echo "No Branch Found"` 

**Describe the results you received:**

"No Branch Found"

**Describe the results you expected:**

No output.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Additional details (revisions used, host distro, etc.):**

https://git.yoctoproject.org/poky/log/?h=nanbield

**Comment by agherzan** [comment]
Thanks - available here: https://github.com/agherzan/meta-raspberrypi/tree/nanbield
