### ISSUE TITLE
RPI5 support

### ISSUE THREAD

**Issue by tristanguerragomez** [agherzan/meta-raspberrypi#1262]
Hi,

Searched for "5" and "RPI5" and not seeing any open issues...

Wondering when support for the RPI5 is expected?

Thank you,

**Comment by agherzan** [comment]
There is an PR in the works: https://github.com/agherzan/meta-raspberrypi/pull/1237. Keep an eye on it.

**Comment by tristanguerragomez** [comment]
apologies for the noise, didn't occur to me to look in the PRs...  looking forward to it!
