### ISSUE TITLE
Add RPI Camera Module 3 to the kirkstone branch

### ISSUE THREAD

**Issue by mark2b** [agherzan/meta-raspberrypi#1283]
Is there a way to add support of RPI Camera Module 3 to the kirkstone branch?
It requires installing overlay imx708

**Comment by mark2b** [comment]
duplicate

**Comment by agherzan** [comment]
That would require a backporting investigation of that in kirkstone. Have you checked the kirkstone kernel version provided by the layer?

**Comment by agherzan** [comment]
> duplicate

I'm not sure what this means. Could you explain?

**Comment by compiaffe** [comment]
There is this MR: https://github.com/agherzan/meta-raspberrypi/pull/1197
