### ISSUE TITLE
Does the /boot/config.txt for raspberry pi 5 work?

### ISSUE THREAD

**Issue by vermaete** [agherzan/meta-raspberrypi#1346]
**Description**

When adding `dtoverlay=disable-bt` to the `/boot/config.txt` file of a Yocto image with machine `raspberrypi5` it didn't do anything.

When comparing the dmesg log with our with the `dtoverlay=disable-bt` there is no difference.

Could it be this file is not processed anymore starting from raspberrypi5?

Changing it within Raspbian did enable/disable BT.
But the file structure at /boot is different at Raspbian.

I'm working with the current master of meta-raspberrypi and all other layers.

**Comment by agherzan** [comment]
The config.txt should still be the configuration interface for rpi5, too.
