### ISSUE TITLE
Static library issue

### ISSUE THREAD

**Issue by fwag** [agherzan/meta-raspberrypi#140]
I don't know if it could be off topic here.
Anyway, I don't know where to ask.

I have created a meta-layer (meta-kp) with:
recipes-example: an example taken from Embedded Linux Projects Using Yocto Project Cookbook with a static library recipe and the relative application.

recipes-piface:  my recipes for an expansion board 
- libmcp23s17: a static library
- exmcp23s17: an example just to use this static library
- libpifacedigital: another static library which requires libmcp23s17
- pifacedigital: the final application which requires both libmcp23s17 and libpifacedigital

I've added in IMAGE_INSTALL_append the recipe pifacedigital and helloworldstatic.

I'm able to compile the image rpi-basic-image, but after booting the image if I try to  execute the application pifacedigital_cmd it prompts out the following error:
/usr/bin/pifacedigital_cmd: line 1: syntax error: unexpected word (expecting ")")

Instead helloworldstatic (recipes-example) properly works.

Here the link of the entire meta-layer:
[meta-kp.zip](https://github.com/agherzan/meta-raspberrypi/files/1383101/meta-kp.zip)

Thanks in advance for your help

**Comment by betafive** [comment]
This sort of question isn't specific to meta-raspberrypi. Your best place to ask this is on the main Yocto Project mailing list (https://lists.yoctoproject.org/listinfo/yocto) or IRC channels (#yocto or #oe on irc.freenode.net).
