### ISSUE TITLE
Duplicated patch

### ISSUE THREAD

**Issue by giraldeau** [agherzan/meta-raspberrypi#15]
Seems that the file 0001-dts-add-overlay-for-pitft22.patch is duplicated multiple times, though the content is the same. Should this patch be merged in the raspberrypi kernel branch?

https://github.com/raspberrypi/linux

**Comment by agherzan** [comment]
Submitted. 
https://github.com/raspberrypi/linux/pull/1436
https://github.com/raspberrypi/linux/pull/1437
