### ISSUE TITLE
Hardware Watchdog Pi 2

### ISSUE THREAD

**Issue by zwerch** [agherzan/meta-raspberrypi#16]
I read about a hardware watchdog kernel module [here](https://www.bayerschmidt.com/raspberry-pi/89-auto-reboot-a-hung-raspberry-pi-using-the-on-board-watchdog-timer.html).
I would like to have a hardware watchdog in my firmware on the Pi 2 B, too.
Is this supported at all? If yes, how can I enable it?

**Comment by agherzan** [comment]
The module is compiled (tested on rpi3). You can load it with modprobe bcm2835_wdt .

**Comment by zwerch** [comment]
Thanks for your answer!
Is there a way that I don't need to manually load the module but configure my image / whatever to load it automatically?

**Comment by agherzan** [comment]
No worries. The way to do it in yocto is using KERNEL_MODULE_AUTOLOAD http://www.yoctoproject.org/docs/2.0/ref-manual/ref-manual.html#migration-1.7-kernel-module-autoloading .

**Comment by zwerch** [comment]
Thanks a lot!

**Comment by agherzan** [comment]
Welcome.
