### ISSUE TITLE
Implement  RPI_EXTRA_CONFIG

### ISSUE THREAD

**Issue by betafive** [agherzan/meta-raspberrypi#169]
(putting this in here so I don't forget)

It would be good to have an RPI_EXTRA_CONFIG variable or similar to add arbitrary text to the config file, so you could do something like this:

```
RPI_EXTRA_CONFIG = " \
    # Raspberry Pi 7\" display/touch screen \
    lcd_rotate=2 \
    "
```

**Comment by twoerner** [comment]
Does this work for others? It doesn't seem to work for me.

RPI_EXTRA_CONFIG = " \n \
    dtoverlay=spi1-3cs \n \
    dtoverlay=fti-tpm \n \
    "

gives a /mnt/config.txt that looks like:

...
#dtparam=pwr_led_gpio=35
# Enable SPI bus
dtparam=spi=on
# Enable I2C
dtparam=i2c1=on
dtparam=i2c_arm=on
# Enable UART
enable_uart=1
 \n dtoverlay=spi1-3cs \n dtoverlay=fti-tpm \n

**Comment by betafive** [comment]
@twoerner: I've just re-tested this in master with your lines added to my local.conf.

Output looks like this:

```
$ cat tmp/deploy/images/raspberrypi3/bcm2835-bootfiles/config.txt

<snip>

#dtparam=pwr_led_gpio=35

 dtoverlay=spi1-3cs
 dtoverlay=fti-tpm

```

Not sure why this would be working for me but not for you. Are you using latest master of everything?

**Comment by agherzan** [comment]
Test it too and looks fine.

**Comment by memox5** [comment]
using "echo -e" seems to fix the issue.
tested on ubuntu 16.04

> 
> 
> Does this work for others? It doesn't seem to work for me. The following in local.conf:
> 
> ```
> RPI_EXTRA_CONFIG = " \n \
>     dtoverlay=spi1-3cs \n \
>     dtoverlay=fti-tpm \n \
>     "
> ```
> 
> gives a /mnt/config.txt that looks like:
> 
> ```
> ...
> #dtparam=pwr_led_gpio=35
> # Enable SPI bus
> dtparam=spi=on
> # Enable I2C
> dtparam=i2c1=on
> dtparam=i2c_arm=on
> # Enable UART
> enable_uart=1
>  \n dtoverlay=spi1-3cs \n dtoverlay=fti-tpm \n
> ```

using echo -e seems to fix the issue, tested on ubuntu 16.04

**Comment by agherzan** [comment]
Sounds like a bug @memox5. Would you be able to push a fix? Thanks in advance.

**Comment by memox5** [comment]
#370

**Comment by memox5** [comment]
#370 should do

**Comment by memox5** [comment]
@agherzan #370 should do, thank you.
