### ISSUE TITLE
"You had no conf/local.conf file." message upon `source ~/poky/oe-init-build-env rpi-build`

### ISSUE THREAD

**Issue by kamomil** [agherzan/meta-raspberrypi#172]
Hi,
I followed the instructions and ran `source ~/poky/oe-init-build-env rpi-build`
and I got a long message:

```
You had no conf/local.conf file. This configuration file has therefore been
created for you with some default values. You may wish to edit it to, for
example, select a different MACHINE (target hardware). See conf/local.conf
for more information as common configuration options are commented.
...
```

the file `meta-raspberrypi/rpi-build/conf/local.conf` with the list of optional MACHINE variable, but raspberrypi machines are not in the list

**Comment by mirzak** [comment]
This is expected behavior when you create an a new "build" directory. The `local.conf` file is simply a copy of a template file found in poky [1]. 

Just set MACHINE to desired raspberrypi board.

[1]. http://git.yoctoproject.org/cgit.cgi/poky/tree/meta-poky/conf/local.conf.sample?h=rocko

**Comment by kamomil** [comment]
Hi,
I set `MACHINE = raspberrypi2`, then running `bitbake rpi-hwup-image` I got the error:

```
ERROR:  OE-core's config sanity checker detected a potential misconfiguration.
    Either fix the cause of this error or at your own risk disable the checker (see sanity.conf).
    Following is the list of potential problems / advisories:

    MACHINE=raspberrypi2 is invalid. Please set a valid MACHINE in your local.conf, environment or other configuration file.
```

**Comment by mirzak** [comment]
You need to add meta-raspberrypi to your bblayers.conf

**Comment by agherzan** [comment]
This is not a bug and the problems you encounter are basic yocto concepts that you need to handle before being able to work with this BSP layer. I suggest reading http://www.yoctoproject.org/docs/current/yocto-project-qs/yocto-project-qs.html and as well take a look as much as possible at http://www.yoctoproject.org/docs/current/ref-manual/ref-manual.html .
