### ISSUE TITLE
raspberrypi-zero-w: how to enable camera module

### ISSUE THREAD

**Issue by DengkeDu** [agherzan/meta-raspberrypi#204]
> root@raspberrypi0-wifi:~# raspivid -t 0
> mmal: mmal_vc_component_create: failed to create component 'vc.ril.camera' (1:ENOMEM)
> mmal: mmal_component_create_core: could not create component 'vc.ril.camera' (1)
> mmal: Failed to create camera component
> mmal: main: Failed to create camera component
> mmal: Camera is not enabled in this build. Try running "sudo raspi-config" and ensure that "camera" has been enabled

**Comment by DengkeDu** [comment]
> root@raspberrypi0-wifi:~# vcgencmd get_camera
> supported=0 detected=0

**Comment by DengkeDu** [comment]
The package rpi-config was null

**Comment by DengkeDu** [comment]
Every time I need mount the boot partion, and modify the config.txt.

**Comment by betafive** [comment]
Have you tried building with `VIDEO_CAMERA = "1"` set in your local.conf file? Looking at the documentation that should be the setting you need.

**Comment by agherzan** [comment]
@DengkeDu Did you try what Paul recommended above? I'd like to close this issue.

**Comment by DengkeDu** [comment]
Yes, it works!
