### ISSUE TITLE
gstreamer1.0-omx: refresh the patches

### ISSUE THREAD

**Issue by hhromic** [agherzan/meta-raspberrypi#211]
**Description**
Hi, I'm trying to refresh the patches for `gstreamer1.0-omx`.
I'm receiving the following warning when building:

```
WARNING: gstreamer1.0-omx-1.12.4-r0 do_patch:
Some of the context lines in patches were ignored. This can lead to incorrectly applied patches.
The context lines in the patches can be updated with devtool:

    devtool modify <recipe>
    devtool finish --force-patch-refresh <recipe> <layer_path>

Then the updated patches and the source tree (in devtool's workspace)
should be reviewed to make sure the patches apply in the correct place
and don't introduce duplicate lines (which can, and does happen
when some of the context is ignored). Further information:
http://lists.openembedded.org/pipermail/openembedded-core/2018-March/148675.html
https://bugzilla.yoctoproject.org/show_bug.cgi?id=10450
Details:
Applying patch 0001-config-files-path.patch
patching file config/bellagio/gstomx.conf
Hunk #1 succeeded at 1 with fuzz 2.
Hunk #2 succeeded at 9 with fuzz 2.
patching file config/rpi/gstomx.conf
Hunk #8 succeeded at 63 with fuzz 2.
Hunk #10 succeeded at 82 with fuzz 2.
Hunk #11 succeeded at 92 with fuzz 2.

Now at patch 0001-config-files-path.patch
```

However I'm a bit confused on how to rebase the patches. In particular, I noticed that there are duplicate patches both in `gstreamer1.0-omx` and `gstreamer1.0-omx-1.12`, under `recipes-multimedia/gstreamer`.

When building, the default (preferred) version picked is 1.12. However when I try to use devtool to rebase as suggested by the warning message, I'm getting the `gstreamer1.0-omx` version updated and not the `gstreamer1.0-omx-1.12` one. Is this normal?

Please let me know how I should perform the rebase properly so I can send the PR.
Thanks for the help!

**Steps to reproduce the issue:**
1. Initialise a build environment.
2. Use `MACHINE = "raspberrypi0-wifi"` and `LICENSE_FLAGS_WHITELIST_append = "commercial"` in `local.conf`.
3. Build the recipe using `bitbake gstreamer1.0-omx`.

**Describe the results you received:**
The warning shown in the description.

**Describe the results you expected:**
No warning when building.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Additional details (revisions used, host distro, etc.):**

```
Build Configuration:
BB_VERSION           = "1.37.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "debian-9"
TARGET_SYS           = "arm-poky-linux-gnueabi"
MACHINE              = "raspberrypi0-wifi"
DISTRO               = "poky"
DISTRO_VERSION       = "2.4+snapshot-20180320"
TUNE_FEATURES        = "arm armv6 vfp arm1176jzfs callconvention-hard"
TARGET_FPU           = "hard"
meta
meta-poky
meta-yocto-bsp       = "master:f49ee61422c867516db252054e993df29f775136"
meta-oe
meta-python
meta-multimedia
meta-networking      = "master:4598769a96980b756b3489ac71ed46a075cfabd7"
meta-raspberrypi     = "master:f86f9f0013e11311c66fc640fbb43b399606ca2f"
```

**Comment by hhromic** [comment]
Hi again,
Going further on this issue, I strongly think the patches in the `gstreamer1.0-omx` directory are obsolete/orphaned and this directory should be removed alltogether, leaving only the `gstreamer1.0-omx-1.12` directory (that includes exactly the some of the same patches from `gstreamer1.0-omx`). To me it looks like this directory was separated and forgotten to be cleaned.

I just back-traced the repository a bit and it looks like the commit ff914ff62267336a602c3dc96e959900795f5617 removed the bbappend (git version) file that referenced that directory.

At the same time it also removed the bbappend for the 1.10 version and its `gstreamer1.0-omx-1.10` directory with patches. I suspect then that the `gstreamer1.0-omx` (patches for the git version) directory should have been removed as well with the bbappend for the git version.

Can @kraj confirm this and I happily can send a PR with cleaning-up and rebasing of the patches?

**Comment by kraj** [comment]
They work fine although a refresh is ok please prepare a PR

**Comment by agherzan** [comment]
Sounds good.

**Comment by hhromic** [comment]
Great! I will remove the obsolete directory and rebase the current patches so all builds without warnings. Will send the PR as soon as I test everything. Cheers!
