### ISSUE TITLE
raspberry pi 3 plus and u-boot

### ISSUE THREAD

**Issue by ikoes** [agherzan/meta-raspberrypi#221]
hello guys,

I can boot a rpi3 with u-boot using meta-raspberrypi@rocko, poky@rocko succesfully. By the way the same image doesn't boot on a raspberry pi 3 plus. I'm tuck to the rainbow screen. What am I missing ?

thanks,

F-

**Comment by agherzan** [comment]
@ikoes we haven't tested support of the 3+ board with u-boot. So at this point, it is just not supported as nobody looked into it (afaik). Obviously, we encourage you to try and contribute but if that's not an option, you can always use the proprietary bootloader from the foundation which is tested to work on 3+.

**Comment by ikoes** [comment]
I've modified rocko:
    conf/machine/include/rpi-base.inc
    recipes-bsp/common/firmware.inc
    recipes-kernel/linux/linux-raspberrypi.inc
    recipes-kernel/linux/linux-raspberrypi_4.9.bb

in order to match their master counterparts. 

I'm not a linux expert but I think that the main problem is related to the new pi3+ dtb that in rocko is missing.

Now u-boot works as expected

**Comment by agherzan** [comment]
Uh wait. Can you try poky rocko + master of this layer? I just realised that rpi3+ support is only available in master.

**Comment by kraj** [comment]
@ikoes rainbow screen means its not using right dtb file

**Comment by ikoes** [comment]
@kraj , thanks to confirm that. 
@agherzan, Pocky@rocko + meta-raspberry@master fails due to bitbake policy. It was my first try. Hence I took only the files specified above from the master branch and replaced to the ones in rocko. It seems to solve the ssue.

**Comment by agherzan** [comment]
What do you mean by "took only the files specified above from the master branch and replaced to the ones in rocko"? Did you inject files in the boot partition?

**Comment by ikoes** [comment]
@agherzan 

I've taken
conf/machine/include/rpi-base.inc
recipes-bsp/common/firmware.inc
recipes-kernel/linux/linux-raspberrypi.inc
recipes-kernel/linux/linux-raspberrypi_4.9.bb

from your master branch and hence added it to your rocko branch

**Comment by agherzan** [comment]
Got it. That makes sense. Would you be able to backorder, cherry pick the commits and push a PR?

Did this fix the U-boot boot?

**Comment by ikoes** [comment]
With the new addition u-boot is working. what do you mean for push a PR ? i'm a very basic user.

**Comment by agherzan** [comment]
Ok. Don't bother about that. I'm glad this fixes your problem in which case I'll close this issue.
