### ISSUE TITLE
raspberry pi3+, brcmfmac43455 issue

### ISSUE THREAD

**Issue by ikoes** [agherzan/meta-raspberrypi#225]
Hello guys,

I have booted a rpi3+ using poky@rocko, meta-raspberrypi@rocko kernel 4.9.80. The running image is gnereted with "core-image-minimal". 

After booting the system, I run
`# dmesg`

The output of dmesg says:
```
Direct firmware load for brcm/brcmfmac43455-sdio.txt failed with error -2
brcmf_sdio_htclk: HT Avail timeout (1000000)
```

running
`# ls /lib/firmware/brcm | grep 43455 `
I get
brcmfmac43455-sdio.bin

Finally running
`# ifconfig -a`
shows no wlan interface

How can I get the wireless interface working again ?

thanks

F

**Comment by agherzan** [comment]
Hi @ikoes. First of all I'm wondering how did you boot the rpi3b+ with rocko? Did you backorder the support patches from meta-raspberrypi master?

About your error. You don't have the txt file. That is the nvram configuration for the WiFi device.

**Comment by ikoes** [comment]
@agherzan , as mentioned in the other issue with u-boot, yes, I've taken the needed file to get the rpi3+ booting with rocko.

As for the error yes, you are right.  I've just taken brcmfmac43455-sdio.txt from a raspbian "/lib/firmware/brcm" and added it manually to the same folder on my raspberry. After a reboot the wireless controller is now detected.

Why the .txt file is not present either in linux-firmware or linux-firmware-raspberry ?

thanks,

F.

**Comment by agherzan** [comment]
The txt file should be provided by linux-firmware-rasbian. Did you try master branch of meta-raspberrypi just to make sure that your "backporting" doesn't miss anything?

**Comment by agherzan** [comment]
This is confusing because you started two threads where you provided complete information about what you did in comments. And I have now to correlate them. Please next time do try to have a detailed as possible description when you create an issue.

You said that rocko poky and master rpi don't compile anymore. I can't remember now what broke it but if it is this way, you an cherry pick and adapt the patches from master to make sure that support is complete.

**Comment by ikoes** [comment]
thank you agherzan. I've started two threads because the issues didn't seem to be related to me at the time. 

I've tried to solve the 
`[brcm/brcmfmac43455-sdio.txt failed with error -2`

adding _/recipes-kernel/linux-firmware/linux-firmware-raspbian.bb_ from the master branch to _/recipes-kernel/linux-firmware/linux-firmware-raspbian.bb_ the rocko branch.

I've just noticed that as you said _linux-firmware-raspbian_ ships the missing file, I can see it in the recipe sysroot. 

By the way if I add _linux-firmware-raspbian_ to _CORE_IMAGE_EXTRA_INSTALL_ , the following error is generated:
`Nothing RPROVIDES 'linux-firmware-raspbian' (but /home/worker/iagocto/build/../poky/meta/recipes-core/images/core-image-minimal.bb RDEPENDS on or otherwise requires it)`

**Comment by ikoes** [comment]
My fault,

CORE_IMAGE_EXTRA_INSTALL += " linux-firmware-raspbian-bcm43455"

that finally solve the issue.

thanks.

**Comment by kraj** [comment]
can you close this ?
