### ISSUE TITLE
abandoned/stale branches

### ISSUE THREAD

**Issue by hhromic** [agherzan/meta-raspberrypi#231]
Hi guys, this is not a bug/issue really but a call for attention.
I noticed that there are two branches that don't correspond to any Yocto release and seem to be fixes that were forgotten to be removed.

* `bcm2835-fix`, Updated 11 months ago by agherzan [merged]
* `fix-rpi0wifi-kernel`, Updated 7 months ago by agherzan [merged]

Perhaps the repo needs a vacuuming for these? :)
Cheers!

**Comment by agherzan** [comment]
Vacuumed. Thanks @hhromic.

**Comment by hhromic** [comment]
happy to help
