### ISSUE TITLE
Time to branch for sumo?

### ISSUE THREAD

**Issue by betafive** [agherzan/meta-raspberrypi#232]
I think we're ready to create a branch for sumo now, the Yocto Project release should be immanent :)

Any objections? Primarily checking with @kraj and @agherzan here. If you're both happy I'll create the branch later this week.

**Comment by betafive** [comment]
Last time people branched just before the release but looks like there isn't a sumo branch in meta-openembedded yet. I'd like to set all my branches to "sumo" and test the build/release scripts in my distro so it's really just for my benefit :)

**Comment by agherzan** [comment]
I'm fine with pushing it.

**Comment by kraj** [comment]
Wait until offcial release please, you never know until its done.

**Comment by betafive** [comment]
master has now divered from sumo in oe-core and contains some major upgrades. I'm currently seeing build failures due to the new u-boot upgrade. So I think it's definitely time to make the branch even if 2.5 isn't fully released yet.

**Comment by kraj** [comment]
OK lets go ahead

**Comment by agherzan** [comment]
Branch created.
