### ISSUE TITLE
No package 'wayland-egl' found

### ISSUE THREAD

**Issue by billj-korg** [agherzan/meta-raspberrypi#259]
When building in master for the raspberrypi3-64 machine (bitbake core-image-minimal), 
I now encounter the error:
 
"No package 'wayland-egl' found" during the gtk+3_3.22.29.bb:do_configure task.

This appears to be related to the addition of do_install_append_rpi() in wayland_%.bbappend from commit de8912cb.

**Comment by hhromic** [comment]
Hi @billj-korg , can you please post the layers you are using and the relevant parts of your `conf/local.conf` file for debugging? Thanks

**Comment by billj-korg** [comment]
Layers are:
BBLAYERS ?= " \
  /data/development/lfs/yocto/poky/meta \
  /data/development/lfs/yocto/poky/meta-poky \
  /data/development/lfs/yocto/poky/meta-yocto-bsp \
  /data/development/lfs/yocto/poky/meta-openembedded/meta-oe \
  /data/development/lfs/yocto/poky/meta-openembedded/meta-python \
  /data/development/lfs/yocto/poky/meta-openembedded/meta-multimedia \
  /data/development/lfs/yocto/poky/meta-raspberrypi \
  /data/development/lfs/yocto/poky/meta-intel \
  /data/development/lfs/yocto/poky/meta-korg-spark \
  "
and local.conf relevant parts are:

MACHINE ??= "raspberrypi3-64"
IMAGE_INSTALL_append = " apt gdbserver openssh-sftp-server mdns-dev perfcnt-enable libasound alsa-utils-alsactl alsa-utils-alsamixer ${VIRTUAL-RUNTIME_alsa-state} libjack jack-server jack-utils"
CORE_IMAGE_EXTRA_INSTALL += " avahi-daemon"
TOOLCHAIN_HOST_TASK_append = " nativesdk-cmake"
EXTRA_IMAGE_FEATURES ?= "debug-tweaks x11-base tools-debug splash ssh-server-dropbear package-management"

Regarding our meta-korg-spark custom layer, it adds a linux recipe that just adds an entry to the cmdline.txt boot file.

**Comment by hhromic** [comment]
thanks, can you try the recent PR #257 please? 
we addressed now to only remove libwayland-egl from wayland only if userland is used at the same time.

**Comment by agherzan** [comment]
This is interesting because I don't see any `vc4graphics` setup there. @billj-korg please take a look at the PR @hhromic referenced above and tell us if it fixes your error.

**Comment by billj-korg** [comment]
I tried the change in PR #257 and it fixes the error.

**Comment by hhromic** [comment]
good stuff @billj-korg !  let us know if you find something else.
