### ISSUE TITLE
netopeer encountering alignment error when starting service

### ISSUE THREAD

**Issue by cclark1974** [agherzan/meta-raspberrypi#262]
I pulled the latest changes and Im still seeing the alignment errors when starting netopeer/sysrepo service.

```
May 19 03:26:54 raspberrypi3 daemon.info init: Id "S0" respawning too fast: disabled for 5 minutes                                                        

May 19 03:28:10 raspberrypi3 user.warn kernel: [26307.707117] Alignment trap: sysrepod (13191) PC=0x76e54c5c Instr=0xe8ae000f Address=0x7490563d FSR 0x801             

May 19 03:28:10 raspberrypi3 user.warn kernel: [26307.708698] Alignment trap: sysrepod (13191) PC=0x76e54c64 Instr=0xe8ae000f Address=0x7490564d FSR 0x801

May 19 03:28:10 raspberrypi3 user.warn kernel: [26307.710290] Alignment trap: sysrepod (13191) PC=0x76e54c6c Instr=0xe88e000f Address=0x7490565d FSR 0x801

May 19 03:28:10 raspberrypi3 user.warn kernel: [26307.712484] Alignment trap: sysrepod (13191) PC=0x76e53e84 Instr=0xe1c020f0 Address=0x74905711 FSR 0x801

May 19 03:28:10 raspberrypi3 user.warn kernel: [26307.714229] Alignment trap: sysrepod (13191) PC=0x76e71bdc Instr=0xedc70b0a Address=0x74905665 FSR 0x801

May 19 03:28:10 raspberrypi3 user.err kernel: [26307.716033] Alignment trap: not handling instruction edc70b0a at [<76e71bdc>]              

May 19 03:28:10 raspberrypi3 user.alert kernel: [26307.718002] Unhandled fault: alignment exception (0x801) at 0x74905665                   

May 19 03:28:10 raspberrypi3 user.alert kernel: [26307.720148] pgd = b7adc000                                                               

May 19 03:28:10 raspberrypi3 user.alert kernel: [26307.722442] [74905665] *pgd=37802835, *pte=36f6f75f, *ppte=36f6fc7f                      

May 19 03:28:10 raspberrypi3 daemon.err netopeer2-server[13197]: Unable to get list of schemas supported by sysrepo (The peer disconnected).

May 19 03:28:10 raspberrypi3 daemon.err netopeer2-server[13197]: Server init failed.                             

May 19 03:28:10 raspberrypi3 daemon.err netopeer2-server[13197]: nc_ps_clear: invalid argument (ps).

```

Im running master branch on the meta-raspberrypi 

I built on raspberry pi3, 32b arch.

Any further info needed please let me know

**Comment by betafive** [comment]
Hi, you say you're "still seeing" this error. Is there any previous discussion of this? It's not something I've seen before but I might have just missed it.

**Comment by agherzan** [comment]
@cclark1974 please update the description in such a way that it can provide context, build description, sources versions and ways to reproduce. The issue template has some content for a reason.

**Comment by cclark1974** [comment]
Local.conf:
#
# This file is your local configuration file and is where all local user settings
# are placed. The comments in this file give some guide to the options a new user
# to the system might want to change but pretty much any configuration option can
# be set in this file. More adventurous users can look at local.conf.extended
# which contains other examples of configuration which can be placed in this file
# but new users likely won't need any of them initially.
#
# Lines starting with the '#' character are commented out and in some cases the
# default values are provided as comments to show people example syntax. Enabling
# the option is a question of removing the # character and making any change to the
# variable as required.

#
# Machine Selection
#
# You need to select a specific machine to target the build with. There are a selection
# of emulated machines available which can boot and run in the QEMU emulator:
#
#MACHINE ?= "qemuarm"
#MACHINE ?= "qemuarm64"
#MACHINE ?= "qemumips"
#MACHINE ?= "qemumips64"
#MACHINE ?= "qemuppc"
#MACHINE ?= "qemux86"
#MACHINE ?= "qemux86-64"
#
# There are also the following hardware board target machines included for 
# demonstration purposes:
#
#MACHINE ?= "beaglebone-yocto"
#MACHINE ?= "genericx86"
#MACHINE ?= "genericx86-64"
#MACHINE ?= "mpc8315e-rdb"
#MACHINE ?= "edgerouter"
#
# This sets the default machine to be qemux86 if no other machine is selected:
#MACHINE ??= "qemux86"
MACHINE ??= "raspberrypi3"

#
# Where to place downloads
#
# During a first build the system will download many different source code tarballs
# from various upstream projects. This can take a while, particularly if your network
# connection is slow. These are all stored in DL_DIR. When wiping and rebuilding you
# can preserve this directory to speed up this part of subsequent builds. This directory
# is safe to share between multiple builds on the same machine too.
#
# The default is a downloads directory under TOPDIR which is the build directory.
#
#DL_DIR ?= "${TOPDIR}/downloads"
#IMAGE_FSTYPES += "wic.qcow2"

#
# Where to place shared-state files
#
# BitBake has the capability to accelerate builds based on previously built output.
# This is done using "shared state" files which can be thought of as cache objects
# and this option determines where those files are placed.
#
# You can wipe out TMPDIR leaving this directory intact and the build would regenerate
# from these files if no changes were made to the configuration. If changes were made
# to the configuration, only shared state files where the state was still valid would
# be used (done using checksums).
#
# The default is a sstate-cache directory under TOPDIR.
#
#SSTATE_DIR ?= "${TOPDIR}/sstate-cache"
ENABLE_UART = "1"

#
# Where to place the build output
#
# This option specifies where the bulk of the building work should be done and
# where BitBake should place its temporary files and output. Keep in mind that
# this includes the extraction and compilation of many applications and the toolchain
# which can use Gigabytes of hard disk space.
#
# The default is a tmp directory under TOPDIR.
#
#TMPDIR = "${TOPDIR}/tmp"

#
# Default policy config
#
# The distribution setting controls which policy settings are used as defaults.
# The default value is fine for general Yocto project use, at least initially.
# Ultimately when creating custom policy, people will likely end up subclassing 
# these defaults.
#
DISTRO ?= "poky"
# As an example of a subclass there is a "bleeding" edge policy configuration
# where many versions are set to the absolute latest code from the upstream 
# source control systems. This is just mentioned here as an example, its not
# useful to most new users.
# DISTRO ?= "poky-bleeding"

#
# Package Management configuration
#
# This variable lists which packaging formats to enable. Multiple package backends
# can be enabled at once and the first item listed in the variable will be used
# to generate the root filesystems.
# Options are:
#  - 'package_deb' for debian style deb files
#  - 'package_ipk' for ipk files are used by opkg (a debian style embedded package manager)
#  - 'package_rpm' for rpm style packages
# E.g.: PACKAGE_CLASSES ?= "package_rpm package_deb package_ipk"
# We default to rpm:
PACKAGE_CLASSES ?= "package_rpm"

#
# SDK target architecture
#
# This variable specifies the architecture to build SDK items for and means
# you can build the SDK packages for architectures other than the machine you are
# running the build on (i.e. building i686 packages on an x86_64 host).
# Supported values are i686 and x86_64
#SDKMACHINE ?= "i686"

#
# Extra image configuration defaults
#
# The EXTRA_IMAGE_FEATURES variable allows extra packages to be added to the generated
# images. Some of these options are added to certain image types automatically. The
# variable can contain the following options:
#  "dbg-pkgs"       - add -dbg packages for all installed packages
#                     (adds symbol information for debugging/profiling)
#  "dev-pkgs"       - add -dev packages for all installed packages
#                     (useful if you want to develop against libs in the image)
#  "ptest-pkgs"     - add -ptest packages for all ptest-enabled packages
#                     (useful if you want to run the package test suites)
#  "tools-sdk"      - add development tools (gcc, make, pkgconfig etc.)
#  "tools-debug"    - add debugging tools (gdb, strace)
#  "eclipse-debug"  - add Eclipse remote debugging support
#  "tools-profile"  - add profiling tools (oprofile, lttng, valgrind)
#  "tools-testapps" - add useful testing tools (ts_print, aplay, arecord etc.)
#  "debug-tweaks"   - make an image suitable for development
#                     e.g. ssh root access has a blank password
# There are other application targets that can be used here too, see
# meta/classes/image.bbclass and meta/classes/core-image.bbclass for more details.
# We default to enabling the debugging tweaks.
EXTRA_IMAGE_FEATURES ?= "debug-tweaks"
CORE_IMAGE_EXTRA_INSTALL = " \ 
kernel-modules \ 
lrzsz \ 
setserial \ 
strongswan \ 
opkg \ 
nbench-byte \ 
alsa-utils \ 
i2c-tools \ 
devmem2 \ 
dosfstools \ 
libdrm-tests \ 
netkit-ftp \ 
iptables \ 
bridge-utils \ 
socat \ 
wget \ 
curl \ 
vlan \ 
dhcp-server \ 
dhcp-client \ 
ntp \ 
libstdc++ \ 
nginx \ 
ppp \ 
proftpd \
boost \ 
openssl \ 
openssh \ 
fcgi \ 
mc \ 
ethtool \ 
minicom \ 
procps \ 
sysrepo \
netopeer2-server \
netopeer2-cli \
netopeer2-keystored \
netdata \
tcpdump \ 
file" 
KERNEL_MODULE_AUTOLOAD += "ip_gre"
EXTRA_USERS_PARAMS = "usermod -P thincpe root;"
PACKAGE_EXCLUDE += " procps "


#
# Additional image features
#
# The following is a list of additional classes to use when building images which
# enable extra features. Some available options which can be included in this variable
# are:
#   - 'buildstats' collect build statistics
#   - 'image-mklibs' to reduce shared library files size for an image
#   - 'image-prelink' in order to prelink the filesystem image
# NOTE: if listing mklibs & prelink both, then make sure mklibs is before prelink
# NOTE: mklibs also needs to be explicitly enabled for a given image, see local.conf.extended
USER_CLASSES ?= "buildstats image-mklibs image-prelink"

#
# Runtime testing of images
#
# The build system can test booting virtual machine images under qemu (an emulator)
# after any root filesystems are created and run tests against those images. To
# enable this uncomment this line. See classes/testimage(-auto).bbclass for
# further details.
#TEST_IMAGE = "1"
#
# Interactive shell configuration
#
# Under certain circumstances the system may need input from you and to do this it
# can launch an interactive shell. It needs to do this since the build is
# multithreaded and needs to be able to handle the case where more than one parallel
# process may require the user's attention. The default is iterate over the available
# terminal types to find one that works.
#
# Examples of the occasions this may happen are when resolving patches which cannot
# be applied, to use the devshell or the kernel menuconfig
#
# Supported values are auto, gnome, xfce, rxvt, screen, konsole (KDE 3.x only), none
# Note: currently, Konsole support only works for KDE 3.x due to the way
# newer Konsole versions behave
#OE_TERMINAL = "auto"
# By default disable interactive patch resolution (tasks will just fail instead):
PATCHRESOLVE = "noop"

#
# Disk Space Monitoring during the build
#
# Monitor the disk space during the build. If there is less that 1GB of space or less
# than 100K inodes in any key build location (TMPDIR, DL_DIR, SSTATE_DIR), gracefully
# shutdown the build. If there is less that 100MB or 1K inodes, perform a hard abort
# of the build. The reason for this is that running completely out of space can corrupt
# files and damages the build in ways which may not be easily recoverable.
# It's necesary to monitor /tmp, if there is no space left the build will fail
# with very exotic errors.
BB_DISKMON_DIRS ??= "\
    STOPTASKS,${TMPDIR},1G,100K \
    STOPTASKS,${DL_DIR},1G,100K \
    STOPTASKS,${SSTATE_DIR},1G,100K \
    STOPTASKS,/tmp,100M,100K \
    ABORT,${TMPDIR},100M,1K \
    ABORT,${DL_DIR},100M,1K \
    ABORT,${SSTATE_DIR},100M,1K \
    ABORT,/tmp,10M,1K"

#
# Shared-state files from other locations
#
# As mentioned above, shared state files are prebuilt cache data objects which can
# used to accelerate build time. This variable can be used to configure the system
# to search other mirror locations for these objects before it builds the data itself.
#
# This can be a filesystem directory, or a remote url such as http or ftp. These
# would contain the sstate-cache results from previous builds (possibly from other
# machines). This variable works like fetcher MIRRORS/PREMIRRORS and points to the
# cache locations to check for the shared objects.
# NOTE: if the mirror uses the same structure as SSTATE_DIR, you need to add PATH
# at the end as shown in the examples below. This will be substituted with the
# correct path within the directory structure.
#SSTATE_MIRRORS ?= "\
#file://.* http://someserver.tld/share/sstate/PATH;downloadfilename=PATH \n \
#file://.* file:///some/local/dir/sstate/PATH"

#
# Yocto Project SState Mirror
#
# The Yocto Project has prebuilt artefacts available for its releases, you can enable
# use of these by uncommenting the following line. This will mean the build uses
# the network to check for artefacts at the start of builds, which does slow it down
# equally, it will also speed up the builds by not having to build things if they are
# present in the cache. It assumes you can download something faster than you can build it
# which will depend on your network.
#
#SSTATE_MIRRORS ?= "file://.* http://sstate.yoctoproject.org/2.5/PATH;downloadfilename=PATH"

#
# Qemu configuration
#
# By default qemu will build with a builtin VNC server where graphical output can be
# seen. The two lines below enable the SDL backend too. By default libsdl-native will
# be built, if you want to use your host's libSDL instead of the minimal libsdl built
# by libsdl-native then uncomment the ASSUME_PROVIDED line below.
PACKAGECONFIG_append_pn-qemu-native = " sdl"
PACKAGECONFIG_append_pn-nativesdk-qemu = " sdl"
#ASSUME_PROVIDED += "libsdl-native"

# CONF_VERSION is increased each time build/conf/ changes incompatibly and is used to
# track the version of this file when it was generated. This can safely be ignored if
# this doesn't mean anything to you.
CONF_VERSION = "1"

Build info:
Build Configuration:
BB_VERSION           = "1.37.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "universal-4.8"
TARGET_SYS           = "arm-poky-linux-gnueabi"
MACHINE              = "raspberrypi3"
DISTRO               = "poky"
DISTRO_VERSION       = "2.5"
TUNE_FEATURES        = "arm armv7ve vfp thumb neon vfpv4 callconvention-hard cortexa7"
TARGET_FPU           = "hard"
meta                 
meta-poky            
meta-yocto-bsp       = "master:5479654eeaaa0f81bfff54ca49369c87f1658705"
meta-oe              
meta-networking      
meta-webserver       
meta-python          
meta-multimedia      = "master:a19aa29f7fa336cd075b72c496fe1102e6e5422b"
meta-raspberrypi     = "master:1fb4dcc0b57bb51aac9c047f17048e1121b690fb"
meta-sysrepo         = "master:f966edff8a88cf0834b55cb151d2cb3443ba53a6"



after booting the raspberry pi with the img, I attempt to start netopeer by:
/etc/init.d/netopeer start 

that is when I encounter this error.

**Comment by cclark1974** [comment]
bblayers:
NOTE: Starting bitbake server...
layer                 path                                      priority
==========================================================================
meta                  /root/Yocto/poky/meta                     5
meta-poky             /root/Yocto/poky/meta-poky                5
meta-yocto-bsp        /root/Yocto/poky/meta-yocto-bsp           5
meta-oe               /root/Yocto/poky/meta-openembedded/meta-oe  6
meta-networking       /root/Yocto/poky/meta-openembedded/meta-networking  5
meta-webserver        /root/Yocto/poky/meta-openembedded/meta-webserver  6
meta-python           /root/Yocto/poky/meta-openembedded/meta-python  7
meta-multimedia       /root/Yocto/poky/meta-openembedded/meta-multimedia  6
meta-raspberrypi      /root/Yocto/poky/meta-raspberrypi         9
meta-sysrepo          /root/Yocto/poky/meta-sysrepo             6

**Comment by hhromic** [comment]
hi @cclark1974 , can you please use [fenced code-blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/#fenced-code-blocks) for your pasted information/files so they are *much more* readable here in github? Thanks :)

**Comment by cclark1974** [comment]
any updates on this issue?  is there more info needed?

**Comment by betafive** [comment]
I just had a quick look around at the `meta-sysrepo` layer and at `sysrepo` itself. Perhaps this is related to https://github.com/sysrepo/sysrepo/issues/947 ? You may need to modify the config options in the sysrepo recipe to disable the feature that's discussed in that issue.

**Comment by agherzan** [comment]
The above-mentioned issue is the only guess I have as well. I would recommend you to either add additional information to that bug or report it to rpi kernel repository. As far as I can tell at this point it doesn't sound like an issue with the yocto layer.

**Comment by pbrkr** [comment]
@agherzan recommend we close this issue now as there's been no update in over a year.
