### ISSUE TITLE
yocto-ci seems to be stuck?

### ISSUE THREAD

**Issue by hhromic** [agherzan/meta-raspberrypi#294]
I noticed that in the recent PRs, the yocto-ci is stuck baking happy raspberries (starting in PR #287). The pending jobs are actually "SUCCEED" in the CI, however here in GitHub they are still marked as pending and as a result there is a pile of PR waiting to be tested since days. Any clues?

**Comment by agherzan** [comment]
I'm looking into it today.

**Comment by agherzan** [comment]
Should be fixed. Closing.
