### ISSUE TITLE
OOM issue with gstreamer

### ISSUE THREAD

**Issue by aswathisivan** [agherzan/meta-raspberrypi#319]
**Description**

I am getting OOM issue while using 10 gstreamer pipellines simultaneously with **_Yocto built linux distro_** but not with Raspbian.

**Steps to reproduce the issue:**
1. I am using raspberry pi 3B which has linux distribution built using yocto (https://git.yoctoproject.org/cgit/cgit.cgi/poky/tree/). I took the meta raspberry from https://git.yoctoproject.org/cgit/cgit.cgi/meta-raspberrypi/tree/. I then included the recipe to include gstreamer 1.14.2.
  bitbake rpi-basic-image
2. Pipeline which I used for all the cameras: 
gst-launch-1.0 -e rtspsrc location="rtsp://<username:password@IPdetails>" name = d \
! rtph264depay ! h264parse ! splitmuxsink name = mux location=~/media/a1_video%02d.mp4 max-size-time=2000000000 max-files=5 &
3. When I am video streaming 4 IP cameras simultaneously using gstreamer the RAM usage is going till 500 MB. 
4. When I do the video streaming with 10 IP cameras the RAM is getting completely utilized and OOM_killer is invoked to kill the pipeline.

**Describe the results you received:**
So with yocto built Linux and running 10 video streaming of IP cameras using gstreamer version, the RAM is getting exhausted and OOM_Killer is invoked

**Describe the results you expected:**
I have ran the same pipeline in raspbian OS for 10 IP cameras, but in this the RAM usage hold to 440 MB.

**Additional information you deem important (e.g. issue happens only occasionally):**
Since the gstreamer version in yocto Linux is 1.14.2 and in raspbian is 1.10.4. I tried the gst-uninstalled 1.14.2 in Raspbian to see if gstreamer version might be making difference, but the RAM usage in Raspbian seems to be same in both the 1.10.4 and 1.14.2. 

**Additional details (revisions used, host distro, etc.):**
Yocto Built Linux:
Kernel version : 4.14.68
gstreamer version: 1.14.2

raspbian:
Kernel version: 4.14.5
gstreamer version: 1.10.4

**_Why the RAM would be growing and exhausted in yocto built Linux distro but not Raspbian ? Any help or clue is much appreciated._**

**Comment by agherzan** [comment]
Do you see any major differences in between process memory consumption on both the distros? I would try to see what eats more memory on a yocto build. As well, do you use the same `config.txt`?

**Comment by aswathisivan** [comment]
- The max value of %MEM in Raspbian is 5.1% for gstreamer. And in yocto the %VSZ is 38%. 
- I couldnt find config.txt in yocto built distro. 

I am adding more information here just in case it might be useful:

**top command result:** 
In yocto _(here only 4 pipelines are running)_:
```
Mem: 565164K used, 435012K free, 204K shrd, 10800K buff, 73204K cached
CPU:  16% usr   1% sys   0% nic  81% idle   0% io   0% irq   1% sirq
Load average: 0.53 0.51 1.05 5/149 647
  PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
  550   458 root     S     368m  38%  13% gst-launch-1.0 -e
  475   446 root     S     182m  19%   2% gst-launch-1.0 -e
  515   454 root     S     213m  22%   2% gst-launch-1.0 -e 
  493   450 root     S     221m  23%   1% gst-launch-1.0 -e 
```

In raspbian _(here 8 pipelines are running)_:
```
	top - 10:12:26 up  1:00,  3 users,  load average: 2.85, 4.73, 4.92
Tasks: 137 total,   1 running,  90 sleeping,   0 stopped,   1 zombie
%Cpu(s):  7.3 us,  2.5 sy,  0.0 ni, 87.3 id,  0.7 wa,  0.0 hi,  2.3 si,  0.0 st
KiB Mem :   949452 total,   436512 free,   270648 used,   242292 buff/cache
KiB Swap:   102396 total,   102396 free,        0 used.   614180 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                       
 1036 pi        20   0  137944  25032  11076 S   8.6  2.6   3:20.93 gst-launch-1.0                                                                                                                                                
 1049 pi        20   0  160472  48144  11040 S   8.3  5.1   3:13.63 gst-launch-1.0                                                                                                                                                
 1082 pi        20   0  196596  35024  11008 S   8.3  3.7   3:15.65 gst-launch-1.0                                                                                                                                                
 1103 pi        20   0  189040  27852  10908 S   5.3  2.9   2:34.79 gst-launch-1.0                                                                                                                                                
 1062 pi        20   0  189040  27736  10832 S   3.6  2.9   1:54.12 gst-launch-1.0                                                                                                                                                
 1122 pi        20   0  133700  21072  10940 S   3.3  2.2   1:14.22 gst-launch-1.0                                                                                                                                                
 1135 pi        20   0  130672  18264  11000 S   2.0  1.9   0:51.48 gst-launch-1.0                                                                                                                                                
 1167 pi        20   0  180848  18548  10876 S   2.0  2.0   0:48.26 gst-launch-1.0 
```

**config.txt data in Raspbian:**
```
dtparam=audio=on
hdmi_force_hotplug=1
```

**local.conf in yocto:**

```
MACHINE ??= "raspberrypi3"
CONF_VERSION = "1"
GPU_MEM = "16"
IMAGE_INSTALL_append = " connman connman-client gstreamer1.0 gstreamer1.0-plugins-bad gstreamer1.0-plugins-good  gstreamer1.0-plugins-base libnice json-glib  libsoup-2.4 "
ENABLE_UART = "1"
LICENSE_FLAGS_WHITELIST="commercial"
DISTRO_FEATURES_append = " systemd"
VIRTUAL-RUNTIME_init_manager = "systemd"
DISTRO_FEATURES_BACKFILL_CONSIDERED = "sysvinit"
```

Also do you think it makes any difference by putting **raspberrypi3-64** in MACHINE?

**Comment by agherzan** [comment]
Just copy thw config.txt from raspbian to yocto and try to reproduce.

**Comment by aswathisivan** [comment]
I copied the config.txt in the /boot/ path of yocto and rebooted the board. It didn't make any difference. 
I just want to point out that the only configuration I see enabled in Raspbian /boot/config.txt is:

```
dtparam=audio=on
hdmi_force_hotplug=1
```
Do you think I should bitbake with **raspberrypi3-64** as **MACHINE**?

**Comment by agherzan** [comment]
How is the raspbian you are comparing against compiled? Is it for armv7 or 8?

**Comment by aswathisivan** [comment]
Raspberry pi 3B is ARMv8, so I am assuming NOOBS installed the Raspbian
according to ARMv8.

**Comment by agherzan** [comment]
What is `uname -a` returning on your installed raspbian?

**Comment by aswathisivan** [comment]
The uname output says armv7:

Linux raspberrypi 4.14.50-v7+ #1122 SMP Tue Jun 19 12:26:26 BST 2018 armv7l

**Comment by kraj** [comment]
this can be a bug in OE gstreamer, but we need a way to reproduce it.

**Comment by TaruntejK** [comment]
Hi, 
If you have an IP camera with RTSP, H264 support, the easiest way to reproduce this issue is use just one pipeline as below:

`gst-launch-1.0  -e rtspsrc location="rtsp://<user>:<pass>@<url>" name = d !  rtph264depay ! h264parse ! avdec_h264  ! x264enc ! h264parse ! splitmuxsink name = mux location=a1_video%02d.mp4 max-size-time=2000000000 max-files=5`

The difference from the original pipeline mentioned by @aswathisivan above is that we added extra `decode > encode > parse` in the new pipeline. 
With this addition in the pipeline running just one pipeline:

**In Yocto build. gstreamer 1.14.2**
The memory very rapidly reaches 900+MB 

**In Rapsbian. gstreamer 1.10.4**
The memory reached 450MB very rapidly and from there it slowly gone past 500MB now.

I am about to try with gst-uninstalled 1.14.2 in raspbian now.

**Comment by kraj** [comment]
Can you try using thumb2 ISA, if you can try using Yoe distro it is default see.
https://github.com/YoeDistro/yoe-distro

**Comment by agherzan** [comment]
@aswathisivan Have you done anything in regards to this? I'm wodering if this issue is still valid.

**Comment by pbrkr** [comment]
Closed as there's been no update in 12 months.
