### ISSUE TITLE
ARMv8 for raspberrypi3 32 bit?

### ISSUE THREAD

**Issue by michaelbaisch** [agherzan/meta-raspberrypi#321]
I'm wondering why `cortexa7` is used for `raspberrypi3`machine configuration. Is there any reason why

```
DEFAULTTUNE ?= "cortexa7thf-neon-vfpv4"
require conf/machine/include/tune-cortexa7.inc
```

should not be:

```
DEFAULTTUNE ?= "cortexa8thf-neon-vfpv4"
require conf/machine/include/tune-cortexa8.inc
```

in `conf/machine/raspberrypi3.conf` ?

When we searched online how to compile for the Raspberry Pi 3, people suggested to use `armv8`.

**Comment by agherzan** [comment]
Take a look at https://github.com/agherzan/meta-raspberrypi/blob/master/conf/machine/raspberrypi3-64.conf

**Comment by michaelbaisch** [comment]
I have already looked at this. 

In `conf/machine/include/arm/arch-armv8.inc` it says `require conf/machine/include/arm/arch-arm64.inc`, which is obviously for 64 bit. `raspberrypi3.conf` is for 32 bit, which is what I need. This is why I asked if we could not just change `tune-cortexa7.inc` to `tune-cortexa8.inc`, with the proper `DEFAULTTUNE`?

**Comment by schnitzeltony** [comment]
@michaelbaisch  Raspi is cortexa7 (as far as I remember cortexa8 is quite old - e.g beaglebone).

**Comment by agherzan** [comment]
Oh. I've misread it. I think it was just something we haven't looked into and most probably inherited from RaspberryPi 2. Would you be willing to do some testing and see how it behave compared to ca7?

**Comment by agherzan** [comment]
Actually, I just realised that cortexa8 is an older variant.

**Comment by michaelbaisch** [comment]
Oh okay this is a bit confusing. So `cortexa8` is older than `cortexa7`, and this is what I would have changed with the `tune-cortexa***.inc` files. What I really want is the `ARMv8-A` architecture instead of the `ARMv7-A` architecture. I was confused by the `7` and `8` in the cortex name in relation to the `armv` architecture name. And the architecture is chosen by the `include/arm/arch-armv***.inc` files. And there the only `armv8` file is 64 bit only. So no luck for `armv8` and 32 bit?

**Comment by agherzan** [comment]
So what is the problem you are facing?

**Comment by michaelbaisch** [comment]
We wanted to compile our code with something like `-march=armv8-a+crc -mfpu=neon-fp-armv8` and right now we have `-march=armv7ve -mfpu=neon-vfpv4`.

**Comment by michaelbaisch** [comment]
The Raspberry 3 (B+) actually has a Cortex-A53 (ARMv8).

https://www.raspberrypi.org/products/raspberry-pi-3-model-b-plus/

And right now this here is running with `-march=armv7ve -mcpu=cortex-a7`. I'm guessing this is not optimal?

**Comment by michaelbaisch** [comment]
As far as I can tell there is no way to use `ARMv8` in the aarch32 mode in yocto right now. Also I think there is no way to select the right tune `cortex-a53` for my raspberry, since the highest I found in yocto was `cortex-a17`. Other people have [done this](https://github.com/axxia/meta-axxia/tree/master/conf/machine/include), I'm not sure why those options for `ARMv8` aren't available in yocto…

**Comment by agherzan** [comment]
Do you see any performance impact with the current one we have?

**Comment by kraj** [comment]
We wanted to keep armv8 as common as possible, in essence similar to x86_64, if someone has real numbers to prove that current tunes are not optimal for real world loads I would be interested to take it further. I have benchmarked current tunes quite a bit as well for my usecases and they hardly make any difference.

**Comment by kraj** [comment]
> We wanted to compile our code with something like `-march=armv8-a+crc -mfpu=neon-fp-armv8` and right now we have `-march=armv7ve -mfpu=neon-vfpv4`.

if you use ```MACHINE = "raspberrypi3-64"``` you should be getting armv8 tunes. by default ```MACHINE = "raspberrypi3"``` is 32-bit in OE speak.

**Comment by agherzan** [comment]
@michaelbaisch please run some tests and see if you can spot any improvements. For the meanwhile, I'll close this issue but feel free to comment on your findings.
