### ISSUE TITLE
create packagegroup-rpi-base

### ISSUE THREAD

**Issue by pabigot** [agherzan/meta-raspberrypi#329]
To provide a good upgrade path in future, it would be good to also create a `packagegroup-rpi-base` which rdepends on the firmware and other "base" packages, thus providing an upgrade path.

_Originally posted by @otavio in https://github.com/agherzan/meta-raspberrypi/issues/298#issuecomment-438351113_

**Comment by kraj** [comment]
Its better that machine specific packages like firmware are added via ```MACHINE_RRECOMMENDS```

Creating a packagegroup will endup in creating machine specific overrides for different RPI machines
