### ISSUE TITLE
Waveshare 10.1inch display touch panel in eglfs 

### ISSUE THREAD

**Issue by Jozefiel** [agherzan/meta-raspberrypi#350]
Hi
I have problem with interfacing this display (Waveshare 10.1) with yocto. 
HDMI work well, but touchscreen don´t work.
My image include tslib but touchpanel is not recognized and is not attached in /proc/bus/input/devices
I need to run my app on eglfs platform without X11. 
Any idea how to solve this? 
Thanks Jozef

**Comment by koolkhel** [comment]
@Jozefiel is hid-multitouch present within the rootfs? Is it loaded? If it is there and loaded manually, does the panel work?

**Comment by Jozefiel** [comment]
Hi @koolkhel . Thanks for your answer.
hid-multitouch is included in rootfs. how can I check if the driver is loaded? and how to load this driver?
My image is based on rpi-basic-image, where are imported qt packages. local.conf is also setted for waveshare display. I have writed .bb for newest tslib , where are libs for waveshare. But i don´t have idea, what is wrong. I am starting with yocto

**Comment by koolkhel** [comment]
@Jozefiel try 'lsmod | grep touch' to see if the module is loaded. It should be detected automatically, though. So, when I had similar issues, I just had to set a few kernel options and that was it. hid-multitouch should work with tools like 'evtest' to see if there's anything coming on from the panel. Qt doesn't use tslib by default, so I'd rather not think much about this part.

**Comment by Jozefiel** [comment]
@koolkhel module is not loaded. probably is problem in my kernel settings. in original image for this touch display from waveshare page is used driver ads7846. but my kernel don´t include this. what kind of changes you done during solving your issues?

**Comment by Jozefiel** [comment]
problem solved :-)
i clone from original waveshare image raspberrypi partition, overlays directory
spi0-cs.dtbo spi0-hw-cs.dtbo and ads7846.dtbo to my sd card boot partition

in meta-raspberrypi/recipes-bsp/bootfile/ is added
rpi-config_git.bbapend with configurations parameters

SRCREV = "648ffc470824c43eb0d16c485f4c24816b32cd6f"

do_deploy_append() {
  echo "display_rotate=0" >>${DEPLOYDIR}/bcm2835-bootfiles/config.txt
  echo "hdmi_force_hotplug=1" >>${DEPLOYDIR}/bcm2835-bootfiles/config.txt
  echo "hdmi_group=2" >>${DEPLOYDIR}/bcm2835-bootfiles/config.txt
  echo "hdmi_mode=87" >>${DEPLOYDIR}/bcm2835-bootfiles/config.txt
  echo "hdmi_cvt=1024 600 60 6 0 0 0" >>${DEPLOYDIR}/bcm2835-bootfiles/config.txt
  echo "hdmi_drive=1" >>${DEPLOYDIR}/bcm2835-bootfiles/config.txt
  echo "max_usb_current=1" >>${DEPLOYDIR}/bcm2835-bootfiles/config.txt
  echo "dtparam=spi=on" >>${DEPLOYDIR}/bcm2835-bootfiles/config.txt
  echo "dtparam=i2c_arm=on" >>${DEPLOYDIR}/bcm2835-bootfiles/config.txt
  echo "dtoverlay=ads7846,penirq=25,speed=10000,keep_vref_on=0,penirq_pull=2,xohms=150" >>${DEPLOYDIR}/bcm2835-bootfiles/config.txt

}

display was loaded as hwmon module
touch events is possible check with sudo hexdump /dev/input/touchscreen0 

thanks for helping

**Comment by systemmind** [comment]
> problem solved :-)
> i clone from original waveshare image raspberrypi partition, overlays directory
> spi0-cs.dtbo spi0-hw-cs.dtbo and ads7846.dtbo to my sd card boot partition
> 
> in meta-raspberrypi/recipes-bsp/bootfile/ is added
> rpi-config_git.bbapend with configurations parameters
> 
> SRCREV = "648ffc470824c43eb0d16c485f4c24816b32cd6f"
> 
> do_deploy_append() {
> echo "display_rotate=0" >>${DEPLOYDIR}/bcm2835-bootfiles/config.txt
> echo "hdmi_force_hotplug=1" >>${DEPLOYDIR}/bcm2835-bootfiles/config.txt
> echo "hdmi_group=2" >>${DEPLOYDIR}/bcm2835-bootfiles/config.txt
> echo "hdmi_mode=87" >>${DEPLOYDIR}/bcm2835-bootfiles/config.txt
> echo "hdmi_cvt=1024 600 60 6 0 0 0" >>${DEPLOYDIR}/bcm2835-bootfiles/config.txt
> echo "hdmi_drive=1" >>${DEPLOYDIR}/bcm2835-bootfiles/config.txt
> echo "max_usb_current=1" >>${DEPLOYDIR}/bcm2835-bootfiles/config.txt
> echo "dtparam=spi=on" >>${DEPLOYDIR}/bcm2835-bootfiles/config.txt
> echo "dtparam=i2c_arm=on" >>${DEPLOYDIR}/bcm2835-bootfiles/config.txt
> echo "dtoverlay=ads7846,penirq=25,speed=10000,keep_vref_on=0,penirq_pull=2,xohms=150" >>${DEPLOYDIR}/bcm2835-bootfiles/config.txt
> 
> }
> 
> display was loaded as hwmon module
> touch events is possible check with sudo hexdump /dev/input/touchscreen0
> 
> thanks for helping

I had the same issue with `core-image-sato` image and your solution had fixed my issue too. But when I am trying to make custom image based on core-image-base target with `mini_x` session I am getting black screen after adding `ads7846.dtbo` to the `/boot/overlays` and the screen stays black even if I remove this file and reboot the system. Also I cannot see any touchscreens in `/dev/input` folder. Do you have any idea how to get working touchscreen in my case?

This is my custom image receipt:
```python
IMAGE_FEATURES_append = " splash x11-base hwcodecs ssh-server-openssh post-install-logging allow-empty-password empty-root-password"

IMAGE_INSTALL = "\
    packagegroup-core-boot \
    packagegroup-core-full-cmdline \
    psplash \
    sudo vim git curl htop wget unzip usbutils ntp ntpdate mongodb \
    xf86-video-fbdev \
    cups nss libxscrnsaver alsa-lib \
    ${CORE_IMAGE_EXTRA_INSTALL} \
    "

inherit core-image extrausers
```

Thanks.
