### ISSUE TITLE
Wiringpi: DYN_VERS_MAJ variable in Makefiles is unset

### ISSUE THREAD

**Issue by erikhh** [agherzan/meta-raspberrypi#362]
**Description**
When using the wiringpi recipe, `sysroot-destdir/usr/lib` contains the following files after building:

```
Dec 14 14:16 libwiringPiDev.so -> libwiringPiDev.so.2.46
Dec 14 14:16 libwiringPiDev.so. -> libwiringPiDev.so.2.46
Dec 14 14:16 libwiringPiDev.so.2.46
Dec 14 14:16 libwiringPi.so -> libwiringPi.so.2.46
Dec 14 14:16 libwiringPi.so. -> libwiringPi.so.2.46
Dec 14 14:16 libwiringPi.so.2.46
```

**Steps to reproduce the issue:**
On the thud branch.
Just add `wiringpi` to `IMAGE_INSTALL_append`.

**Describe the results you received:**

```
Dec 14 14:16 libwiringPiDev.so -> libwiringPiDev.so.2.46
Dec 14 14:16 libwiringPiDev.so. -> libwiringPiDev.so.2.46
Dec 14 14:16 libwiringPiDev.so.2.46
Dec 14 14:16 libwiringPi.so -> libwiringPi.so.2.46
Dec 14 14:16 libwiringPi.so. -> libwiringPi.so.2.46
Dec 14 14:16 libwiringPi.so.2.46
```

**Describe the results you expected:**

```
Dec 14 14:16 libwiringPiDev.so -> libwiringPiDev.so.2.46
Dec 14 14:16 libwiringPiDev.so.2 -> libwiringPiDev.so.2.46
Dec 14 14:16 libwiringPiDev.so.2.46
Dec 14 14:16 libwiringPi.so -> libwiringPi.so.2.46
Dec 14 14:16 libwiringPi.so.2 -> libwiringPi.so.2.46
Dec 14 14:16 libwiringPi.so.2.46
```

**Additional information you deem important (e.g. issue happens only occasionally):**

I think this is caused by the variable `DYN_VERS_MAJ` in `wiringPi/Makefile` and `devLib/Makefile` not getting a value. It's not clear to me at all where it should get a value from. 

I ran a build where I hardcoded `DYN_VERS_MAJ=2` in both Makefiles, that does produce the right output but I doubt it's a durable fix.

If someone can point me in the direction of a durable fix I'll make a PR out of it.

**Comment by agherzan** [comment]
It sounds like a bug in the package itself. What version of wiringpi is this? Can you try to downgrade and see what you get?

**Comment by agherzan** [comment]
This was fixed on thud but awaits patch to master as well.

**Comment by erikhh** [comment]
Like this? https://github.com/agherzan/meta-raspberrypi/pull/385

**Comment by agherzan** [comment]
Yes. Thanks @erikhh .

**Comment by agherzan** [comment]
Fixed in master too.
