### ISSUE TITLE
No recipes available issue :  bpftool.bbappend

### ISSUE THREAD

**Issue by robin0338** [agherzan/meta-raspberrypi#366]
**Description**
I following "Quick Start" to generate image file.
But now i stuck in bitbake core-image-base step.

Meta-raspberrypi : Master

**Steps to reproduce the issue:**
1.Modify bblayers.conf file, add  [/*Destination Path*/raspberry/poky/meta-raspberrypi] .
2.Modify local.conf file , add [MACHINE = "raspberrypi3-64"].
3.Bitbake core-image-base.

**Describe the results you received:**
After the process finish , I got information below.

No recipes available for : /"Destination Path"/meta-raspberrypi/recipes-kernel/linux/bpftool.bbappend

![image](https://user-images.githubusercontent.com/7358284/50274270-c721a100-0477-11e9-9dc4-87acb137fe33.png)

**Comment by robin0338** [comment]
I am using latest master branch.

**Comment by agherzan** [comment]
@robin0338 I think this was fixed. Pull master and retest, please.

**Comment by jmunsin** [comment]
I also get the same error with the latest master.

**Comment by agherzan** [comment]
Closing issue as per above confirmation.

**Comment by jperezminguez** [comment]
Hi,
I got the same result when I forgot to include the layers from openembedded:
meta-oe, meta-multimedia, meta-networking, meta-python

**Comment by agherzan** [comment]
@jperezminguez Pull master and check it out again.
