### ISSUE TITLE
External wifi LAN card problems after updating firmware

### ISSUE THREAD

**Issue by cws7777** [agherzan/meta-raspberrypi#37]
Hi,
I'm having an issue with external wifi LAN card after updating firmware. 
It works fine before updating firmware but not now.
Giving me dmesg like below,

usb 1-1.3: ath9k_htc: Firmware ath9k_htc/htc_9271-1.4.0.fw requested
[    4.877941] usb 1-1.3: Direct firmware load for ath9k_htc/htc_9271-1.4.0.fw failed with error -2
[    4.877966] usb 1-1.3: ath9k_htc: Firmware htc_9271.fw requested
[    4.878020] usb 1-1.3: Direct firmware load for htc_9271.fw failed with error -2
[    4.878029] usb 1-1.3: no suitable firmware found!
[    4.878036] usb 1-1.3: ath9k_htc: Failed to get firmware htc_9271.fw
[    4.880936] usb 1-1.3: ath9k_htc: USB layer deinitialized

Any solutions or ideas?

Thank you and hope have a great day!

Best,
Paul

**Comment by agherzan** [comment]
Hi. This output tells you exactly that you miss some firmware for that dongle. I don't know how is that relevant on the firmware update, but you need them on the filesystem.

Found one here: https://github.com/OpenELEC/wlan-firmware/blob/master/firmware/ath9k_htc/htc_9271-1.4.0.fw
