### ISSUE TITLE
Raspberry Pi 3 Model A+ support

### ISSUE THREAD

**Issue by xuhcc** [agherzan/meta-raspberrypi#373]
Is [Raspberry Pi 3 A+](https://www.raspberrypi.org/products/raspberry-pi-3-model-a-plus/) board supported? 

I tried to boot image built for `raspberrypi3` target and it didn't boot (sumo branch).

**Comment by agherzan** [comment]
@xuhcc Can you try with thud? I know there were some updates needed for this support and I'm not sure if it caught sumo branch.

**Comment by xuhcc** [comment]
Thanks, 3A+ booted successfuly with thud. WiFi is not working, but it could be a problem with my custom layer.

**Comment by agherzan** [comment]
Great. Check wifi firmware and test with managers like networkmanager.

**Comment by markuswurz** [comment]
@xuhcc Have the same issue, did you get it to work?
