### ISSUE TITLE
raspberrypi0w - no wifi interface on thud branch

### ISSUE THREAD

**Issue by nandra** [agherzan/meta-raspberrypi#375]
Build image for raspberrypi0w  from thud branch. After startup check ifconfig -a and no wlan0 interface was present. Anyway FW files are present:
```
ls /lib/firmware/brcm/
BCM43430A1.hcd          brcmfmac43430-sdio.bin  brcmfmac43430-sdio.txt
```
**Steps to reproduce the issue:**
1. build image from thud branch for rpi0w

**Describe the results you received:**
No wlan0 interface available

**Describe the results you expected:**
wlan0 interface should be working

**Comment by agherzan** [comment]
Hi @nandra . Can you attach the `dmesg` log?

**Comment by nandra** [comment]
Sure: https://pastebin.com/AG7YVdVD

+ I also enabled u-boot for rpi (needed for rauc update)

Looks like wifi driver is not probed at all.

**Comment by nandra** [comment]
@agherzan any ideas? I know for sure that on rocko ifi was working. I can bisect maybe but it will take some time ;)

**Comment by agherzan** [comment]
@nandra That is strange indeed. I'd have to take a look (but that will happen after I get rid of this annoying cold).

**Comment by kraj** [comment]
@nandra what does `ifconfig -a` says

**Comment by nandra** [comment]
@kraj shows only lo interface nothing more (lsmod also doesn't report any wifi drivers available while bluetooth driver is loaded).

**Comment by kraj** [comment]
that means its not getting right firmware in image, can you try to manually copy the /lib/firmware directory from  a working SD card to thud and see if that helps.

**Comment by agherzan** [comment]
@kraj But that should have been shown in dmesg, isn't it?

**Comment by kraj** [comment]
@agherzan good point, (with another sip of morning tea) I looked at dmesg again and I don't see it loading `brcmfmac` module which means the wifi chip will go undetected, can we find out why this module is not being loaded ?

**Comment by nandra** [comment]
Asked for help also here as it looks like kernel issue: https://github.com/raspberrypi/linux/issues/2842

**Comment by nandra** [comment]
Looks like wifi chip became dead somehow (pls see info here:) https://github.com/raspberrypi/linux/issues/2842

Basically tried raspbian and interface is also not preset.

**Comment by agherzan** [comment]
@nandra can you retry the version you know for sure it was working? We found something similar with a testing device lately.

**Comment by nandra** [comment]
@agherzan ok building image now and will do the shot

**Comment by nandra** [comment]
@agherzan I flashed image for whcih I have confirmed wifi works on other rpi0w but not on mine. So I think my HW is really dead. Can you try raspbian if wifi will work there? Thanks.

**Comment by agherzan** [comment]
@nandra I actually did and it is reproducible but it seems like a different issue (maybe?): https://github.com/RPi-Distro/repo/issues/122

**Comment by nandra** [comment]
@agherzan  Hmm in my log there are no such issues. So also in raspbian image you don't have wifi interface? I had yesterday confirmation that image build on rocko wifi works perfectly fine. Weird :)

**Comment by agherzan** [comment]
That is correct, It fails as well in raspbian for this OTG + Wifi dongle setup. But only when rebooting for a couple of times.

**Comment by nandra** [comment]
So for first few time everything is fine but then later after reboot make troubles. Maybe ask on linux-raspberrypi github

**Comment by agherzan** [comment]
That's the plan. For now, I'll let the raspbian guys know.

**Comment by nandra** [comment]
Looks like also raspbian have an issue: https://github.com/raspberrypi/linux/issues/2846

**Comment by nandra** [comment]
Also pls note: https://github.com/raspberrypi/linux/issues/2846#issuecomment-460177049
