### ISSUE TITLE
How can I add gstreamer1.0-libav for streaming mp4 video songs in meta-raspberry?

### ISSUE THREAD

**Issue by madhu2051** [agherzan/meta-raspberrypi#376]
I am trying to add gstreamer1.0-libav in meta-raspberry  to support for streaming of mp4 videos.

I've added the following lines in local.conf file

IMAGE_INSTALL_append = " gstreamer1.0-libav"
LICENSE_FLAGS_WHITELIST_append = "commercial_gstreamer1.0-libav"
LICENSE_FLAGS_WHITELIST_append = "commercial_avdec_h264 "
PACKAGECONFIG_pn-gstreamer1.0-libav = "avdec_h264"

Whenever I am trying to build with the above changes, I am getting the following errors:
WARNING: gstreamer1.0-libav-1.12.2-r0 do_configure: QA Issue: gstreamer1.0-libav: invalid PACKAGECONFIG: avdec_h264 [invalid-packageconfig]
WARNING: agl-demo-platform-1.0-r0 do_rootfs: [log_check] agl-demo-platform: found 2 warning messages in the logfile:

Please help me to resolve this issue.

**Comment by madhu2051** [comment]
Instead of specifying avdec_h264 element, I've installed the entire gstreamer1.0-libav plugin. Now I am able to stream the videos.

**Comment by Shravansingh** [comment]
Hello @madhu2051,

I too am trying to play some video on my raspberry-pi cm3. Can you please share how did you run the videos?
