### ISSUE TITLE
Boot partition should be fat32

### ISSUE THREAD

**Issue by rosterloh** [agherzan/meta-raspberrypi#382]
**Description**
As per the [Raspberry Pi documentation](https://www.raspberrypi.org/documentation/hardware/computemodule/cm-emmc-flashing.md) there is an issue with some compute modules when the boot partition is not FAT32. 

**Steps to reproduce the issue:**
1. Build image
2. Check partitions using gparted

**Describe the results you received:**
Some images don't boot on a compute module

**Describe the results you expected:**
Should boot

**Additional information you deem important (e.g. issue happens only occasionally):**
As I see it line [114 of lasses/sdcard_image-rpi.bbclass](https://github.com/agherzan/meta-raspberrypi/blob/master/classes/sdcard_image-rpi.bbclass#L114) should change from 
```
    mkfs.vfat -n "${BOOTDD_VOLUME_ID}" -S 512 -C ${WORKDIR}/boot.img $BOOT_BLOCKS
```
to 
```
    mkfs.vfat -F32 -n "${BOOTDD_VOLUME_ID}" -S 512 -C ${WORKDIR}/boot.img $BOOT_BLOCKS 
```
but I'd like someone else to verify

**Additional details (revisions used, host distro, etc.):**

**Comment by agherzan** [comment]
@rosterloh that is correct. Would you feel like pushing a PR to address this?

**Comment by rosterloh** [comment]
@agherzan should be good now

**Comment by agherzan** [comment]
Nice. Waiting for builds and will merge.
