### ISSUE TITLE
spurious file in master branch

### ISSUE THREAD

**Issue by LocutusOfBorg** [agherzan/meta-raspberrypi#4]
Hi, please remove the "patch" file in the root of the master branch

(I guess something bad happened to my patch forwarding)

**Comment by agherzan** [comment]
Can you add a pull request for this please? Thanks.

**Comment by LocutusOfBorg** [comment]
closing, added #5 instead :)

**Comment by LocutusOfBorg** [comment]
(I thought you were asking for mails instead of PRs)

**Comment by agherzan** [comment]
Well we do emails officially. But I can manage PRs too.

**Comment by LocutusOfBorg** [comment]
wonderful :)
