### ISSUE TITLE
The RAM size is 128M on raspi2.

### ISSUE THREAD

**Issue by latiaoxia** [agherzan/meta-raspberrypi#40]
I have built an image using this layer, the ram size should be 1G on raspi, but the `free`command output is 128M.

**Comment by agherzan** [comment]
Hello,

What exactly RaspberryPi version are you using? Do you have any GPU memory configuration in your config.txt?

Regards,
Andrei

**Comment by latiaoxia** [comment]
Thanks! I've solved this problem, I use the old gpu bootloader.
