### ISSUE TITLE
FFMpeg override

### ISSUE THREAD

**Issue by TomMettam** [agherzan/meta-raspberrypi#402]
On Raspberry Pi, FFMPEG can provide hardware acceleration through the use of --enable-omx and --enable-omx-rpi compile-time switches.

It would make sense for meta-raspberrypi to override the recipe in oe-core to add these compile-time switches to FFMPEG.

**Comment by kraj** [comment]
It’s better to write bbappends to express these
In this layer itself and apply the package config using ‘rpi’ overrides

**Comment by agherzan** [comment]
I subscribe to what @kraj said. I'm also OK with adding them in the BSP layer as long as you feel like pushing and testing a PR.

**Comment by TomMettam** [comment]
I have a working bbappend for this, however it breaks because for some reason the openmax libraries are in /usr/lib/ rather than the expected /opt/vc/lib/ - any clue why this might be?

**Comment by kraj** [comment]
thats normal for this libs to be in /usr/lib so make it look into standard paths.

**Comment by TomMettam** [comment]
But it's not normal for raspberry pi - userland libraries are expected to be under /opt/vc/lib, and I believe it's hardcoded in ffmpeg!

**Comment by TomMettam** [comment]
Yep... https://gyazo.com/74b7141b4d088c6ee0b4c136d3f1fc27

**Comment by kraj** [comment]
Right you need to patch ffmpeg

**Comment by TomMettam** [comment]
But every single other OS which implements the raspberry pi userland puts these libraries in /opt/vc/lib. And actually,  having these libraries in /usr/lib breaks the omx samples too.

**Comment by agherzan** [comment]
@TomMettam Any updates on this?

**Comment by pbrkr** [comment]
@agherzan I recommend we close this due to lack of follow-up.
