### ISSUE TITLE
linux-raspberrypi 4.19.y is not considered stable

### ISSUE THREAD

**Issue by paul-betafive** [agherzan/meta-raspberrypi#410]
Looking upstream today I've seen the following issue reported by @schnitzeltony: https://github.com/raspberrypi/linux/issues/2931

On this issue it's been made clear that the rpi-4.19.y kernel branch is not considered stable and rebasing of this branch will likely continue. The rebasing is causing regular fetch errors for myself and other users.

I recommend we switch the default kernel version back to 4.14 in this layer.

@kraj, @agherzan: Any thoughts on this? It's a shame to move backwards but I don't think we can leave the default kernel on a branch that's being regularly rebased.

**Comment by kraj** [comment]
We should add ```rebaseable=1``` to SRC_URI until upstream gets their act together and starts respecting default public branches.

**Comment by agherzan** [comment]
What is rebaseable doing?

**Comment by kraj** [comment]
it keeps the old SHA along even on refresh it will find the old SHA

**Comment by paul-betafive** [comment]
Setting `rebaseable=1` doesn't fix things for us as we're not maintaining a downloads mirror.
