### ISSUE TITLE
[Question] ENABLE_UART="1" in local.conf will not enable cmdline console arg

### ISSUE THREAD

**Issue by manszigher** [agherzan/meta-raspberrypi#415]
Hi,

I am trying to get the serial console to work on the GPIO pins on raspberrypi3 B+ without any success. I am sure I am doing something wrong and I have gone through all the issues here but without any luck. One of the things that I don't understand is that according to the documentation I should add ENABLE_UART="1" to the local.conf which I have verified that enable_uart=1 exists in config.txt. In [linux-raspberrypi.inc](https://github.com/agherzan/meta-raspberrypi/blob/7059c374512f1c1c0df9ecab0703d11438bdf78b/recipes-kernel/linux/linux-raspberrypi.inc#L24) we can see the following code

<pre>
SERIAL = "${@oe.utils.conditional("ENABLE_UART", "1", "console=serial0,115200", "", d)}"
CMDLINE ?= "dwc_otg.lpm_enable=0 ${SERIAL} root=/dev/mmcblk0p2 rootfstype=ext4 rootwait"
</pre>

So why is [oe.utils.conditional](https://github.com/openembedded/openembedded-core/blob/ff578f4451a0a199202e576b647840910b4d3f59/meta/lib/oe/utils.py#L22) not finding ENABLE_UART? Am I doing something wrong?

**Comment by manszigher** [comment]
So i dumped the env for linux-raspberrypi and noticed that ENABLE_UART actually was enabled after modifying the SERIAL to always set "console=serial0,115200" so I think the issue was that I did not do a clean of linux-raspberrypi after adding ENABLE_UART in local.conf.

**Comment by manszigher** [comment]
So this is what I get when running bitbake -e linux-raspberrypi

<pre>
CMDLINE="dwc_otg.lpm_enable=0 console=serial0,115200 root=/dev/mmcblk0p2 rootfstype=ext4 rootwait    "
</pre>

But when booting up the console is missing in the cmdline.txt

**Comment by manszigher** [comment]
The file under ./tmp/deploy/images/raspberrypi3/bcm2835-bootfiles/cmdline.txt also includes the console arg.

**Comment by agherzan** [comment]
Can you mount the final image and check the cmdline.txt? Have you regenerated the image and burn the right one?

**Comment by manszigher** [comment]
Well let me just say that I have tried to verify it accordingly but since it was still not working I must be messing something up. I will post a comment when I figures this out. Thanks anyway.

**Comment by agherzan** [comment]
@manszigher Any news on this?

**Comment by manszigher** [comment]
Sorry yes I just had to make sure that after enable it that everything was built as expected I think there was a cache interfering resulting it after making sure everything was built as expected I got it up and working.
