### ISSUE TITLE
No recipe for bpftool.bbappend in meta-raspberry pi

### ISSUE THREAD

**Issue by NirajTummala** [agherzan/meta-raspberrypi#416]
![Workspace 1_003](https://user-images.githubusercontent.com/6519885/57183376-d24afb80-6e71-11e9-8310-442bb93112a5.png)

using poky thud-20.0.2 

meta-raspberrypi depends on meta-oe,meta-openembedded
MACHINE: raspberrypi3

error:
No recipe for packagegroup-meta-oe.bbappend
No recipe for bpftool.bbappend

when using bitbake core-image-minimal

**Comment by kraj** [comment]
are you using `thud` branch for meta-raspperrypi repo as well ? if not please do so.

**Comment by agherzan** [comment]
I'll close this issue for now. Don't hesitate to post a comment if the branch selection was not the issue.
