### ISSUE TITLE
ERROR: Function failed: do_image_rpi_sdimg

### ISSUE THREAD

**Issue by karansinghminhas** [agherzan/meta-raspberrypi#42]
![screenshot from 2017-01-04 21 18 07](https://cloud.githubusercontent.com/assets/24550701/21691519/e937f318-d39e-11e6-9f07-bb486c62dea8.png)

**Comment by agherzan** [comment]
Sadly I am not maintaining the krogoth branch anymore. Can you test the morty one?

**Comment by agherzan** [comment]
Tested morty and can't reproduce.
