### ISSUE TITLE
OMXPlayer build fails

### ISSUE THREAD

**Issue by TomMettam** [agherzan/meta-raspberrypi#428]
OMXPlayer build fails when targeting Raspberry Pi 3b+ from meta-raspberrypi master

`/build/tmp/work/cortexa7t2hf-neon-vfpv4-yoe-linux-gnueabi/omxplayer/git-r4/recipe-sysroot/usr/include/bits/byteswap.h:34:29: sorry, unimplemented: Thumb-1 hard-float VFP ABI`

**Comment by c0ffee** [comment]
```
diff --git recipes-multimedia/omxplayer/omxplayer_git.bb recipes-multimedia/omxplayer/omxplayer_git.bb
index aad2fed..1d539fc 100644
--- recipes-multimedia/omxplayer/omxplayer_git.bb
+++ recipes-multimedia/omxplayer/omxplayer_git.bb
@@ -80,6 +80,8 @@ export INCLUDES = "${@bb.utils.contains("MACHINE_FEATURES", "vc4graphics", " -D_
                   "
 export DIST = "${D}"
 
+ARM_INSTRUCTION_SET = "arm"
+
 do_compile() {
     # Needed for compiler test in ffmpeg's configure
     mkdir -p tmp
```


fixed it for me

**Comment by c0ffee** [comment]
i didnt create a pull request because i was not sure if it is a good idea to disable thumb for all people for this package ;) but sadly so far i didnt find a better solution

**Comment by TomMettam** [comment]
Will "arm" work for all pi variants?

**Comment by c0ffee** [comment]
all pi variants are arm yes and support the basic arm instruction set. thumb instruction set reduces the sizes and could increase the performance, I'm using omxplayer with it and couldnt discover any problems with it yet.

yocto is using by default here thumb2 instruction set for this machine, I have no clue why it complains about thumb1 in this case, maybe we can get it to work with thumb2 somehow...

**Comment by kraj** [comment]
> OMXPlayer build fails when targeting Raspberry Pi 3b+ from meta-raspberrypi master
> 
> `/build/tmp/work/cortexa7t2hf-neon-vfpv4-yoe-linux-gnueabi/omxplayer/git-r4/recipe-sysroot/usr/include/bits/byteswap.h:34:29: sorry, unimplemented: Thumb-1 hard-float VFP ABI`

the fix to disable thumb ISA may be a broad-brush here, Please check if omxplayer build it modifying -mcpu/march options to use something that is < armv6 which would mean -mthumb would point to thumb1 and that could result in such errors. What is the full compiler cmdline for this particular build failures?

**Comment by agherzan** [comment]
I agree. We should find the root cause of this.

**Comment by c0ffee** [comment]
can we pls cherry-pick this in warrior?

**Comment by agherzan** [comment]
@c0ffee Could you please send a PR with this commit targeting the warrior branch?
