### ISSUE TITLE
Raspberrypi4-64, usb no power

### ISSUE THREAD

**Issue by iohe** [agherzan/meta-raspberrypi#446]
**Description**
Keyboard is not powered, kernel reports errors 
**Steps to reproduce the issue:**
1. build meta-raspberry @ 6531d1d (HEAD -> ag/rpi4-uboot-update, origin/ag/rpi4-uboot-update) u-boot: Update patches for RPi4
2.
3.

**Describe the results you received:**
Errors encountered in kernel :
[    2.530074] usb 1-1: new high-speed USB device number 4 using xhci_hcd
[    2.550489] usb 1-1: device descriptor read/8, error -61
[    2.678539] usb 1-1: device descriptor read/8, error -61
[    2.914059] usb 1-1: new high-speed USB device number 5 using xhci_hcd
[    2.934469] usb 1-1: device descriptor read/8, error -61
[    3.062515] usb 1-1: device descriptor read/8, error -61
[    3.170269] usb usb1-port1: unable to enumerate USB device

**Describe the results you expected:**
Usb keyboard to work.

**Additional information you deem important (e.g. issue happens only occasionally):**
Always happens.
It did not happen with meta-raspberry@ 1e329d36c99718194d20e6216f1c13199e124bb7

**Additional details (revisions used, host distro, etc.):**
layers used:
-poky@97c5921666
-meta-openembedded@27d1d3dfa
- meta-raspberry @ 6531d1d
local.conf has:
MACHINE ?= "raspberrypi4-64"
DISTRO_FEATURES_append = " opengl"
DISTRO_FEATURES_append = " polkit"
u-boot is not enabled or used.
-Image : core-image-x11
Other packages in image: xfce4

[dmesg.txt](https://github.com/agherzan/meta-raspberrypi/files/3411976/dmesg.txt)

**Comment by agherzan** [comment]
What power supply are you using? Are you testing it with an official charger?

**Comment by iohe** [comment]
Official power source for rpi4.
usb is powered and no issue present if i build a couple of days old commit, as specified.  I suspect something wrong on firmware side.

**Comment by agherzan** [comment]
That is worrying. Would you be able to give it a try with an older firmware and test that theory?

**Comment by iohe** [comment]
[dmesg.txt](https://github.com/agherzan/meta-raspberrypi/files/3412283/dmesg.txt)
This works ok

**Comment by iohe** [comment]
Using https://github.com/agherzan/meta-raspberrypi/commit/8d5fc54f41dab42d765644ea953bf451ced78f74 i can attach my Razer Blackwidw Lite keyboard and type. 
Using 69da331154852f5d62d6cf7a69c4ddb34f5564d0 it does not go more than colored screen at boot.
Using 0d641c8fa918b1c5ecce2cb9918c47bb3c4e1510, and RPI_USE_U_BOOT = "1" it does not appear again.
Using a USBtester that shows Voltage and amps, it never shows amps above 0.
Is anyone else able to reproduce issue ?

**Comment by agherzan** [comment]
The relevant kernel issue is: https://github.com/raspberrypi/linux/issues/3093

**Comment by agherzan** [comment]
@iohe if you are willing to compromise on 1Gb of ram, here is a PR ^

**Comment by iohe** [comment]
ok for now, will revisit later for full 4g. 
Thank you very much!
