### ISSUE TITLE
Fix cm3 armstub

### ISSUE THREAD

**Issue by agherzan** [agherzan/meta-raspberrypi#452]
https://github.com/agherzan/meta-raspberrypi/blob/6c175288cc81554b765c99453dc96fd4570205dd/conf/machine/raspberrypi-cm3.conf#L14

**Comment by pbrkr** [comment]
@agherzan Is this an issue we can close?

**Comment by agherzan** [comment]
I think we can close it for now. We'll revise if we have users on that side but I would be surprised if anyone uses armstubs nowadays.
