### ISSUE TITLE
raspberry pi4-64bit can not display logo at boot up

### ISSUE THREAD

**Issue by gitgonewithwind** [agherzan/meta-raspberrypi#484]
raspberry pi4-64bit can not display logo at boot up

pi4-32bit can show a few  small raspberries and rainbow colour at boot up  and after I change file drivers/video/logo/logo_linux_clut224.ppm  it can show my company logo.

but pi4-64bit no samll raspberries display ,only rainbow colour , and no my company logo after  drivers/video/logo/logo_linux_clut224.ppm replaced by my logo.

**Comment by pbrkr** [comment]
@gitgonewithwind is this still an issue? If so, could you check the kernel config for raspberrypi4-64 to see if CONFIG_LOGO is enabled?

**Comment by gitgonewithwind** [comment]
> @gitgonewithwind is this still an issue? If so, could you check the kernel config for raspberrypi4-64 to see if CONFIG_LOGO is enabled?

sorry, now I do not debug it, I am working on a different project. some  days later I will debug it. thank you.

**Comment by janeczkos** [comment]
I have the same thing with raspberypi3-64. I have CONFIG_LOG enabled. 
It was working with raspberrypi 3 architecture ( 32 bits closed source gpu driver ).

**Comment by agherzan** [comment]
It works on dunfell and master as tested lately by me. Closing.
