### ISSUE TITLE
Package management using apt

### ISSUE THREAD

**Issue by MickHackEthic** [agherzan/meta-raspberrypi#50]
Hi,
I don't know if this is an issue, I have compiled a console-image recipe for raspberry pi3 successfully.
I have setted up the wifi to have internet connection and now I would like to set apt properly to use Raspbian repository for upgrade and mainteinance.
I have added the official repository URL into sources.list but when I have tried to install something or just upgrade with apt-get upgrade I have a "Broken pipe" error from dpkg.
I think it is not so easy like just I have done.
Is it really possible to use apt-get for maintenance of a Yocto based distro?

**Comment by agherzan** [comment]
Sorry for the late reply. Yocto doesn't support apt package manager.
