### ISSUE TITLE
RPI 3b+ with official touchscreen: problems after upgrade from thud to warrior

### ISSUE THREAD

**Issue by BlackZork** [agherzan/meta-raspberrypi#500]
7" PI touchscreen shows boot phase, but as soon as psplash is shown screen freezes.

I tried so far:
- default kernel on warrior branch (core-image-base)
- 4.14.112 kernel on warrior branch (core-image-base)
- [meta-rpi layer](https://github.com/jumpnow/meta-rpi) - it uses kernel 4.19.73

Raspbian (Release 2019-09-26, 4.19.75 kernel) boots and works ok.

Anyone has a working configuration for warrior branch?

**Comment by agherzan** [comment]
@BlackZork Do you have a stable power supply? Also, can you attach a serial console to see if the entire board is frozen?

**Comment by BlackZork** [comment]
It is a problem with vc4 video driver. When I blacklisted it in /etc/modprobe.d touchscreen works OK.

I tried to use VC4DTBO = "vc4-fkms-v3d" in layer.conf, but effect is the same.

I ended with MACHINE_FEATURES_remove = "vc4graphics", which I assume is a return to old working configuration. Will see when I add QT5 to my new layer.

BTW, hdmi output works OK with vc4 kernel module loaded.

**Comment by agherzan** [comment]
Interesting. I sadly don't have a display at my disposal. @floion @zubair do you happen to know anything about this issue? @BlackZork this is on DSI, right?

**Comment by BlackZork** [comment]
Yes, this is Official Raspberry PI 7" Touchscreen bought about a year ago.

**Comment by BlackZork** [comment]
I upgraded to Dunfell and vc4graphics works ok with PI 7" Touchscreen.
Not sure if I should close this issue.

**Comment by agherzan** [comment]
I'll close it as warrior is not an actively supported branch. If anyone wants to investigate it as part of that release, I'll be accepting patches.
