### ISSUE TITLE
No audio on Raspberry Pi 4

### ISSUE THREAD

**Issue by mozcelikors** [agherzan/meta-raspberrypi#516]
I used to be able to get audio on Raspberry Pi 4, but for some reason now I cant seem to get it. I use master branches for raspberrypi4-64 machine. I have an HDMI touchscreen (https://www.waveshare.com/10.1inch-hdmi-lcd-with-case.htm) connected to my Pi.

```
root@raspberrypi4-64:~# aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 6/7
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 IEC958/HDMI [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: ALSA [bcm2835 ALSA], device 2: bcm2835 IEC958/HDMI1 [bcm2835 IEC958/HDMI1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
I have the following in my config.txt:
`dtparam=audio=on`

And audio card created:
```
root@raspberrypi4-64:~# dmesg | grep snd
[    1.922779] snd_bcm2835: module is from the staging directory, the quality is unknown, you have been warned.
root@raspberrypi4-64:~# dmesg | grep audio
[    1.942517] bcm2835_audio soc:audio: card created with 8 channels
```

What I've tried: 
```
speaker-test -Dpulse
speaker-test -Dhw:0
speaker-test -Dhw:0,0
speaker-test -Dhw:0,1
pactl set-default-sink alsa_output.0.analog-mono && speaker-test -Dpulse
```
I've tested the speaker with different board, and it's working.
On Pi, I have no error messages that can help me, simply no output.

If I could get some help, I'd appreciate it. Thanks

**Comment by floion** [comment]
Have you tried running `amixer cset numid=3 2` and then checking audio?

**Comment by agherzan** [comment]
See also: https://www.raspberrypi.org/documentation/configuration/audio-config.md

**Comment by mozcelikors** [comment]
@floion I've tried "amixer cset numid=3 1" since I want the analog audio to work instead of HDMI.
@agherzan Started to happend without rebuilding. Alsa volumes are not muted, I've checked with alsamixer.

I am using following:

```
meta                 
meta-poky            
meta-yocto-bsp       = "HEAD:d7441ddb0c49eafdb620dc45fb7e9a2a92790767"
meta-oe              
meta-multimedia      
meta-networking      
meta-python          
meta-gnome           
meta-xfce            = "master:3061ead8cf38c47ff81d7622cbcf2b8602012212"
meta-qt5             = "master:12ea469918bcb73605b9c1e5080351f1189c0f17"
meta-qt5-extra       = "master:97fa7b592a8faa08d51f64275455e2cbe837a377"
meta-raspberrypi     = "master:866ccc829f728f722f623571b24305d2bc9d8b17"
```

**Comment by xlla** [comment]
same issue here

**Comment by mozcelikors** [comment]
@xlla I still have the same issue, and have been using USB sound card for that reason.

**Comment by koolkhel** [comment]
same issue :-(
```
meta-poky            = "HEAD:3d0865c905d28912f3d355dc4d2b04f42f579616"
meta-oe
meta-multimedia
meta-networking
meta-perl
meta-python          = "zeus:9e60d30669a2ad0598e9abf0cd15ee06b523986b"
meta-qt5             = "zeus:852e279a45da2b68719fecdaad3573b2ada9558c"
meta-raspberrypi     = "zeus:0e05098853eea77032bff9cf81955679edd2f35d"
meta-security        = "zeus:27ddb455543b670097e252ba0d0ad5b7e4101748"
```

Cannot get the embedded headphone jack to be detected with DISTRO_FEATURES = " alsa " and alsa-utils installed:
```
# aplay -l
aplay: device_list:272: no soundcards found...
```

I have dtparam=audio=on in config.txt, but snd_bcm2835 is not loaded by default (and I'm not sure if that's the one to use on pi4)

**Comment by shawaj** [comment]
@mozcelikors is the issue with sound just from HDMI? Or from the 3.5mm jack also?

**Comment by adrianalin** [comment]
Adding 
```hdmi_force_hotplug=1```
to config.txt should do it.
