### ISSUE TITLE
Waveshare 3.5 inches LCD

### ISSUE THREAD

**Issue by metamorphling** [agherzan/meta-raspberrypi#53]
Did anybody manage to make this display work with raspberry pi3?
In kernel config display drivers are being built as modules, but still no luck. LCD shows just white screen the moment I put power on. Tried to do some "echo 0 > /dev/fb0" and "tail -f /dev/input/touchscreen0", no reactions on touch too.

**Comment by agherzan** [comment]
From this documentation it seems that it needs OOT drivers: http://www.waveshare.com/wiki/3.5inch_RPi_LCD_(A)#Driver . I don't think anyone worked in adding support for it.

**Comment by agherzan** [comment]
Checked the archives there - probably you only need those overlays.

**Comment by agherzan** [comment]
@metamorphling Were you able to make it work?

**Comment by agherzan** [comment]
Hopefully you managed to make it work. It would be great if you give us some feedback. I'll close the ticket for now. Do comment if there is anything we can help with.
