### ISSUE TITLE
raspberrypi rpi-test-image compile error

### ISSUE THREAD

**Issue by fuyongjie** [agherzan/meta-raspberrypi#55]
Hi:
How to solve this compile problem?
Log as follows：

fuyongjie@Lenovo:~/work/raspberrypi/yocto$ source poky/oe-init-build-env rpi-build

### Shell environment set up for builds. ###

You can now run 'bitbake <target>'

Common targets are:
    core-image-minimal
    core-image-sato
    meta-toolchain
    meta-ide-support

You can also run generated qemu images with a command like 'runqemu qemux86'
fuyongjie@Lenovo:~/work/raspberrypi/yocto/rpi-build$ bitbake rpi-test-image
Loading cache: 100% |################################################| Time: 0:00:01
Loaded 2687 entries from dependency cache.
Parsing recipes: 100% |##############################################| Time: 0:00:05
Parsing of 1944 .bb files complete (1943 cached, 1 parsed). 2688 targets, 176 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION        = "1.33.3"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "universal"
TARGET_SYS        = "arm-poky-linux-gnueabi"
MACHINE           = "raspberrypi"
DISTRO            = "poky"
DISTRO_VERSION    = "2.2+snapshot-20170423"
TUNE_FEATURES     = "arm armv6 vfp arm1176jzfs callconvention-hard"
TARGET_FPU        = "hard"
meta              
meta-poky         
meta-yocto-bsp    = "master:633ad6c9f436f5d2b6ee1a005b697661a054a394"
meta-raspberrypi  = "master:4b0bc450e08e6836744c97d21e72600f8320fc05"
meta-oe           
meta-multimedia   
meta-networking   
meta-python       = "master:444e1fb198076f34a0fa66e83f3eec76efba2e6c"

Initialising tasks: 100% |###########################################| Time: 0:00:07
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
ERROR: x264-r2731+gitAUTOINC+2b741f81e5-r0 do_compile: oe_runmake failed
ERROR: x264-r2731+gitAUTOINC+2b741f81e5-r0 do_compile: Function failed: do_compile (log file is located at /home/fuyongjie/work/raspberrypi/yocto/rpi-build/tmp/work/arm1176jzfshf-vfp-poky-linux-gnueabi/x264/r2731+gitAUTOINC+2b741f81e5-r0/temp/log.do_compile.2800)
ERROR: Logfile of failure stored in: /home/fuyongjie/work/raspberrypi/yocto/rpi-build/tmp/work/arm1176jzfshf-vfp-poky-linux-gnueabi/x264/r2731+gitAUTOINC+2b741f81e5-r0/temp/log.do_compile.2800
Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: make -j 4
| ERROR: oe_runmake failed
| arm-poky-linux-gnueabi-gcc  -march=armv6 -mfpu=vfp  -mfloat-abi=hard -mtune=arm1176jzf-s -mfpu=vfp --sysroot=/home/fuyongjie/work/raspberrypi/yocto/rpi-build/tmp/work/arm1176jzfshf-vfp-poky-linux-gnueabi/x264/r2731+gitAUTOINC+2b741f81e5-r0/recipe-sysroot -I. -I. -c -DSTACK_ALIGNMENT=4 -DPIC -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -o common/arm/quant-a.o common/arm/quant-a.S
| common/arm/quant-a.S: Assembler messages:
| common/arm/quant-a.S:362: Error: selected processor does not support `rbit r1,r1' in ARM mode
| common/arm/quant-a.S:363: Error: selected processor does not support `rbit r1,r1' in ARM mode
| Makefile:217: recipe for target 'common/arm/quant-a.o' failed
| make: *** [common/arm/quant-a.o] Error 1
| ERROR: Function failed: do_compile (log file is located at /home/fuyongjie/work/raspberrypi/yocto/rpi-build/tmp/work/arm1176jzfshf-vfp-poky-linux-gnueabi/x264/r2731+gitAUTOINC+2b741f81e5-r0/temp/log.do_compile.2800)
ERROR: Task (/home/fuyongjie/work/raspberrypi/yocto/poky/meta/recipes-multimedia/x264/x264_git.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 2296 tasks of which 2290 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/fuyongjie/work/raspberrypi/yocto/poky/meta/recipes-multimedia/x264/x264_git.bb:do_compile
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.

**Comment by agherzan** [comment]
This was fixed in master. Ref.: https://github.com/agherzan/meta-raspberrypi/commit/fe909cd5b9cb23dabc4f8d3600f5ec6b3e8443c1
