### ISSUE TITLE
ReadTheDocs GitHub integration needs re-activating

### ISSUE THREAD

**Issue by pbrkr** [agherzan/meta-raspberrypi#561]
Looks like this broke around 11 months ago and I can't fix it myself without admin access to this repository.

@agherzan, I think I added you as an admin on https://readthedocs.org/projects/meta-raspberrypi/. Could you go the the admin tab on there, select Integrations and add a "GitHub incoming webhook" integration? That should then automatically rebuild the docs whenever they're updated in this repository.

**Comment by agherzan** [comment]
Should be fixed now. Thanks @pbrkr for raising this.
