### ISSUE TITLE
uImage-bcm2711-rpi-4-b.dtb No such file or directory

### ISSUE THREAD

**Issue by sirus20x6** [agherzan/meta-raspberrypi#580]
has the naming scheme changed with the pi 4? I have 
bcm2711-rpi-4-b-1-4.19.93+git0+3fdcc814c5-r0-raspberrypi4-20200213161019.dtb
bcm2711-rpi-4-b.dtb
bcm2711-rpi-4-b-raspberrypi4.dtb
but no uImage-bcm2711-rpi-4-b.dtb

`Initialising tasks: 100% |########################################################################################################################################################################################################################| Time: 0:00:08
Sstate summary: Wanted 23 Found 8 Missed 15 Current 2796 (34% match, 99% complete)
NOTE: Executing Tasks
NOTE: Setscene tasks completed
ERROR: core-image-myImage-1.0-r0 do_image_wic: Execution of '/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/tmp-glibc/work/raspberrypi4-oe-linux-gnueabi/core-image-myImage/1.0-r0/temp/run.do_image_wic.40339' failed with exit code 1:
INFO: Creating image(s)...

WARNING: bootloader config not specified, using defaults

ERROR: _exec_cmd: install -m 0644 -D /mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/tmp-glibc/deploy/images/raspberrypi4/uImage-bcm2711-rpi-4-b.dtb /mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/tmp-glibc/work/raspberrypi4-oe-linux-gnueabi/core-image-myImage/1.0-r0/deploy-core-image-myImage-image-complete/core-image-myImage-raspberrypi4-20200213161019/tmp.wic.35m3q06x/boot.1/bcm2711-rpi-4-b.dtb returned '1' instead of 0
output: install: cannot stat '/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/tmp-glibc/deploy/images/raspberrypi4/uImage-bcm2711-rpi-4-b.dtb': No such file or directory

WARNING: exit code 1 from a shell command.

ERROR: Logfile of failure stored in: /mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/tmp-glibc/work/raspberrypi4-oe-linux-gnueabi/core-image-myImage/1.0-r0/temp/log.do_image_wic.40339
Log data follows:
| DEBUG: Executing python function set_image_size
| DEBUG: 1943536.000000 = 1943536 * 1.000000
| DEBUG: 2045936.000000 = max(1943536.000000, 65536)[1943536.000000] + 102400
| DEBUG: 2045936.000000 = int(2045936.000000)
| DEBUG: 2048000 = aligned(2045936)
| DEBUG: returning 2048000
| DEBUG: Python function set_image_size finished
| DEBUG: Executing python function extend_recipe_sysroot
| NOTE: Direct dependencies are ['virtual:native:/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-devtools/swig/swig_3.0.12.bb:do_populate_sysroot', '/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-devtools/mklibs/mklibs-native_0.1.44.bb:do_populate_sysroot', 'virtual:native:/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-devtools/bison/bison_3.4.1.bb:do_populate_sysroot', 'virtual:native:/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-connectivity/openssl/openssl_1.1.1d.bb:do_populate_sysroot', 'virtual:native:/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-devtools/syslinux/syslinux_6.04-pre2.bb:do_populate_sysroot', '/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-devtools/gcc/gcc-runtime_9.2.bb:do_populate_sysroot', 'virtual:native:/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-devtools/squashfs-tools/squashfs-tools_git.bb:do_populate_sysroot', 'virtual:native:/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-devtools/fdisk/gptfdisk_1.0.4.bb:do_populate_sysroot', 'virtual:native:/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-bsp/u-boot/u-boot-tools_2019.07.bb:do_populate_sysroot', 'virtual:native:/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-devtools/dnf/dnf_4.2.2.bb:do_populate_sysroot', 'virtual:native:/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-devtools/prelink/prelink_git.bb:do_populate_sysroot', 'virtual:native:/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-devtools/opkg/opkg_0.4.1.bb:do_populate_sysroot', 'virtual:native:/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-devtools/flex/flex_2.6.0.bb:do_populate_sysroot', '/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-devtools/quilt/quilt-native_0.66.bb:do_populate_sysroot', 'virtual:native:/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-support/lzop/lzop_1.04.bb:do_populate_sysroot', 'virtual:native:/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-support/bmap-tools/bmap-tools_3.5.bb:do_populate_sysroot', '/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-devtools/binutils/binutils-cross_2.32.bb:do_populate_sysroot', 'virtual:native:/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-devtools/icecc-create-env/icecc-create-env_0.1.bb:do_populate_sysroot', 'virtual:native:/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-devtools/btrfs-tools/btrfs-tools_5.2.2.bb:do_populate_sysroot', 'virtual:native:/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-core/update-rc.d/update-rc.d_0.8.bb:do_populate_sysroot', 'virtual:native:/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-devtools/opkg-utils/opkg-utils_0.4.1.bb:do_populate_sysroot', '/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-devtools/python/python-native_2.7.17.bb:do_populate_sysroot', 'virtual:native:/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-extended/bc/bc_1.07.1.bb:do_populate_sysroot', 'virtual:native:/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-devtools/dosfstools/dosfstools_4.1.bb:do_populate_sysroot', '/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-core/glibc/cross-localedef-native_2.30.bb:do_populate_sysroot', 'virtual:native:/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-devtools/mtools/mtools_4.0.23.bb:do_populate_sysroot', '/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta-raspberrypi/recipes-bsp/bootfiles/rpi-config_git.bb:do_populate_sysroot', '/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-kernel/kmod/depmodwrapper-cross_1.0.bb:do_populate_sysroot', 'virtual:native:/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-devtools/rpm/rpm_4.14.2.1.bb:do_populate_sysroot', '/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta-raspberrypi/recipes-bsp/rpi-u-boot-scr/rpi-u-boot-scr.bb:do_populate_sysroot', '/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta-raspberrypi/recipes-kernel/linux/linux-raspberrypi_4.19.bb:do_populate_sysroot', '/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-core/glibc/glibc_2.30.bb:do_populate_sysroot', '/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-kernel/kern-tools/kern-tools-native_git.bb:do_populate_sysroot', 'virtual:native:/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta-myImage-system/recipes-kernel/dtc/dtc_1.4.5.bb:do_populate_sysroot', '/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-devtools/gcc/gcc-cross_9.2.bb:do_populate_sysroot', '/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-devtools/qemu/qemuwrapper-cross_1.0.bb:do_populate_sysroot', 'virtual:native:/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-extended/pigz/pigz_2.4.bb:do_populate_sysroot', '/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta-myImage-system/recipes-core/myImage-additional/myImage-additional_1.0.0.bb:do_populate_sysroot', '/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-devtools/cdrtools/cdrtools-native_3.01.bb:do_populate_sysroot', '/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-core/glibc/ldconfig-native_2.12.1.bb:do_populate_sysroot', 'virtual:native:/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-devtools/e2fsprogs/e2fsprogs_1.45.3.bb:do_populate_sysroot', 'virtual:native:/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-devtools/createrepo-c/createrepo-c_0.15.0.bb:do_populate_sysroot', '/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-kernel/kmod/kmod-native_git.bb:do_populate_sysroot', 'virtual:native:/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-extended/parted/parted_3.2.bb:do_populate_sysroot', 'virtual:native:/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-devtools/pseudo/pseudo_git.bb:do_populate_sysroot', 'virtual:native:/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-extended/xz/xz_5.2.4.bb:do_populate_sysroot', 'virtual:native:/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta/recipes-devtools/makedevs/makedevs_1.0.1.bb:do_populate_sysroot']
| NOTE: rpi-u-boot-scr exists in sysroot, but is stale (rpi-u-boot-scr.aca3952b561d5e2d1bae4f736f294acc68c625537fe1314fac0d8bd548f31f95 vs. rpi-u-boot-scr.aede7b69bd57650a1d376b7440c89317d76990ca660093b7ae5307a03f79a42e), removing.
| DEBUG: Removing manifest: /mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/tmp-glibc/work/raspberrypi4-oe-linux-gnueabi/core-image-myImage/1.0-r0/recipe-sysroot/sysroot-providers/rpi-u-boot-scr
| DEBUG: Removing manifest: /mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/tmp-glibc/work/raspberrypi4-oe-linux-gnueabi/core-image-myImage/1.0-r0/recipe-sysroot/sysroot-providers/
| NOTE: linux-raspberrypi exists in sysroot, but is stale (linux-raspberrypi.8b95e2b46a09f337480e289932df73a79381d0b88e126e0157504ef98f92ee92 vs. linux-raspberrypi.baf142a8d01923814e73f25de3f558d6ed0e99a6bb419e572275a5b7a3067685), removing.
| DEBUG: Removing manifest: /mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/tmp-glibc/work/raspberrypi4-oe-linux-gnueabi/core-image-myImage/1.0-r0/recipe-sysroot/sysroot-providers/linux-raspberrypi
| DEBUG: Removing manifest: /mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/tmp-glibc/work/raspberrypi4-oe-linux-gnueabi/core-image-myImage/1.0-r0/recipe-sysroot/sysroot-providers/virtual_kernel
| DEBUG: Removing manifest: /mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/tmp-glibc/work/raspberrypi4-oe-linux-gnueabi/core-image-myImage/1.0-r0/recipe-sysroot/sysroot-providers/
| NOTE: Installed into sysroot: ['rpi-u-boot-scr', 'linux-raspberrypi']
| NOTE: Skipping as already exists in sysroot: ['swig-native', 'mklibs-native', 'bison-native', 'openssl-native', 'syslinux-native', 'gcc-runtime', 'squashfs-tools-native', 'gptfdisk-native', 'u-boot-tools-native', 'dnf-native', 'prelink-native', 'opkg-native', 'flex-native', 'quilt-native', 'lzop-native', 'bmap-tools-native', 'binutils-cross-arm', 'icecc-create-env-native', 'btrfs-tools-native', 'update-rc.d-native', 'opkg-utils-native', 'python-native', 'bc-native', 'dosfstools-native', 'cross-localedef-native', 'mtools-native', 'rpi-config', 'depmodwrapper-cross', 'rpm-native', 'glibc', 'kern-tools-native', 'dtc-native', 'gcc-cross-arm', 'qemuwrapper-cross', 'pigz-native', 'myImage-additional', 'cdrtools-native', 'ldconfig-native', 'e2fsprogs-native', 'createrepo-c-native', 'kmod-native', 'parted-native', 'pseudo-native', 'xz-native', 'makedevs-native', 'autoconf-native', 'automake-native', 'pkgconfig-native', 'gnu-config-native', 'python3-native', 'libpcre-native', 'libtool-native', 'systemd-systemctl-native', 'qemu-native', 'gettext-minimal-native', 'texinfo-dummy-native', 'util-linux-native', 'nasm-native', 'linux-libc-headers', 'libgcc', 'shadow-native', 'nss-native', 'elfutils-native', 'binutils-native', 'libsolv-native', 'libarchive-native', 'lzo-native', 'debianutils-native', 'mkfontdir-native', 'mkfontscale-native', 'bzip2-native', 'file-native', 'dbus-native', 'popt-native', 'db-native', 'perl-native', 'sqlite3-native', 'libxml2-native', 'libmodulemd-native', 'zlib-native', 'expat-native', 'glib-2.0-native', 'cmake-native', 'ninja-native', 'curl-native', 'readline-native', 'ncurses-native', 'lz4-native', 'attr-native', 'gdk-pixbuf-native', 'librepo-native', 'libcomps-native', 'python3-iniparse-native', 'libdnf-native', 'm4-native', 'python3-setuptools-native', 'python3-six-native', 'acl-native', 'gdbm-native', 'gtk+3-native', 'gmp-native', 'libmpc-native', 'mpfr-native', 'shadow', 'libusb1', 'v4l-utils', 'qextserialport', 'alsa-lib', 'libogg', 'qtwebkit', 'libx11', 'libxml2', 'shadow-sysroot', 'libxslt', 'qtftp', 'mesa', 'qrencode', 'libxext', 'base-files', 'bash', 'libvorbis', 'qtbase', 'ffmpeg', 'qtscript', 'qtxmlpatterns', 'libxrandr', 'libtheora', 'qtdeclarative', 'e2fsprogs', 'base-passwd', 'qtsvg', 'gtk-doc-native', 'libtirpc-native', 'libffi-native', 'libnsl2-native', 'libsdl2-native', 'libcap-ng-native', 'groff-native', 'nspr-native', 'libx11-native', 'util-macros-native', 'libfontenc-native', 'freetype-native', 'xorgproto-native', 'libyaml-native', 'gobject-introspection-native', 'meson-native', 'gettext-native', 're2c-native', 'libjpeg-turbo-native', 'libpng-native', 'shared-mime-info-native', 'gpgme-native', 'libcheck-native', 'json-c-native', 'unzip-native', 'fontconfig-native', 'libxfixes-native', 'libxrender-native', 'pango-native', 'atk-native', 'libxcursor-native', 'libxcomposite-native', 'libxdamage-native', 'cairo-native', 'at-spi2-atk-native', 'libxrandr-native', 'libxi-native', 'libxext-native', 'libxcrypt', 'opkg-utils', 'attr', 'systemd', 'libjpeg-turbo', 'libxrender', 'libxcomposite', 'icu', 'fontconfig', 'qtlocation', 'qtmultimedia', 'qtwebchannel', 'glib-2.0', 'sqlite3', 'qtsensors', 'libxcb', 'util-macros', 'xtrans', 'xorgproto', 'python3', 'zlib', 'cmake', 'libxfixes', 'libxshmfence', 'libdrm', 'expat', 'libxxf86vm', 'xrandr', 'libxdamage', 'libpng', 'libsdl', 'glibc-locale', 'ncurses', 'tslib', 'libxkbcommon', 'xcb-util-image', 'openssl', 'xcb-util-keysyms', 'libinput', 'dbus', 'xcb-util-wm', 'freetype', 'python', 'xcb-util-renderutil', 'libxv', 'bzip2', 'util-linux', 'xtrans-native', 'libxcb-native', 'font-util-native', 'intltool-native', 'libgpg-error-native', 'libassuan-native', 'gperf-native', 'libxft-native', 'harfbuzz-native', 'fribidi-native', 'pixman-native', 'libsm-native', 'at-spi2-core-native', 'kmod', 'bash-completion', 'xz', 'libcap', 'acl', 'qtquickcontrols', 'qtwebsockets', 'libpcre', 'libffi', 'xcb-proto', 'libxdmcp', 'libpthread-stubs', 'libxau', 'libnsl2', 'libtirpc', 'readline', 'gdbm', 'curl', 'libarchive', 'libpciaccess', 'libglu', 'xkeyboard-config', 'xcb-util', 'libevdev', 'mtdev', 'libsm', 'autoconf-archive', 'db', 'libcap-ng', 'libxdmcp-native', 'libxau-native', 'xcb-proto-native', 'libpthread-stubs-native', 'libxml-parser-perl-native', 'icu-native', 'libice-native', 'libxtst-native', 'libidn2', 'gnutls', 'lzo', 'libice', 'libunistring', 'nettle', 'gmp']
| DEBUG: Python function extend_recipe_sysroot finished
| DEBUG: Executing shell function do_image_wic
| INFO: Creating image(s)...
| 
| WARNING: bootloader config not specified, using defaults
| 
| ERROR: _exec_cmd: install -m 0644 -D /mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/tmp-glibc/deploy/images/raspberrypi4/uImage-bcm2711-rpi-4-b.dtb /mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/tmp-glibc/work/raspberrypi4-oe-linux-gnueabi/core-image-myImage/1.0-r0/deploy-core-image-myImage-image-complete/core-image-myImage-raspberrypi4-20200213161019/tmp.wic.35m3q06x/boot.1/bcm2711-rpi-4-b.dtb returned '1' instead of 0
| output: install: cannot stat '/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/tmp-glibc/deploy/images/raspberrypi4/uImage-bcm2711-rpi-4-b.dtb': No such file or directory
| 
| WARNING: exit code 1 from a shell command.
| ERROR: Execution of '/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/tmp-glibc/work/raspberrypi4-oe-linux-gnueabi/core-image-myImage/1.0-r0/temp/run.do_image_wic.40339' failed with exit code 1:
| INFO: Creating image(s)...
| 
| WARNING: bootloader config not specified, using defaults
| 
| ERROR: _exec_cmd: install -m 0644 -D /mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/tmp-glibc/deploy/images/raspberrypi4/uImage-bcm2711-rpi-4-b.dtb /mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/tmp-glibc/work/raspberrypi4-oe-linux-gnueabi/core-image-myImage/1.0-r0/deploy-core-image-myImage-image-complete/core-image-myImage-raspberrypi4-20200213161019/tmp.wic.35m3q06x/boot.1/bcm2711-rpi-4-b.dtb returned '1' instead of 0
| output: install: cannot stat '/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/tmp-glibc/deploy/images/raspberrypi4/uImage-bcm2711-rpi-4-b.dtb': No such file or directory
| 
| WARNING: exit code 1 from a shell command.
| 
ERROR: Task (/mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta-myImage-system/recipes-core/images/core-image-myImage.bb:do_image_wic) failed with exit code '1'
NOTE: Tasks Summary: Attempted 7633 tasks of which 7502 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /mnt/md0/myuser/svn/yocto/myImage-yocto-system/branches/mybranch/build/../poky/meta-myImage-system/recipes-core/images/core-image-myImage.bb:do_image_wic
Summary: There were 4 WARNING messages shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.

real	18m21.627s
user	0m4.616s
sys	0m0.532s
`

**Comment by agherzan** [comment]
Can you please reformat your issue and make sure you clearly describe what your setup is, what you are building and how it breaks? The current report is undecipherable.

**Comment by agherzan** [comment]
Closing due to lack of feedback.
