### ISSUE TITLE
rpi0-w + connman = no carrier (need connman restart or reboot)

### ISSUE THREAD

**Issue by sherpya** [agherzan/meta-raspberrypi#585]
**Description**

I have a custom image of zeus, I've added connman and wifi firmware,
When doing cold boot wifi link does not comes up.

if I try scan wifi from connmanctl I get no carrier.
Restarting connman makes the wifi work again, often it works by rebooting.

I had similar problems with thud, on sumo it works flawless

**Comment by sherpya** [comment]
I'll try to reproduce the problem starting from the minimal image

**Comment by agherzan** [comment]
I've long moved away from connman so I'm not sure how that works lately. Independently of the manager, does the interface appear when you boot? (ifconfig -a)

**Comment by agherzan** [comment]
Closing due to lack of feedback.
