### ISSUE TITLE
Question: "now what?"

### ISSUE THREAD

**Issue by cristiandgal** [agherzan/meta-raspberrypi#598]
Hey guys, this isn't an issue, more of a 'now what' question.
Got the RPI booted, but only port 22 and 111 are open, there's no 443 (for REST) or UDP for IPMI.
Any pointers? Thanks.

**Comment by agherzan** [comment]
Your message is extremely confusing. What are you trying to achieve?

**Comment by cristiandgal** [comment]
Yeah .. sorry, I was a little too in my head. I'm trying to install OpenBMC on rpi3. Got the build per your docs, but it has no OpenBMC code, so was wondering, after I get the rpi running, where do I go to install the OpenBMC code. It's not very clear from the doc. Thanks.

**Comment by agherzan** [comment]
Have you seen https://github.com/openbmc/openbmc? I would redirect any questions to them.
