### ISSUE TITLE
conf for pi zero?

### ISSUE THREAD

**Issue by daveti** [agherzan/meta-raspberrypi#6]
Hi

Is there any conf for Pi Zero? Or could I reuse Pi/Pi2 for Zero?

Thanks,
Dave

**Comment by agherzan** [comment]
As we tested it in the resin context, we were able to boot the zero conf just by using the rpi1 machine config. You could try it and let us know if you get into troubles.

**Comment by daveti** [comment]
Cool! Thanks~

**Comment by agherzan** [comment]
Wilkomen.
