### ISSUE TITLE
Raspberry Pi Zero W Console No Output with ENABLE_UART = "1"

### ISSUE THREAD

**Issue by phishstang65** [agherzan/meta-raspberrypi#605]
**Description**
I can successfully produce an image that boots the Raspberry Pi Zero with the following command:
`source ./oe-init-build-env build-rpi ; bitbake -c cleansstate core-image-minimal ; bitbake core-image-minimal ; bitbake -c populate_sdk core-image-minimal'`

However, I get no console output at all. 

My machine is set:
`MACHINE ??= "raspberrypi0-wifi"`

My local.conf has the following related contents ( Raspberry ):
```
DISTRO_FEATURES_append = " systemd"
VIRTUAL-RUNTIME_init_manager = "systemd"
DISTRO_FEATURES_BACKFILL_CONSIDERED = "sysvinit"
VIRTUAL-RUNTIME_initscripts = ""
ENABLE_UART = "1"
RPI_USE_U_BOOT = "1"
BOOT_DELAY = "1"
#BOOT_DELAY_MS = "1"
#DISABLE_RPI_BOOT_LOGO = "1"
ENABLE_SPI_BUS = "1"
ENABLE_I2C = "1"
ENABLE_DWC2_PERIPHERAL = "1"
GPU_MEM = "16"
IMAGE_FSTYPES_append = " wic"
WKS_FILE = "sdimage-raspberrypi.wks"
```

My HDMI Monitor shows the Raspberry and eventually shows a prompt to log in. 

I have this standard cable:

- https://www.adafruit.com/product/954

I have triple checked my connection between the USB Serial Cable and my PC using the following instructions:

- https://learn.adafruit.com/assets/41603
- https://learn.adafruit.com/adafruits-raspberry-pi-lesson-5-using-a-console-cable
- https://learn.adafruit.com/raspberry-pi-zero-creation/enable-uart

After flashing the card, in the boot partition, the config.txt shows this at the end:
```
# Enable UART
enable_uart=1
# Enable VC4 Graphics
dtoverlay=vc4-kms-v3d
```

I am launching the terminal console command like this:
`sudo screen /dev/cu.usbserial-14220 115200`

I get no console output, even though the Raspberry Pi Boots Successfully and local.conf has ENABLE_UART = "1"

**Steps to reproduce the issue:**
1. Set MACHINE ??= "raspberrypi0-wifi"
2. Add ENABLE_UART = "1" to local.conf
3. Build core-image-minimal
4. Flash chard and boot

**Describe the results you received:**
No Console Output to Mac Terminal screen command

**Describe the results you expected:**
Console Output to Mac Terminal screen command

**Additional information you deem important (e.g. issue happens only occasionally):**
This has never worked for me. 

**Additional details (revisions used, host distro, etc.):**
Host is a Macbook Pro

**Comment by agherzan** [comment]
I don't have a 0w to test but it would help if you could run, as a sanity check, a raspbian image.

**Comment by phishstang65** [comment]
Thanks for the comment. It turns out that I get console output on my native Ubuntu machine - but not my MacBook, maybe something with the Prolific USB/Serial drivers there.. Anyway this is not a bug with meta-raspberry and so I'll close it.
