### ISSUE TITLE
Bitbake gives error

### ISSUE THREAD

**Issue by Nishantthummar** [agherzan/meta-raspberrypi#626]
**Description**

when I try to build image for raspberrypi while running bitbake it gives error like:  Could not inherit file classes/kernel-artifact-names.bbclass. what I do. I clone raspberrypi layer again and again but same error gives.

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
 error like:  Could not inherit file classes/kernel-artifact-names.bbclass. 

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Additional details (revisions used, host distro, etc.):**

**Comment by pbrkr** [comment]
Please give us the exact commands you executed and the output you got. For bitbake the full output should make things a bit clearer.

**Comment by agherzan** [comment]
Closing due to lack of feedback.
