### ISSUE TITLE
zeus branch raspberrypi cm3 u-boot no messages in console

### ISSUE THREAD

**Issue by nandra** [agherzan/meta-raspberrypi#643]
Using meta-raspberrypi branch zeus with raspberrypi cm3 module and enable u-boot in localconf. Build image doesn't show any info in console. I tried older u-boot 2018.01 and it works fine. Ideas? 
Console is on PIN 14 and 15.
Thanks.

**Comment by agherzan** [comment]
Could it be related to https://github.com/raspberrypi/firmware/issues/1391 ?

**Comment by nandra** [comment]
Issue was missgin u-boot patch: commit id: 29f7d05a347ab7a42577c67fdfb787ef91537302

**Comment by agherzan** [comment]
Do we have that in meta-raspberrypi?

**Comment by nandra** [comment]
Nope should be cherrypicke at least for have u-boot 2020.01 working on  cm3.

**Comment by mike-scott** [comment]
@nandra Ah that makes sense.  I ended up migrating to a newer u-boot and my boot issues on CM3 went away.

@agherzan 
I notice that `https://github.com/agherzan/meta-raspberrypi/blob/master/conf/machine/raspberrypi-cm3.conf` doesn't set:
`VC4DTBO ?= "vc4-fkms-v3d"` like the other machine configurations.

I had to temporarily setup an append to get working fkms graphics.

Otherwise the default setting here is set (kms):
https://github.com/agherzan/meta-raspberrypi/blob/master/recipes-bsp/bootfiles/rpi-config_git.bb#L27

**Comment by mike-scott** [comment]
To clarify: I know that this setting in config.txt shouldn't really affect the u-boot / Linux.  But I was getting a GPU hang during Linux boot until I made sure the config.txt had the right setting here.  Who knows what the RaspberryPi firmware does prior to u-boot handoff.

**Comment by nandra** [comment]
Fix: #660

**Comment by amgedr** [comment]
U-Boot was not working in dunfell for the CM3+. It was fixed when I manually added the changes in #660. Why was the commit reverted from the dunfell branch?

**Comment by agherzan** [comment]
Can you point me to the revert PR?

**Comment by amgedr** [comment]
Sorry, should've mentioned that. Its #699

**Comment by nandra** [comment]
Also stock zeus build (without u-boot) doesn't boot on CM3. Anyone have some idea? CM3 is light version without eMMC. Thanks.

**Comment by nandra** [comment]
Nah I was wrong. It just took some time until it start and need to enable console :). Sorry for noise.

**Comment by agherzan** [comment]
@amgedr That PR was a hefty backport. Would be hard for me to spot the issue from it. We would need to do a bit of investigation.

**Comment by amgedr** [comment]
Hope this helps when you get a chance to review: #660's commit f20ccfa11db4c0d1608cf6f3e654d29c5bfc3dd3 solved the CM3+ booting issue when u-boot is enabled. But as you commented in #699, it was reverted in 8258e733ea89b6ac1f65419a8baf42110b83fdbc because it was missing the following line:
```
FILESEXTRAPATHS_prepend := "${THISDIR}/files:"
```

**Comment by agherzan** [comment]
That makes sense - and I remember now. Do you feel like pushing that? CC @nandra

**Comment by nandra** [comment]
Should I redo patch or @amgedr will you do it? Thanks.

**Comment by agherzan** [comment]
I didn't know you are up for it. If you want, it would probably be better if you could do it as you know better patch.

**Comment by nandra** [comment]
PR #747

**Comment by agherzan** [comment]
Thanks @nandra . @amgedr do you have a second to give the PR a spin?

**Comment by amgedr** [comment]
Sorry, didn't notice the notification email earlier. Works on CM3+.

**Comment by vkotarov** [comment]
Not sure if this is the right place to comment but the patch somehow made it to gatesgarth. On the other hand, it's not needed there as u-boot version is 2020.07 and already has it applied. Eventually, the do_patch task breaks on gatesgarth (probably on hardknott, too)

**Comment by agherzan** [comment]
Looks fixed. Ping me otherwise.
