### ISSUE TITLE
A proper way to add dtbo to boot partition?

### ISSUE THREAD

**Issue by BlackZork** [agherzan/meta-raspberrypi#648]
What is a recommended way to add dtbo files to boot partition?

For now I am doing it in [local.conf](https://github.com/BlackZork/meta-rpi-qml/commit/a8a41f3f80294cbb97f2b94a0e437d1d55eece0b):

KERNEL_DEVICETREE_append = " \
  overlays/rpi-backlight.dtbo \
"

I am not sure if this is the proper way to do it.

**Comment by agherzan** [comment]
We are generally trying to include them all but that is definitely a way to include some that are not currently available in all the supported kernel versions.
