### ISSUE TITLE
core-image-sato is not booting RPI4 

### ISSUE THREAD

**Issue by pankajjoshi347** [agherzan/meta-raspberrypi#674]
Hi,
i am trying to build core-image-sato for RPI4 i have added all the required layers in bblayer and also i have added all necessary features and install packages, i am attaching the the installs that i have added in local.conf

EXTRA_IMAGE_FEATURES  ?= " debug-tweaks "
ENABLE_UART = "1"
CORE_IMAGE_EXTRA_INSTALL += " git ruby bsdtar pseudo os-release lsb-release cmake vim  sysstat numactl python3 apt"
DISTRO_FEATURES_append  = " python3-pip perf opengl"
EXTRA_IMAGE_FEATURES_append  +=  "src-pkgs package-management ssh-server-openssh stateless-rootfs "
IMAGE_INSTALL_append  = " glibc-utils localedef unicode-ucd "
IMAGE_FEATURES_append  = "tools-debug tools-sdk dev-pkgs"
CORE_IMAGE_EXTRA_INSTALL += " kernel-modules bash e2fsprogs mtools parted dosfstools mtd-utils-ubifs openssh"
DISTRO_FEATURES_append +=  " x11 "
MACHINE_FEATURES_append += "vc4graphics"
IMAGE_INSTALL += "glibc-staticdev"
IMAGE_INSTALL_append = "perf dbus libnss-mdns minicom rsync dbus dstat hostapd dhcpcd nasm ncurses-libncurses ncurses-tools ncurses-terminfo-base"
EXTRA_IMAGE_FEATURES += "staticdev-pkgs "
DISTRO ?= "exaleap-arm-linux"
EXTRA_IMAGE_FEATURES ?= " allow-empty-password allow-root-login bash-completion-pkgs dbg-pkgs debug-tweaks dev-pkgs doc doc-pkgs eclipse-debug empty-root-password hwcodecs nfs-client nfs-server package-management post-install-logging ptest-pkgs splash src-pkgs ssh-server-dropbear ssh-server-openssh staticdev-pkgs tools-debug tools-profile tools-sdk tools-testapps x11 x11-base x11-sato "
VIRTUAL-RUNTIME_init_manager += "systemd"

Oe-Raspberrypi4$ bitbake core-image-sato
Parsing recipes: 100% |######################################################################################################################################################################| Time: 0:02:45
Parsing of 2279 .bb files complete (0 cached, 2279 parsed). 3439 targets, 158 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION           = "1.46.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-18.04"
TARGET_SYS           = "aarch64-oe-linux"
MACHINE              = "raspberrypi4-64"
DISTRO               = "exaleap-arm-linux"
DISTRO_VERSION       = "exaleap-arm-linux-r1.0.0"
TUNE_FEATURES        = "aarch64 cortexa72 crc crypto"
TARGET_FPU           = ""
meta                 = "master:982b7f98b8423236cc986346379b1bde3694f131"
meta-oe              
meta-python          
meta-networking      
meta-multimedia      
meta-perl            = "dunfell:e413c1ef621688e69bb7830bb3151ed23b30b73e"
meta-raspberrypi     = "master:5ac6f013339b0b1ab2d71f9f6af48a186e126c19"
meta-pankaj          = "<unknown>:<unknown>"

Initialising tasks: 100% |###################################################################################################################################################################| Time: 0:00:08
Sstate summary: Wanted 133 Found 126 Missed 7 Current 1200 (94% match, 99% complete)
NOTE: Executing Tasks
NOTE: Tasks Summary: Attempted 3932 tasks of which 3914 didn't need to be rerun and all succeeded.

I would like to mention i am not getting any error while buliding the image and i have successfully copied the image as well which is core-image-sato-raspberrypi4-64.wic.bz2  and i am able to see both the partitions as well.
Everything seems to be correct but i am not able to understand why the image is not booting, i am missing anything or adding something extra due to which this is happening  ??
Kindly suggest

Thanks!

**Comment by agherzan** [comment]
Have you checked the serial debug console?
