### ISSUE TITLE
Building with kernel5.4.50 failed

### ISSUE THREAD

**Issue by embdlover** [agherzan/meta-raspberrypi#681]
Hi i am trying to build core-image-minimal for RPI4 i am getting following error

bitbake core-image-minimal
Loading cache: 100% |########################################################################################################################################################################| Time: 0:00:00
Loaded 3439 entries from dependency cache.
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION           = "1.46.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-18.04"
TARGET_SYS           = "aarch64-oe-linux"
MACHINE              = "raspberrypi4-64"
DISTRO               = "exaleap-arm-linux"
DISTRO_VERSION       = "exaleap-arm-linux-r1.0.0"
TUNE_FEATURES        = "aarch64 cortexa72 crc crypto"
TARGET_FPU           = ""
meta                 = "master:982b7f98b8423236cc986346379b1bde3694f131"
meta-oe              
meta-python          
meta-networking      
meta-multimedia      
meta-perl            = "dunfell:e413c1ef621688e69bb7830bb3151ed23b30b73e"
meta-raspberrypi     = "master:5ac6f013339b0b1ab2d71f9f6af48a186e126c19"
meta-pankaj          = "<unknown>:<unknown>"

Initialising tasks: 100% |###################################################################################################################################################################| Time: 0:00:02
Sstate summary: Wanted 29 Found 0 Missed 29 Current 1677 (0% match, 98% complete)
NOTE: Executing Tasks
WARNING: linux-raspberrypi-1_5.4.50+gitAUTOINC+856e83151c-r0 do_fetch: Failed to fetch URL git://github.com/raspberrypi/linux.git;branch=rpi-5.4.y, attempting MIRRORS if available
ERROR: linux-raspberrypi-1_5.4.50+gitAUTOINC+856e83151c-r0 do_fetch: Fetcher failure: Unable to find revision 856e83151cf3f802c495585ac176bb135a08030f in branch rpi-5.4.y even from upstream
ERROR: linux-raspberrypi-1_5.4.50+gitAUTOINC+856e83151c-r0 do_fetch: Fetcher failure for URL: 'git://github.com/raspberrypi/linux.git;branch=rpi-5.4.y'. Unable to fetch URL from any source.
ERROR: Logfile of failure stored in: /home/pankaj/Oe-Raspberrypi4_1/tmp-glibc/work/raspberrypi4_64-oe-linux/linux-raspberrypi/1_5.4.50+gitAUTOINC+856e83151c-r0/temp/log.do_fetch.28419
ERROR: Task (/home/pankaj/Source/meta-raspberrypi/recipes-kernel/linux/linux-raspberrypi_5.4.bb:do_fetch) failed with exit code '1'

**Comment by texierp** [comment]
Hi @embdlover 


> WARNING: linux-raspberrypi-1_5.4.50+gitAUTOINC+856e83151c-r0 do_fetch: Failed to fetch URL git://github.com/raspberrypi/linux.git;branch=rpi-5.4.y, attempting MIRRORS if available
> ERROR: linux-raspberrypi-1_5.4.50+gitAUTOINC+856e83151c-r0 do_fetch: Fetcher failure: Unable to find revision 856e83151cf3f802c495585ac176bb135a08030f in branch rpi-5.4.y even from upstream
> ERROR: linux-raspberrypi-1_5.4.50+gitAUTOINC+856e83151c-r0 do_fetch: Fetcher failure for URL: 'git://github.com/raspberrypi/linux.git;branch=rpi-5.4.y'. Unable to fetch URL from any source.
> ERROR: Logfile of failure stored in: /home/pankaj/Oe-Raspberrypi4_1/tmp-glibc/work/raspberrypi4_64-oe-linux/linux-raspberrypi/1_5.4.50+gitAUTOINC+856e83151c-r0/temp/log.do_fetch.28419
> ERROR: Task (/home/pankaj/Source/meta-raspberrypi/recipes-kernel/linux/linux-raspberrypi_5.4.bb:do_fetch) failed with exit code


Yes, they are a rebase and force push from upstream, PR #679 fixes this issue ;)
