### ISSUE TITLE
How to update linux-firmware-rpidistro?

### ISSUE THREAD

**Issue by gvkalra** [agherzan/meta-raspberrypi#686]
**Description**
Stuck with `thud`.
However, want to update `linux-firmware-rpidistro` to the latest in `master`.
Adding new SRCREV to `.bbappend` leads to `check_data_file_clashes` error.

**Steps to reproduce the issue:**
1. Create `linux-firmware-rpidistro_%.bbappend`
2. Change SRCREV and LICENSE (copied from `master`)
```
LIC_FILES_CHKSUM = "\
    file://LICENCE.broadcom_bcm43xx;md5=3160c14df7228891b868060e1951dfbc \
    file://WHENCE;md5=7b12b2224438186e4c97c4c7f3a5cc28 \
"

SRCREV = "616fc2dd4df421e3974179d9e46d45e7006aeb28"
PV = "20190114-1+rpt6"
```
3. bitbake image

**Describe the results you received:**
```
Collected errors:
 * check_data_file_clashes: Package linux-firmware wants to install file /media/gvkalra/66bef40b-d84f-4ad0-ada6-a025b494ca5d/seesv-distro/build-raspberrypi3-devel-staging/tmp/work/raspberrypi3-poky-linux-gnueabi/seesv-embedded-qt5-image/1.0-r0/rootfs/lib/firmware/brcm/brcmfmac43430-sdio.AP6212.txt
	But that file is already provided by package  * linux-firmware-rpidistro-bcm43430
 * check_data_file_clashes: Package linux-firmware wants to install file /media/gvkalra/66bef40b-d84f-4ad0-ada6-a025b494ca5d/seesv-distro/build-raspberrypi3-devel-staging/tmp/work/raspberrypi3-poky-linux-gnueabi/seesv-embedded-qt5-image/1.0-r0/rootfs/lib/firmware/brcm/brcmfmac43430-sdio.Hampoo-D2D3_Vi8A1.txt
	But that file is already provided by package  * linux-firmware-rpidistro-bcm43430
 * check_data_file_clashes: Package linux-firmware wants to install file /media/gvkalra/66bef40b-d84f-4ad0-ada6-a025b494ca5d/seesv-distro/build-raspberrypi3-devel-staging/tmp/work/raspberrypi3-poky-linux-gnueabi/seesv-embedded-qt5-image/1.0-r0/rootfs/lib/firmware/brcm/brcmfmac43430-sdio.MUR1DX.txt
	But that file is already provided by package  * linux-firmware-rpidistro-bcm43430
```

**Describe the results you expected:**
`linux-firmware-rpidistro` should have been updated.

**Additional information you deem important (e.g. issue happens only occasionally):**
Always

**Additional details (revisions used, host distro, etc.):**
Ubuntu 16.04

Probably not directly a `meta-raspberrypi` problem, and in that case I apologize for the noise.
However, the exact same procedure for `linux-raspberrypi` works without any problems.

**Comment by agherzan** [comment]
You create a clash in between `linux-firmware` and this recipe. I suspect `thud` was providing in the main package the `bcm43430` blobs so you will need to bbappend that too to fix this issue.

**Comment by gvkalra** [comment]
Thanks...
