### ISSUE TITLE
u-boot fetch error for fw_env.config in dunfell

### ISSUE THREAD

**Issue by mtrensch** [agherzan/meta-raspberrypi#696]
**Description**

Fetching u-boot fails as "fw_env.config" cannot be found:
```
ERROR: u-boot-1_2020.01-r0 do_fetch: Fetcher failure for URL: 'file://fw_env.config'. Unable to fetch URL from any source.
ERROR: Logfile of failure stored in: /build/build_raspberrypi/tmp/work/niot_e_tpi51_en_re-poky-linux-gnueabi/u-boot/1_2020.01-r0/temp/log.do_fetch.25975
NOTE: recipe u-boot-1_2020.01-r0: task do_fetch: Failed
ERROR: Task (/build/build_raspberrypi/../poky/meta/recipes-bsp/u-boot/u-boot_2020.01.bb:do_fetch) failed with exit code '1'
```

**Steps to reproduce the issue:**
1. build u-boot (bitbake u-boot)

**Describe the results you received:**

```
ERROR: u-boot-1_2020.01-r0 do_fetch: Fetcher failure for URL: 'file://fw_env.config'. Unable to fetch URL from any source.
ERROR: Logfile of failure stored in: /build/build_raspberrypi/tmp/work/niot_e_tpi51_en_re-poky-linux-gnueabi/u-boot/1_2020.01-r0/temp/log.do_fetch.25975
NOTE: recipe u-boot-1_2020.01-r0: task do_fetch: Failed
ERROR: Task (/build/build_raspberrypi/../poky/meta/recipes-bsp/u-boot/u-boot_2020.01.bb:do_fetch) failed with exit code '1'
```

**Describe the results you expected:**
Building works.

**Additional information you deem important (e.g. issue happens only occasionally):**

This bug was introduced by following commit:
https://github.com/agherzan/meta-raspberrypi/commit/fc494a35b513b05860c5a813239274017f1ef934

The file fw_env.config resides in "${THISDIR}/files" which is not in FILESEXTRAPATHS. Either move it to u-boot or add "${THISDIR}/files" to FILESEXTRAPATHS.

**Comment by agherzan** [comment]
Should be fixed now.
