### ISSUE TITLE
Issue tracker down

### ISSUE THREAD

**Issue by zwerch** [agherzan/meta-raspberrypi#7]
Your external issue tracker seems to be offline.

**Comment by agherzan** [comment]
Yeah... i moved to to AWS. I'm seriously wondering if we should just move completely on github. And maybe just ask people to send the patches to mailing list too for more community visibility.

**Comment by zwerch** [comment]
Just do it :grinning:

**Comment by agherzan** [comment]
:) https://lists.yoctoproject.org/pipermail/yocto/2016-April/029682.html
