### ISSUE TITLE
vc4graphics support on morty build

### ISSUE THREAD

**Issue by moorthy-bs** [agherzan/meta-raspberrypi#725]
**is vc4graphics support available on morty builds?**

vc4graphics is enabled by default in dunfell/master based builds. The changes which are required on userland, mesa and others are available on morty branch but not enabled by default.
The difference between morty and master is mesa and wayland version. dunfell/master build has mesa v 20.x and wayland 18.0+ whereas in morty based build, mesa version is 12.0.1 and wayland is 11.0
When enabled vc4grpahics purposefully on morty based builds, wayland client applicants are failed to launch on top a wayland compositor by saying below error
wl_drm@12: error 2: invalid name
Does mesa v 12.0.1 support vc4graphics? What else required to enable vc4graphics on morty builds?

**Steps to reproduce the issue:**
1. MACHINE_FEATURES += "vc4graphics"
2.
3.

**Describe the results you received:**
Wayland client apps through a common error when tried to run on top of a wayland compositor
wl_drm@12: error 2: invalid name

**Describe the results you expected:**
Wayland client apps to be run on top of wayland compositor

**Additional information you deem important (e.g. issue happens only occasionally):**

**Additional details (revisions used, host distro, etc.):**
DISTRO = rdk
Wayland compositor is "Westeros"

**Comment by kraj** [comment]
morty might not be possible for vc4graphics

**Comment by agherzan** [comment]
We don't work on or maintain morty anymore so I don't think many people can confirm/infirm this support. It's sadly one of those cases where patches are welcomed - I know it's not helpful but that's the situation.

**Comment by moorthy-bs** [comment]
vc4graphics support works from mesa version > 17.x whereas morty based builds provide mesa 12.x
