### ISSUE TITLE
Is it possible to encrypt the rootfs partition in the SD card image ?

### ISSUE THREAD

**Issue by myfreescalewebpage** [agherzan/meta-raspberrypi#734]
**Description**

Is it possible to encrypt the rootfs partition in the SD card image ? The goal is to prevent someone to retrieve the content of the SD card on another machine. On compute module target, the goal is to prevent someone to read the content of the eMMC throw the USB OTG port.

I have read several things about this subject (https://linux.die.net/man/8/cryptsetup for example) but the purpose is to do it with Yocto of course :)

**Describe the results you expected:**

rootfs partition encrypted

**Additional details (revisions used, host distro, etc.):**

Currently using dunfell but it's not a strong requirment

**Comment by agherzan** [comment]
Sure it is. You can use an initramfs to unlock a luks device. Nevertheless, this solution is not RPi specific at all.

**Comment by myfreescalewebpage** [comment]
@agherzan thanks for the answer, looks good if it is not rpi specific. Can you anyway point us a link/tuto if you know to help starting on this subject ? I haven't found pertinent content at this time...

**Comment by agherzan** [comment]
Here it is: https://wiki.archlinux.org/index.php/dm-crypt
