### ISSUE TITLE
Readme is too long and needs breaking up

### ISSUE THREAD

**Issue by betafive** [agherzan/meta-raspberrypi#74]
Creating this so we don't forget...

Should we split the Readme into files in a doc directory in the git repository itself or should we use the wiki on GitHub? My preference is a doc directory as we're then not tied to GitHub too closely.

**Comment by agherzan** [comment]
I would not go for github wiki either as I'm not sure how we can migrate in case we want to switch from it. I would vote though for something that can be interpreted / parsed / compiled in pdf and html.

**Comment by betafive** [comment]
Ok. It sounds like a doc directory full of markdown formatted files is the way to go. We can then use sphinx or one of the thousand other similar tools to turn that into html/pdf.
