### ISSUE TITLE
unable to boot raspberry pi 3b using 64 bit configuration

### ISSUE THREAD

**Issue by AnanduKE** [agherzan/meta-raspberrypi#765]
Hi,
I am unable to boot raspberry pi 3b using 64 bit configuration. Boot just hangs after
 Starting syslogd/klogd: done
i am using dunfell branch.
Enabled uart and currently using uart for getting console

**Comment by agherzan** [comment]
Can you paste UART boot logs and also build configuration?

**Comment by abhi-84** [comment]
I am facing the similar issue but I am not using UART. I ave tried with both dunfell and gatesgarth but same issue. With Warrior branch it is working fine. I wanted to access pi using ssh but ethernet port is not getting activated.
When connected with HDMI, I am getting following message:
[https://i.stack.imgur.com/dpaET.jpg](url)
Please help

Abhishek

**Comment by agherzan** [comment]
That is not the same issue. Your boot fails while loading the kernel image in uboot while this issue reports hanging in userspace. As there is no update on the initial issue, I'll close this.
