### ISSUE TITLE
Limited dt overlays?

### ISSUE THREAD

**Issue by shawaj** [agherzan/meta-raspberrypi#784]
**Description**

I just wondered if there is a particular reason why the [rpi-base.inc](https://github.com/agherzan/meta-raspberrypi/blob/master/conf/machine/include/rpi-base.inc) only includes a small subset of dtoverlays? Could you explain how you decide what should/shouldn't go in here?

**Comment by agherzan** [comment]
We started from a set back in the days based on what kernel supported and users requested, Also, we wanted to keep them working on all the versions included in the layer. Always up for PRs though as long as it doesn't break any kernel version in the layer.
