### ISSUE TITLE
Boot Log does not show

### ISSUE THREAD

**Issue by embexus** [agherzan/meta-raspberrypi#789]
Boot Log does not show on raspberrypi3 with LCD 7'' display if cmdline.txt contains **quiet**

**Steps to reproduce the issue:**
1. Build meta-raspberrypi (Gatesgarth) default settings and add **quiet** to cmdline.txt

**Describe the results you received:**

No Logo
**Describe the results you expected:**

Logo with 4x raspberries

**Additional information you deem important (e.g. issue happens only occasionally):**

**Additional details (revisions used, host distro, etc.):**
poky gatesgarth

**Comment by embexus** [comment]
there should be no coupling between loglovel (quiet) and boot logo display

**Comment by embexus** [comment]
it seems that this Bug is a feature in linux raspberrypi kernel !

https://github.com/raspberrypi/linux/commit/10993504d647356196a04b3022d645ec92e00159

**Comment by agherzan** [comment]
@embexus Thanks for reporting this. I'll defer this to the linux raspberrypi project. For me this upstream change makes sense but if for your specific usecase it doesn't, probably the easiest way forward would be a revert in a local layer. Much more elegant would be to take it upstream and maybe implement it as an argument.
