### ISSUE TITLE
Build fails due to gstreamer

### ISSUE THREAD

**Issue by deep5050** [agherzan/meta-raspberrypi#790]
**Description**
```
ERROR: No recipes in default available for:
  /home/dipankar/poky/meta-raspberrypi/recipes-multimedia/gstreamer/gstreamer1.0-omx_1.18%.bbappend
  /home/dipankar/poky/meta-raspberrypi/recipes-multimedia/gstreamer/gstreamer1.0-plugins-good_1.18.%.bbappend
```
Showing this error while building `core-image-base` `MACHINE = "raspberrypi3-64"`

**Steps to reproduce the issue:**
1. `bitbake core-image-base`
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Additional details (revisions used, host distro, etc.):**
host: Ubuntu 16.04

**Comment by kraj** [comment]
are you using matching branch of meta-raspberrypi with poky/

**Comment by deep5050** [comment]
> are you using matching branch of meta-raspberrypi with poky/

using `master`

**Comment by kraj** [comment]
in `local.conf` add
```
LICENSE_FLAGS_WHITELIST_append = " commercial_gstreamer1.0-omx "
```

**Comment by deep5050** [comment]
> in `local.conf` add
> 
> ```
> LICENSE_FLAGS_WHITELIST_append = " commercial_gstreamer1.0-omx "
> ```

thanks for the quick response, but this did not help me

**Comment by deep5050** [comment]
> > in `local.conf` add
> > ```
> > LICENSE_FLAGS_WHITELIST_append = " commercial_gstreamer1.0-omx "
> > ```
> 
> thanks for the quick response, but this did not help me

Even I switched to `gatesgarth` branch both for poky and meta-raspberry. still having this issue.

**Comment by deep5050** [comment]
i had to add gstreamer layer manually to resolve it.
