### ISSUE TITLE
include backlight dtbo 

### ISSUE THREAD

**Issue by embexus** [agherzan/meta-raspberrypi#795]
what is the proper way to include backlight overlay *rpi-backlight-overlay.dtbo* in meta-raspberrypi ?

RPI_KERNEL_DEVICETREE_OVERLAYS_append = " overlays/rpi-backlight-overlay.dtbo"  added to local.conf is built but NOT added to the bootfiles !

**Comment by embexus** [comment]
it should be :
RPI_KERNEL_DEVICETREE_OVERLAYS_append = " overlays/rpi-backlight.dtbo"

**Comment by agherzan** [comment]
What's the difference?

**Comment by embexus** [comment]
backlight-overlay.dtbo and rpi-backlight.dtbo the difference is "-overlay" string should be removed

**Comment by agherzan** [comment]
I see it now. Enjoy!
