### ISSUE TITLE
raspberrypi0-wifi nodejs12

### ISSUE THREAD

**Issue by nandra** [agherzan/meta-raspberrypi#796]
Hi,

it's not specific to this layer but I would like to ask if anybody compile sucessfully nodejs12 package (from dunfell) for raspberrypi0-wifi machine. It works pretty fine for raspberrypi3 but it fails for raspberrypi0-w with:
```
/usr/include/c++/9.3.0/atomic:254: undefined reference to `__atomic_load_8'
```
Any ideas? Thanks.

**Comment by agherzan** [comment]
Sorry @nandra I guess nobody hit this one. Did you figure ir out or shall we close it as a non-BSP issue?
