### ISSUE TITLE
Inherit kernel is called twice

### ISSUE THREAD

**Issue by JonasVautherin** [agherzan/meta-raspberrypi#797]
It's probably a detail, but I realized that in [linux-raspberrypi.inc](https://github.com/agherzan/meta-raspberrypi/blob/master/recipes-kernel/linux/linux-raspberrypi.inc#L11-L12):

```
inherit kernel siteinfo
require recipes-kernel/linux/linux-yocto.inc
```

There is `inherit kernel` right before requiring `linux-yocto.inc`. But `linux-yocto.inc` [already inherits kernel](https://git.yoctoproject.org/cgit.cgi/poky/tree/meta/recipes-kernel/linux/linux-yocto.inc#n45).

Is there a reason why this is needed here, or is it superfluous?

I'm pretty new to Yocto, just trying to understand :slightly_smiling_face:.

**Comment by kraj** [comment]
I guess its redundant can can be removed from explicit inherit here.

**Comment by agherzan** [comment]
It's a miss or at some point, this was not the case. I bet on the latter. Up for a small PR?
