### ISSUE TITLE
rpi-specific features documantation

### ISSUE THREAD

**Issue by moose-rivieh** [agherzan/meta-raspberrypi#810]
The readme file provides examples of rpi-specific image features such as ENABLE_I2C = "1". Where can I find the document that lists all available options and their syntax? For example, is there an ENABLE_SPI option? Thx!

**Comment by aurelian17** [comment]
You can try: https://meta-raspberrypi.readthedocs.io/en/latest/extra-build-config.html

**Comment by agherzan** [comment]
One of the links in the readme files contains a link to the full documentation. https://meta-raspberrypi.readthedocs.io/en/latest/
