### ISSUE TITLE
Initramfs support with .wks (wic) images?

### ISSUE THREAD

**Issue by bvarner** [agherzan/meta-raspberrypi#816]
I've been working with attempting to get an initramfs image to work. I can get things to function with the sdimg class, but for the project I'm working on (and future projects) I'd prefer to use WIC.

I cannot seem to figure out how to make this work with WIC. 

Any pointers?

**Comment by agherzan** [comment]
There is nothing dramatically special with the sdimg approach. The only thing it does is to deploy the bundled kernel image as opposed to the normal one in the case of related initramfs configuration. 

Probably all you need is to tweak  `IMAGE_BOOT_FILES`. MInd the output name of the deployed file - see https://www.yoctoproject.org/docs/2.1/ref-manual/ref-manual.html#var-IMAGE_BOOT_FILES
