### ISSUE TITLE
fakeroot1.18.4

### ISSUE THREAD

**Issue by pankajjoshi347** [agherzan/meta-raspberrypi#833]
Hi,
i am building core-image-minimal for raspberrypi4 but while building fakeroot 1.18.4 i am getting following error

/Yocto/ARM/Build_Dir_ARM$ bitbake core-image-minimal
Loading cache: 100% |########################################################################################################################################################################| Time: 0:00:00
Loaded 3823 entries from dependency cache.
Parsing recipes: 100% |######################################################################################################################################################################| Time: 0:00:00
Parsing of 2487 .bb files complete (2486 cached, 1 parsed). 3822 targets, 173 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION           = "1.49.2"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-18.04"
TARGET_SYS           = "aarch64-oe-linux"
MACHINE              = "raspberrypi4-64"
DISTRO               = "nodistro"
[fakeroot_error.txt](https://github.com/agherzan/meta-raspberrypi/files/6180498/fakeroot_error.txt)
DISTRO_VERSION       = "nodistro.0"
TUNE_FEATURES        = "aarch64 armv8a crc crypto cortexa72"
TARGET_FPU           = ""
meta                 = "master:ecb038f14c0b91280ba1532ad94a6ebc64c70644"
meta-oe              
meta-python          
meta-networking      
meta-perl            
meta-multimedia      
meta-filesystems     = "master:fbd73ac3f30865a8173cdb99d43261b7085425b7"
meta-raspberrypi     = "master:fdf02accfe3f68d11fa178d72eb377f9ca96411c"
meta-exleap-arm      = "<unknown>:<unknown>"

Initialising tasks: 100% |###################################################################################################################################################################| Time: 0:00:03
Sstate summary: Wanted 366 Local 269 Network 0 Missed 97 Current 808 (73% match, 91% complete)
NOTE: Executing Tasks
ERROR: fakeroot-1.18.4-r0 do_compile: oe_runmake failed
ERROR: fakeroot-1.18.4-r0 do_compile: Execution of '/home/pankaj/Yocto/ARM/Build_Dir_ARM/tmp-glibc/work/cortexa72-oe-linux/fakeroot/1.18.4-r0/temp/run.do_compile.7978' failed with exit code 1:
make  all-recursive
make[1]: Entering directory '/home/pankaj/Yocto/ARM/Build_Dir_ARM/tmp-glibc/work/cortexa72-oe-linux/fakeroot/1.18.4-r0/build'
Making all in scripts
make[2]: Entering directory '/home/pankaj/Yocto/ARM/Build_Dir_ARM/tmp-glibc/work/cortexa72-oe-linux/fakeroot/1.18.4-r0/build/scripts'
sed -e 's,[@]prefix[@],/usr,g' -e 's,[@]bindir[@],/usr/bin,g' -e 's,[@]libdir[@],/usr/lib,g' -e 's,[@]fakeroot_transformed[@],'`echo fakeroot | sed -e 's,x,x,'`',g' -e 's,[@]faked_transformed[@],'`echo faked | sed -e 's,x,x,'`',g' -e 's,[@]signal[@],TERM,g' -e 's,[@]SHELL[@],/bin/bash,g' -e 's,[@]VERSION[@],1.18.4,g' -e 's,[@]DLSUFFIX[@],.so,g' -e 's,[@]LDLIBPATHVAR[@],LD_LIBRARY_PATH,g' -e 's,[@]LDPRELOADVAR[@],LD_PRELOAD,g' -e 's,[@]LDPRELOADABS[@],0,g' -e 's,[@]LDEXTRAVAR[@],,g' -e 's,[@]MACOSX_FALSE[@],,g' -e 's,[@]MACOSX_TRUE[@],#,g' < ../../fakeroot-1.18.4/scripts/fakeroot.in > fakeroot
chmod +x fakeroot
make[2]: Leaving directory '/home/pankaj/Yocto/ARM/Build_Dir_ARM/tmp-glibc/work/cortexa72-oe-linux/fakeroot/1.18.4-r0/build/scripts'
Making all in doc
make[2]: Entering directory '/home/pankaj/Yocto/ARM/Build_Dir_ARM/tmp-glibc/work/cortexa72-oe-linux/fakeroot/1.18.4-r0/build/doc'
Making all in de
[fakeroot_error.txt](https://github.com/agherzan/meta-raspberrypi/files/6180489/fakeroot_error.txt)

attaching complete log file herewith  can someone help me to fix this issue ?

**Comment by agherzan** [comment]
This a similar issue as to the ones fixed in pseudo. See oe-core for patches or https://git.yoctoproject.org/cgit/cgit.cgi/pseudo/log/?h=oe-core. At its core, it's due to the Glibc upgrade.

Closing this as it is not in the BSP layer scope but the above should give you a starting point.
