### ISSUE TITLE
What "other data" is located in the 4MiB between 0 and IMAGE_ROOTFS_ALIGNMENT?

### ISSUE THREAD

**Issue by evading** [agherzan/meta-raspberrypi#837]
In `classes/sdcard_image-rpi.bbclass` there is a comment:
```
#    0                      -> IMAGE_ROOTFS_ALIGNMENT         - reserved for other data
```
I'm curious about what "other data" that is as I would like to use that space for two redundant u-boot environments.
I realise there is an MBR in there in the beginning but that will not consume the full 4MiB, right?

Is it safe to assume that the space between 3MiB and 4MiB is available for this?

Thanks for an awesome layer!

Best regards,
Einar

**Comment by agherzan** [comment]
That was only done for performance reasons on SD cards. And indeed, you should be able to use the remaining free space. What is your usecase?

**Comment by evading** [comment]
We have found that placing the u-boot environment on a FAT partition is a bit fragile. And, with the partition layout we're using, it forces us to mount the boot partition R/W. Also I don't think u-boot supports redundant envs in FAT.

To get around that we plan to put two u-boot environments straight on the device at some offset in the first 4MiB, like at 3MiB and 3.5MiB.
