### ISSUE TITLE
Raspberry pi 4 not booting after burning core-image-base.wic.bz2

### ISSUE THREAD

**Issue by Kottoz** [agherzan/meta-raspberrypi#839]
What i'm trying to do is installing `update-image` from meta-swupdate. whichi is based on `core-image-full-cmdline`, so first i try to bitbake `core-image-full-cmdline` without adding swupdate bsp layer to bblayers. 

i follow steps from meta-raspberrypi:

- Poky
  - branch: master
  - revision: HEAD
- Open-embedded
  - branch: master
  - revision: HEAD
- meta-raspberrypi
  - branch:master
 
- my target specifications:
  - Raspberry pi 4 - 2GB Ram.
  - SDcard 32 GB class 10.
 
after use the default configuration of `local.conf`, and add layers to `bblayers.conf` then i run `bitbake core-image-full-cmdline`;
build is successful.
```
Loading cache: 100% |                                                                                                                                                         | ETA:  --:--:--
Loaded 0 entries from dependency cache.
Parsing recipes: 100% |########################################################################################################################################################| Time: 0:00:42
Parsing of 2465 .bb files complete (0 cached, 2465 parsed). 3796 targets, 143 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION           = "1.49.2"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "universal"
TARGET_SYS           = "arm-poky-linux-gnueabi"
MACHINE              = "raspberrypi4"
DISTRO               = "poky"
DISTRO_VERSION       = "3.2+snapshot-ef501020fb44c7f1984fc854d0a70d082aa9a5c1"
TUNE_FEATURES        = "arm vfp cortexa7 neon vfpv4 thumb callconvention-hard"
TARGET_FPU           = "hard"
meta                 
meta-poky            
meta-yocto-bsp       = "master:ef501020fb44c7f1984fc854d0a70d082aa9a5c1"
meta-raspberrypi     = "master:f9a13f3b9a90f4f033afa9f34b66ca7432a7742b"
meta-oe              
meta-python          
meta-networking      
meta-perl            
meta-multimedia      = "master:454644c578c84062f49b443626b7bb7dfff06060"

Initialising tasks: 100% |#####################################################################################################################################################| Time: 0:00:06
Sstate summary: Wanted 205 Local 0 Network 0 Missed 205 Current 1117 (0% match, 84% complete)
Removing 4 stale sstate objects for arch cortexa7t2hf-neon-vfpv4: 100% |#######################################################################################################| Time: 0:00:00
Removing 1 stale sstate objects for arch raspberrypi4: 100% |##################################################################################################################| Time: 0:00:00
NOTE: Executing Tasks
NOTE: Tasks Summary: Attempted 3490 tasks of which 3030 didn't need to be rerun and all succeeded.
```
before boot from sdcard i run raspbian lite image and every thing is worked well, hdmi monitor, and wifi.

 then i use ` sudo bmaptool copy core-image-base-raspberrypi4.wic.bz2 /dev/sdb `  to my sd card, after that raspberrypi not booting. 
then i plug sdcard and every thing is done correctly and pi have booted well. 

[local.txt](https://github.com/agherzan/meta-raspberrypi/files/6266497/local.txt)
[bblayers.txt](https://github.com/agherzan/meta-raspberrypi/files/6266499/bblayers.txt)

**Comment by Kottoz** [comment]
Edit i try the last steps, with new HW device, raspberry pi 3, and it works fine. and boots properly, so what is  wrong  with RPI4?

**Comment by kraj** [comment]
I just booted today from master branches of layer and it works all fine for rpi4 ( I use yoe distro )

**Comment by Kottoz** [comment]
I will test changing to master

**Comment by Kottoz** [comment]
@kraj i have tested master poky. 
here is my `local.conf`
```
MACHINE = "raspberrypi4-64"

RPI_USE_U_BOOT = "1"
LICENSE_FLAGS_WHITELIST = "commercial"
IMAGE_INSTALL_append = " kernel-image kernel-modules"
INHERIT += "image-buildinfo"
IMAGE_ROOTFS_EXTRA_SPACE = "327680"

DISTRO_FEATURES_append = " systemd"
DISTRO_FEATURES_BACKFILL_CONSIDERED += "sysvinit"
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = "systemd-compat-units"
DL_DIR ?= "/home/kotoz/Desktop/Embedded_linux/yocto_for_rpi/downloads"
SSTATE_DIR ?= "/home/kotoz/Desktop/Embedded_linux/yocto_for_rpi/sstate-cache"
DISTRO ?= "poky"
PACKAGE_CLASSES ?= "package_ipk"
EXTRA_IMAGE_FEATURES ?= "debug-tweaks"
USER_CLASSES ?= "buildstats image-mklibs image-prelink"
PATCHRESOLVE = "noop"
PACKAGECONFIG_append_pn-qemu-system-native = " sdl"
CONF_VERSION = "1"
```

here is my `bblayers.conf`

```
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /home/kotoz/Desktop/Embedded_linux/yocto_for_rpi/poky_master/poky/meta \
  /home/kotoz/Desktop/Embedded_linux/yocto_for_rpi/poky_master/poky/meta-poky \
  /home/kotoz/Desktop/Embedded_linux/yocto_for_rpi/poky_master/poky/meta-yocto-bsp \
  /home/kotoz/Desktop/Embedded_linux/yocto_for_rpi/poky_master/layers/meta-raspberrypi \
  /home/kotoz/Desktop/Embedded_linux/yocto_for_rpi/poky_master/layers/meta-openembedded/meta-oe \
  /home/kotoz/Desktop/Embedded_linux/yocto_for_rpi/poky_master/layers/meta-openembedded/meta-python \
  /home/kotoz/Desktop/Embedded_linux/yocto_for_rpi/poky_master/layers/meta-openembedded/meta-networking\
  /home/kotoz/Desktop/Embedded_linux/yocto_for_rpi/poky_master/layers/meta-openembedded/meta-perl \
  /home/kotoz/Desktop/Embedded_linux/yocto_for_rpi/poky_master/layers/meta-openembedded/meta-multimedia \
  "
```
images was built successfully with no errors.

i use the following command to boot from sd card.
`sudo bmaptool copy ./tmp/deploy/images/raspberrypi4-64/core-image-base-raspberrypi4-64.wic.bz2 /dev/sdb`

when i pluged the sd card then the power cable the green flash was blinking, then make a cracking flashes then off. 
i use hdmi screen, i goes into power save mode. 

i have used the last steps with raspberry pi 3 and it works properly. so what is the problem ?

**Comment by kraj** [comment]
Can you try after removing below line from your `local.conf`

```
RPI_USE_U_BOOT = "1"
```

**Comment by Kottoz** [comment]
@kraj 
i have already test that,  just keep the default `local.conf`, and edit `MACHINE = "raspberrypi4"` . 
the first trial my pi has connected and detected the hdmi, rainbow background start to appears for 2 seconds then nothing to show. 
i remove the power then plug it again, nothing happens and not detects hdmi. 

my pi is raspberrypi4 , 2G rams, using 32 G class 10 sd card.

**Comment by Kottoz** [comment]
i will make another test keep `local.conf` is default but update the following 
```
MACHINE = "raspberrypi4"

#RPI_USE_U_BOOT = "1"
LICENSE_FLAGS_WHITELIST = "commercial"
IMAGE_INSTALL_append = " kernel-image kernel-modules"
INHERIT += "image-buildinfo"
IMAGE_ROOTFS_EXTRA_SPACE = "327680"

```

**Comment by Kottoz** [comment]
@kraj 
i have used a shared `download` and `sstate-cache` folders between different pokies branches and also different hardware.
should i isolate each `download` and `sstate-cache` for each poky. 

what i mean that i have poky with dunfell branch and another in different directory with master. 
is this the problem ?

**Comment by kraj** [comment]
> @kraj
> i have used a shared `download` and `sstate-cache` folders between different pokies branches and also different hardware.
> should i isolate each `download` and `sstate-cache` for each poky.

I think its fine to share these directories.

> 
> what i mean that i have poky with dunfell branch and another in different directory with master.
> is this the problem ?
> 
> i will make a try to isolate both by commenting `DL` and `SSTATE-CACHE` inside `local.conf`
> 
> this works ! but how

What works ? I did not understand

**Comment by Kottoz** [comment]
I was using shared sstate-cache between all my projects, which are based on
poky dunfell branch. I have created another project based on poky master,
and used the shared sstate-cache and downloads.
After i have removed the shared sstate-cache and downloads, just commented
them.
The device is booted properly.

But after remove the power and plug it again it doesn't work hdmi monitor
is in power saving mode. I have also noticed that the device has taken an
ip address as i connect the pi to router via ethernet cable.

I suspected that i have a problem in my mini  hdmi socets then i will try
to use another one and post my feedback

**Comment by agherzan** [comment]
Note for future: prefer attaching configuration files as opposed to pasting long ones in the issue thread.

On topic though, are you sure that initially, the board was not booting at all? Maybe it just behaved as in the case you described above - for which you suspect the HDMI cable/port.

**Comment by kraj** [comment]
> Note for future: prefer attaching configuration files as opposed to pasting long ones in the issue thread.
> 
> On topic though, are you sure that initially, the board was not booting at all? Maybe it just behaved as in the case you described above - for which you suspect the HDMI cable/port.

If you look at my suggestion I asked to disable u-boot and fall back to direct boot loader instead 
It might be worth testing if
This is the reason I have had enough troubles with  unit on master lately that I have disabled it in yoe distro for now

**Comment by Kottoz** [comment]
i have updated the issue. 
every thing is worked well. 
thanks 
i will close this issue
