### ISSUE TITLE
How to prevent lirc from building?

### ISSUE THREAD

**Issue by zlemonpie** [agherzan/meta-raspberrypi#849]
Hi,
unfortunately I'm mixing and matching versions of meta-rpi and meta-oe. Because of this lirc bbappend is failing. Is there a way to just tell yocto not to build this recipe? I don't need it

**Comment by kraj** [comment]
you could mask it with `BBMASK` something like

```
BBMASK .= "recipes-connectivity/lirc"
```
might work. but you might have to refine the regexp
