### ISSUE TITLE
raspberrypi3-64 MACHINEOVERRIDES

### ISSUE THREAD

**Issue by michal-mazurek** [agherzan/meta-raspberrypi#85]
Currently meta-raspberrypi/conf/machine/raspberrypi3-64.conf sets:
`MACHINEOVERRIDES = "raspberrypi3:raspberrypi:${MACHINE}"`
Is there a need for it to include "raspberrypi"? The non-64bit version doesn't seem to do that.

**Comment by agherzan** [comment]
I think that is an issue. We should only have raspberrypi3 there and rely on `rpi` as family sock. @kraj , thoughts?

**Comment by kraj** [comment]
I think it can be removed, if 32bit version doesnt use it then we dont need it for 64bit version either
we have to fix fallouts though.

**Comment by agherzan** [comment]
@michal-mazurek Would you be able to sent a PR for this too?

**Comment by betafive** [comment]
@michal-mazurek, @agherzan: Can this be closed now as the pull request above has been merged?

**Comment by agherzan** [comment]
Yes. Let's clean. If there's anything left needed, I'll let people to comment. For now I'll close it.
