### ISSUE TITLE
Pi4 u-boot USB controller not found

### ISSUE THREAD

**Issue by havok13888** [agherzan/meta-raspberrypi#853]
Hi, whenever the system boots and the usb start command is run in u-boot it is unable to find the usb controller. I can see the usb devices running and mounted when I'm in the OS

![image](https://user-images.githubusercontent.com/1217312/116588036-ae93e200-a8e0-11eb-9a37-646c46581d00.png)

Using:
- u-boot 2021.04
- all layers on gatesgarth
- Building for pi4 and cm4

I have the following enabled in u-boot def config. 

```
CONFIG_CMD_USB=y
CONFIG_USB=y
CONFIG_DM_USB=y
CONFIG_DM_USB_GADGET=y
CONFIG_USB_XHCI_HCD=y
CONFIG_USB_XHCI_PCI=y
CONFIG_USB_KEYBOARD=y
CONFIG_USB_GADGET=y
CONFIG_USB_GADGET_MANUFACTURER="FSL"
CONFIG_USB_GADGET_VENDOR_NUM=0x0525
CONFIG_USB_GADGET_PRODUCT_NUM=0xa4a5
CONFIG_USB_GADGET_DWC2_OTG=y
CONFIG_USB_GADGET_DOWNLOAD=y
```

Thanks

**Comment by havok13888** [comment]
The ultimate goal was to run this on a CM4, there seems to be an issue there too but a different one. I have an issue opened at linux-raspberrypi: https://github.com/raspberrypi/linux/issues/4325

**Comment by agherzan** [comment]
@havok13888 As far as I remember, uboot didn't have USB support (maybe that changed, and all we need is a backport or a version bump). I encourage you to follow up on the uboot mailing list for this issue.
