### ISSUE TITLE
how to add components in local.conf file  to make raspberry pi 4 64bit image can run 32bit executable ?

### ISSUE THREAD

**Issue by gitgonewithwind** [agherzan/meta-raspberrypi#877]
hi all,
I use IDS-3118WR-30HDA1E touchscreen to connect to pi 4, but the touchscreen driver is 32bit(no 64bit driver). the executable driver can be install and run in  Raspbian image(2021-05-07-raspios-buster-armhf-full).
but  I build my own raspberry pi  64bit image with yocto.the executable driver can NOT run on.
so what components I need to add to the image to make 32bit executable driver can run?

Thank you so much.

**Comment by kraj** [comment]
is this a kernel driver or userspace driver ? if it is all userspace then perhaps you can try multilib see https://www.yoctoproject.org/docs/current/dev-manual/dev-manual.html#combining-multiple-versions-library-files-into-one-image

if you are lucky perhaps all you need is to add `lib32-<your-driver>` to `IMAGE_INSTALL` and all will work :)

**Comment by gitgonewithwind** [comment]
thank you
