### ISSUE TITLE
Does WM8960 audio capture work ?

### ISSUE THREAD

**Issue by BMatthai** [agherzan/meta-raspberrypi#889]
I am using meta-raspberrypi on master branch and I would like to use audio features (capture and playback).

To perform this, I added MACHINE_FEATURES += "wm8960" in my local.conf file as documentation says. I also toggled switches to make playback working.

Playback works, but I'm not able to perform any capture.

I unmuted and toggled all switches in alsamixer capture panel, and increased all volumes to max level, but when I run following command I don't have any sound to my loudspeaker (except noise or automatic rifle sounds):
$ arecord -D hw:0,0 -f CD -r 16000 -c 2 | aplay -Dhw:0
(capture to a wav files doesn't work neither)

When I install [seeed-voicecard from respeaker](https://github.com/respeaker/seeed-voicecard) on a fresh Raspbian install capture does work.

Did I miss something ? Thank you.

**Comment by agherzan** [comment]
@BMatthai have you managed to figure this one out? I sadly don't have much I can help with.
