### ISSUE TITLE
libwpe workaround for rpi to be removed from OE-Core

### ISSUE THREAD

**Issue by denix0** [agherzan/meta-raspberrypi#893]
Please migrate the corresponding workaround code for libwpe to meta-raspberrypi, if still applicable, as it is to be removed from OE-Core.

    # Workaround build issue with RPi userland EGL libraries.
    CFLAGS:append_rpi = " ${@bb.utils.contains('MACHINE_FEATURES', 'vc4graphics', '', '-D_GNU_SOURCE', d)}"

https://lists.openembedded.org/g/openembedded-core/topic/84653556

**Comment by agherzan** [comment]
I think it is safe to go ahead and migrate. I'm curious why was it done there in the first place.
