### ISSUE TITLE
core-image-minimal-xfce

### ISSUE THREAD

**Issue by vermaete** [agherzan/meta-raspberrypi#905]
Is the core-image-minimal-xfce known to be booting/working?
I think it's not in the CI/CI, but I could be wrong.

At master, I have the issue: "(EE) Fatal server error:(EE) no screen found(EE) ..."

(at raspberrypi4 with kas)

**Comment by kraj** [comment]
I have fixed it for rpi4-64 can you try https://github.com/agherzan/meta-raspberrypi/pull/904 ?
we will need similar fix for rpi4 as well if rpi4-64 works.

**Comment by vermaete** [comment]
@kraj You're latest version of  #904 did solve it at rasberrypi4-64.

Thanks!
