### ISSUE TITLE
config.txt contains line longer than 80 bytes

### ISSUE THREAD

**Issue by zyga** [agherzan/meta-raspberrypi#917]
Default `config.txt` should refrain from adding lines longer than 80 columns. The firmware has a [documented limitation](https://www.raspberrypi.com/documentation/computers/config_txt.html#file-format) in parsing those, and while it seems to not choke too hard on the 80 column-big comments, it should probably be both detected by the build system (a `bbwarn`) and avoided in the default setup.

**Steps to reproduce the issue:**
1. Build a stock image for the Raspberry Pi 4
2. Look at the created config.txt file and select lines longer than 80 bytes
3. There should be none

**Describe the results you received:**

Default config.txt contains a reference to a bug report.
```
# Force arm in 64bit mode. See: https://github.com/raspberrypi/firmware/issues/1193.
```

This line is 85 bytes long.

**Describe the results you expected:**

Perhaps wrap the line?

**Additional information you deem important (e.g. issue happens only occasionally):**

**Additional details (revisions used, host distro, etc.):**

meta-{ohos,asos} from OSTC

**Comment by agherzan** [comment]
We have merged the proposed checkerand master is not having any lines longer than 80 bytes. So, for the scope of master, I'll close this but feel free to propose changes on older versions.
