### ISSUE TITLE
RPI 4 Model B only shows one DRM CRTC/Connector when two HDMI displays connected

### ISSUE THREAD

**Issue by angusto** [agherzan/meta-raspberrypi#919]
I am using gatesgarth branch meta-raspberrypi, and kernel is "Linux raspberrypi4-64 5.10.17-v8", when connecting two monitors(4k and 1080p) to the RPI 4 Model B two Micro HDMI ports, and the one HDMI port which near to USB Type-c power supply port can show the UI(GNOME-SHELL), the another one shows rainbow. after checking the DRM debug FS of kernel, find there is only one CRTC/Connector in DRM card0(vc4 Node), below is the details:

root@raspberrypi4-64:~# cd /sys/kernel/debug/dri/0/
root@raspberrypi4-64:/sys/kernel/debug/dri/0# ls
HDMI-A-1  bo_stats  clients  crtc-0  framebuffer  gem_names  hvs_load_tracker  internal_clients  name  state
root@raspberrypi4-64:/sys/kernel/debug/dri/0# cat state 
plane[31]: plane-0
	crtc=crtc-0
	fb=97
		allocated by = gnome-shell
		refcount=2
		format=XR24 little-endian (0x34325258)
		modifier=0x0
		size=3840x2160
		layers:
			size[0]=3840x2160
			pitch[0]=15360
			offset[0]=0
			obj[0]:
				name=0
				refcount=3
				start=00102f7a
				size=33177600
				imported=no
	crtc-pos=3840x2160+0+0
	src-pos=3840.000000x2160.000000+0.000000+0.000000
	rotation=1
	normalized-zpos=0
	color-encoding=ITU-R BT.601 YCbCr
	color-range=YCbCr limited range
plane[38]: plane-1
	crtc=(null)
	fb=0
	crtc-pos=0x0+0+0
	src-pos=0.000000x0.000000+0.000000+0.000000
	rotation=1
	normalized-zpos=0
	color-encoding=ITU-R BT.601 YCbCr
	color-range=YCbCr limited range
plane[45]: plane-2
	crtc=(null)
	fb=0
	crtc-pos=0x0+0+0
	src-pos=0.000000x0.000000+0.000000+0.000000
	rotation=1
	normalized-zpos=0
	color-encoding=ITU-R BT.601 YCbCr
	color-range=YCbCr limited range
plane[52]: plane-3
	crtc=(null)
	fb=0
	crtc-pos=0x0+0+0
	src-pos=0.000000x0.000000+0.000000+0.000000
	rotation=1
	normalized-zpos=0
	color-encoding=ITU-R BT.601 YCbCr
	color-range=YCbCr limited range
plane[59]: plane-4
	crtc=(null)
	fb=0
	crtc-pos=0x0+0+0
	src-pos=0.000000x0.000000+0.000000+0.000000
	rotation=1
	normalized-zpos=0
	color-encoding=ITU-R BT.601 YCbCr
	color-range=YCbCr limited range
plane[66]: plane-5
	crtc=(null)
	fb=0
	crtc-pos=0x0+0+0
	src-pos=0.000000x0.000000+0.000000+0.000000
	rotation=1
	normalized-zpos=0
	color-encoding=ITU-R BT.601 YCbCr
	color-range=YCbCr limited range
plane[73]: plane-6
	crtc=(null)
	fb=0
	crtc-pos=0x0+0+0
	src-pos=0.000000x0.000000+0.000000+0.000000
	rotation=1
	normalized-zpos=0
	color-encoding=ITU-R BT.601 YCbCr
	color-range=YCbCr limited range
plane[80]: plane-7
	crtc=crtc-0
	fb=95
		allocated by = gnome-shell
		refcount=1
		format=AR24 little-endian (0x34325241)
		modifier=0x0
		size=64x64
		layers:
			size[0]=64x64
			pitch[0]=256
			offset[0]=0
			obj[0]:
				name=0
				refcount=3
				start=00102f76
				size=16384
				imported=no
	crtc-pos=64x64+3452+1940
	src-pos=64.000000x64.000000+0.000000+0.000000
	rotation=1
	normalized-zpos=1
	color-encoding=ITU-R BT.601 YCbCr
	color-range=YCbCr limited range
crtc[87]: crtc-0
	enable=1
	active=1
	self_refresh_active=0
	planes_changed=1
	mode_changed=0
	active_changed=0
	connectors_changed=0
	color_mgmt_changed=0
	plane_mask=81
	connector_mask=1
	encoder_mask=1
	mode: "3840x2160": 30 297000 3840 4016 4104 4400 2160 2168 2178 2250 0x40 0x5
connector[89]: HDMI-A-1
	crtc=crtc-0
	self_refresh_aware=0
root@raspberrypi4-64:/sys/kernel/debug/dri/0# cat name 
vc4 dev=gpu unique=gpu

root@raspberrypi4-64:~# cat /proc/cpuinfo 
processor	: 0
BogoMIPS	: 108.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 1
BogoMIPS	: 108.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 2
BogoMIPS	: 108.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 3
BogoMIPS	: 108.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

Hardware	: BCM2835
Revision	: d03114
Serial		: 1000000092da5122
Model		: Raspberry Pi 4 Model B Rev 1.4

so want to confirm here: if Linux DRM vc4 driver(not sure why CPU is still bcm2835? should be bcm2711?) only support one HDMI port connected at the same time? i have no DSI display in hands now, not sure if is can support two CRTC/conntector when connecting one HDMI port and one DSI port at the same time?  or any config can enable two HDMIs CRTC/Connector? thank you

**Comment by agherzan** [comment]
Have you tried to reproduce on the current HEAD of master?
