### ISSUE TITLE
Zeus Branch has outdated raspberrypi-firmware

### ISSUE THREAD

**Issue by gookcedemir** [agherzan/meta-raspberrypi#925]
**Description**
I am using the Zeus branch and so far it was able to boot the image that I created. But last Raspberry Pi 4 Model B (4 GB Ram) orders started to show this issue below:

![image](https://user-images.githubusercontent.com/51710502/137147418-3936b1bb-caba-4f5d-9aa4-705e8d01a3bc.png)

**Describe the results you received:**
After some testing, I noticed that Rasperry Pi 4 is able to load official Rasbian image which I have installed using Raspberry Pi Imager. I had copied start4.elf file from SD-card which had Rasbian image intalled and pasted into my custom image installed SD-card. This helped to boot the image. That's why I thought the problem is related to the bootfiles. And I have checked meta-raspberrypi bootfiles and noticed that the Zeus branch is outdated and the latest raspberry pi firmware version was pinned to the 20191210. Therefore, I have created a bcm2835-boot files.bbappend file to change the installed raspberrypi firmware version to get the latest start4.elf file for my custom image. Now it is able to boot but not able to load the Qt5 application.

[bcm2835-bootfiles.zip](https://github.com/agherzan/meta-raspberrypi/files/7363324/bcm2835-bootfiles.zip)

I am not sure if only update required part is raspberry pi firmware. Can you please update the zeus branch with the latest raspberrypi firmware version and also all the relevant files or recipes?

**Comment by agherzan** [comment]
Zeus is not a maintained branch anymore. I would suggest you move to either the latest stable or an LTS version (eg. `dunfell`). If `zeus` is something you are stuck with, for whatever reason, I would probably look forward to a proposal of change (if it is completely broken in the current state) or recommend you to use an extra layer to update the firmware (and probably kernel) externally.
