### ISSUE TITLE
5.4 kernel compilation fails for hardknott due to overlays/vc4-kms-dsi-7inch.dtbo

### ISSUE THREAD

**Issue by razr** [agherzan/meta-raspberrypi#927]
**5.4 kernel compilation fails for hardknott due to overlays/vc4-kms-dsi-7inch.dtbo**

I have tried to compile a 5.4 kernel instead of 5.10 for the `raspberrypi4-64`

**Steps to reproduce the issue:**
1. add `PREFERRED_VERSION_linux-raspberrypi = "5.4.%"` to conf/local.conf
2. `bitbake linux-raspberrypi`

**Describe the results you received:**
it fails due to this line `overlays/vc4-kms-dsi-7inch.dtbo`, since it presents only in 5.10 kernel:
https://github.com/agherzan/meta-raspberrypi/blob/hardknott/conf/machine/include/rpi-base.inc#L50

If I remove this line I can successfully compile and boot 5.4

**Comment by agherzan** [comment]
Oh the fun. @razr do you happen to know if later 5.4 has it? If not, I'm inclined to drop the 5.4 version. Would that hurt your usecase?

**Comment by razr** [comment]
Hi @agherzan sorry, I don't know whether this `dts` exists in the latest 5.4. Actually, this issue does not hurt me at all, since I can work around it. I have built 5.4 `PREEMPT_RT` since I know it works, didn't try 5.10 yet.

**Comment by agherzan** [comment]
@razr Right. I have checked the latest 5.4 revision and this `dts` is not there either. I fail to see the reason to keep this version anymore. And if we do, it will add the overhead of making the `dt overlay` files version-specific - which I'd like to avoid. So I'll proceed to drop this version and see if anyone complains.

**Comment by agherzan** [comment]
Dropped in https://github.com/agherzan/meta-raspberrypi/pull/931

**Comment by razr** [comment]
do add 5.15 instead would be nice :)

**Comment by agherzan** [comment]
If I get a free moment I will @razr

**Comment by shr-project** [comment]
FWIW 5.10 is used by default since gatesgarth:
https://github.com/agherzan/meta-raspberrypi/commit/12ff6a2ea60183877b3659b3d46ae4af986800e4

Any plans to create separate honister branch? I need to remove 5.4 bbappends in meta-webosose and would be useful to know if this removal will be part of meta-raspberrypi/honister or only master (for kirkstone).
