### ISSUE TITLE
Support for Raspberry Pi Zero 2 W

### ISSUE THREAD

**Issue by ckelloug3** [agherzan/meta-raspberrypi#929]
Are you planning on supporting the Raspberry PI Zero 2 W in Hardknott or later?

**Comment by kraj** [comment]
Mostly in master and honister for sure and perhaps dunfell

**Comment by agherzan** [comment]
Yes. I can't provide you with an ETA as i don't have a board but I could add the initial support without it. I'll try to look into it soon.

**Comment by floion** [comment]
Hi. Do you have an idea if you will create a new machine for it or it will be supposed to work with an updated existing machine in this BSP layer?
Thanks

**Comment by agherzan** [comment]
@floion do you have a board at hand? There will be at least a dts addition needed: bcm2710-rpi-zero-2.dts

**Comment by agherzan** [comment]
There are some changes to the wireless firmware as well. I'll get a board and add support.

**Comment by floion** [comment]
@agherzan yes, we have a board. We'll probably submit a PR with a new machine for it, in `dunfell`, `honister`, and `master`,

**Comment by floion** [comment]
What should the approach for this be like? I assume you'd want 2 new machines for both 32 and 64 bits? If so, they'd be inheriting `raspberrypi3.conf` and `raspberrypi3-64.conf` respectively?

**Comment by kraj** [comment]
I wonder, if we should just have 64bit only.

**Comment by floion** [comment]
Yeah, on our side we'll be using only the 64 bits machine anyway.

**Comment by acostach** [comment]
@kraj I raised a PR to add the machines, please let me know if it needs other changes or if I should drop the 32bit one. cc @floion

**Comment by agherzan** [comment]
Support merged as part of https://github.com/agherzan/meta-raspberrypi/pull/937
