### ISSUE TITLE
/llib/firmware wifi files not added for 64 bit compute 4

### ISSUE THREAD

**Issue by foreshoretechnology** [agherzan/meta-raspberrypi#939]
I've been trying to figure out where / why the firmware files are not being included in my final image.

bitbake-layers show-recipes  shows me that the recipe "linux-firmware-rpidistro" is included in my image but I can't see these files in my final image anyway and hence wifi does not work.

My image is based on core-image-minimal-dev and I'm using the hardknott branch but I have cherry picked out the update for the wifi drivers for the Compute 4

**Comment by kraj** [comment]
linux-firmware-rpidistro is perhaps not what you want. But specific ipk/rpm names that you want to include in image. e.g. see
https://github.com/agherzan/meta-raspberrypi/blob/master/conf/machine/raspberrypi4-64.conf#L8
