### ISSUE TITLE
dnf not installing

### ISSUE THREAD

**Issue by SirAvix** [agherzan/meta-raspberrypi#953]
Hi

**Description**
I am not able to get **dnf** installed on the raspberrypi image.
This is the same config that does get dnf installed on **qemux86-64** and **qemuarm64** machines.
I can get **apt / package_deb** to install with a similar config but not the **dnf / package_rpm** variant.

**Steps to reproduce the issue:**
1. Start fresh with hardknott 3.3
2. In _conf/bblayers.conf_ replace **meta-yocto-bsp** with **meta-raspberrypi**
3. Add/update these lines in conf/local.conf
```
    MACHINE ??= "raspberrypi4-64"
    PACKAGE_CLASSES ?= "package_rpm"
    EXTRA_IMAGE_FEATURES += "debug-tweaks package-management"
    IMAGE_INSTALL_append += "dnf"

```
**Describe the results you received:**
The image is built and boots successfully, but dnf is not installed.

**Describe the results you expected:**
I expected dnf to be installed.

**Additional information you deem important:**
This same config get dnf installed for qemuarm64 and qemux86-64 machines.

**Additional details (revisions used, host distro, etc.):**
This was tested on hardknot 3.3.
The host machine is Ubuntu 20.04.

**Comment by agherzan** [comment]
Hello. Most probably this is because you missed a whitespace in front of "dnf".

IMAGE_INSTALL_append += " dnf"

Also, look into "package-management" image feature. That should should be the standard way of doing it.
https://www.yoctoproject.org/docs/latest/ref-manual/ref-manual.html#ref-features-image
