### ISSUE TITLE
picamera Yocto integration

### ISSUE THREAD

**Issue by bhargavthriler** [agherzan/meta-raspberrypi#959]
**Description**
Currently controlling raspberry pi camera is quite straight forward using picamera module if rasberry pi os is used. But I want to use the camera using yocto. picamera module is not for yocto. I even tried creating a recipe for picamera but due to some other dependencies it doesn't seem to work.

Is there any other library or tool to control the camera.

**Comment by agherzan** [comment]
I reckon you are referring to https://github.com/waveform80/picamera, right? I don't think there is an integration of it in Yocto yet so we would need someone to look into it. If you get it working, feel free to submit a PR.

**Comment by bhargavthriler** [comment]
I will look into it. The picamera seems to be building fine but it needs some other modules to work. Will update the progress here.

**Comment by bhargavthriler** [comment]
Btw is there any other way to use the raspberry pi camera from yocto (poky distro) ?

**Comment by bhargavthriler** [comment]
**Update** : picamera needs the raspberrypi firmware's (https://github.com/raspberrypi/firmware) precompiled shared libraries, working on it.

@agherzan Btw don't we have these precompiled binaries for aarch64 ? since raspberrypi os now has 64bit support.

**Comment by bhargavthriler** [comment]
Everything is working after porting the picamera module. Now I just have to organize the recipes and the raise PR.
