### ISSUE TITLE
git.yoctoproject.org/meta-raspberrypi sync broken?

### ISSUE THREAD

**Issue by shr-project** [agherzan/meta-raspberrypi#962]
One commit is missing in git.yoctoproject.org/meta-raspberrypi hardknott branch compared to github.

```
meta-raspberrypi$ git log --oneline yp/hardknott..origin/hardknott 
b4ec97e recipes: Update SRC_URI protocols for github
```

There were some changes on git.yoctoproject.org recently, maybe you need to adjust whatever you're using to keep it in sync? https://lists.yoctoproject.org/g/yocto/message/55415

**Comment by agherzan** [comment]
Something has changed on the yocto infrastructure side. I'll check with upstream.

**Comment by agherzan** [comment]
@shr-project The mirror job should be fixed now. Thanks for raising it.
