### ISSUE TITLE
RPI CM3 64 Bits

### ISSUE THREAD

**Issue by Minipada** [agherzan/meta-raspberrypi#97]
**Description**
I am trying to write a configuration file for the cm3 64 bits, but I keep getting errors regarding `KERNEL_DEVICETREE`. I am trying to make the machine similar to the raspberrypi3-64 and add the `KERNEL_DEVICETREE` for the CM, but from what I understand, they are not shipped.
During compilation, it fails, not finding some dtb.It seem `KERNEL_DEVICETREE` points to some, but those are not generated. If not linked to `KERNEL_DEVICETREE` paramater, how can I ship the right dtb?
Here is my conf file:

    #@TYPE: Machine
    #@NAME: RaspberryPi Compute Module 3 (CM3-64)
    #@DESCRIPTION: Machine configuration for the RaspberryPi Compute Module 3 (CM3) in 64 bits mode

    MACHINEOVERRIDES = "raspberrypi3:${MACHINE}"

    require conf/machine/include/arm/arch-armv8.inc
    include conf/machine/include/rpi-base.inc

    KERNEL_DEVICETREE = " \
        broadcom/bcm2710-rpi-3-b.dtb \
        broadcom/bcm2837-rpi-3-b.dtb \
        broadcom/bcm2708-rpi-cm.dtb \
        broadcom/bcm2710-rpi-cm3.dtb \
        \
        overlays/hifiberry-amp.dtbo \
        overlays/hifiberry-dac.dtbo \
        overlays/hifiberry-dacplus.dtbo \
        overlays/hifiberry-digi.dtbo \
        overlays/i2c-rtc.dtbo \
        overlays/iqaudio-dac.dtbo \
        overlays/iqaudio-dacplus.dtbo \
        overlays/lirc-rpi.dtbo \
        overlays/pitft22.dtbo \
        overlays/pitft28-resistive.dtbo \
        overlays/pitft35-resistive.dtbo \
        overlays/pps-gpio.dtbo \
        overlays/rpi-ft5406.dtbo \
        overlays/w1-gpio.dtbo \
        overlays/w1-gpio-pullup.dtbo \
        overlays/pi3-disable-bt.dtbo \
        overlays/pi3-miniuart-bt.dtbo \
        overlays/vc4-kms-v3d.dtbo \
        "

    SERIAL_CONSOLE ?= "115200 ttyS0"
    VC4_CMA_SIZE ?= "cma-256"

    UBOOT_MACHINE = "rpi_3_config"
    MACHINE_FEATURES_append = " vc4graphics"

I am conscious this is not an issue itself, but once I understand how it works, I can make a PR here.

**Steps to reproduce the issue:**
1. Add the upper configuration file in `meta-raspberrypi/conf/machine`
2. Add `KERNEL_DEFCONFIG_raspberrypi-cm3-64 ?= "bcmrpi3_defconfig"` in `recipes-kernel/linux/linux-raspberrypi.inc`
3. `bitbake linux-raspberrypi`

**Describe the results you received:**

    |   DTC     arch/arm64/boot/dts/broadcom/bcm2837-rpi-3-b.dtb
    | make[3]: *** No rule to make target `arch/arm64/boot/dts/broadcom/bcm2708-rpi-cm.dtb'.  Stop.
    | make[2]: *** [broadcom/bcm2708-rpi-cm.dtb] Error 2
    | make[1]: *** [sub-make] Error 2
    | make: *** [__sub-make] Error 2

**Describe the results you expected:**
Compilation done with dtb from CM.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Additional details (revisions used, host distro, etc.):**

**Comment by betafive** [comment]
Looking in the linux-raspberrypi kernel sources, there isn't any `*-cm.dtb` files in https://github.com/raspberrypi/linux/tree/rpi-4.9.y/arch/arm64/boot/dts/broadcom.

I'd recommend asking on the linux-raspberrypi repository what the correct dts file is to for the RaspberryPi CM3 to be used in 64-bit mode.

**Comment by Minipada** [comment]
You are right, that's where I mostly working. It's a WIP on the kernel and will update you asap. I'd like to merge it here once it's done

**Comment by betafive** [comment]
Ok that's good news, it'd be nice to have the CM3 working with a 64-bit operating system.

Do you have a kernel branch that does have the dts files you need?

**Comment by Minipada** [comment]
Yes, [here](https://github.com/synapticon/linux/tree/feature_rpi-cm3-64). For now, it is more experiments since it's the first time I work with this.

**Comment by betafive** [comment]
Ok. For development you can modify `recipes-kernel/linux/linux-raspberrypi_4.9.bb` in the meta-raspberrypi layer, change SRC_URI to point to your kernel repository and branch. That should allow you to test your changes. Once they're working and have been merged in to the upstream linux-raspberrypi repository you can send us a pull request to add the raspberrypi-cm3-64 MACHINE configuration.

**Comment by Minipada** [comment]
Yes, thanks for the informations. I'm really new to the kernel side, but am used to Yocto. This is pretty interesting, but I have to say, it lacks documentation, especially on some dts files. One needs to dig to understand why it's needed. e.g, why is the bcm2837 needed for the 64 bit rpi3.

**Comment by Minipada** [comment]
Here as an update. I manage to boot, the kernel log seems really promising. My only issue is it seems device tree overlays are ignored, for a reason I ignore. Because they are ignored, I cannot use `pi3-disable-bt` enabling to log in. Hence the message `console [ttyS0] enabled` is not displayed

I think dtoverlays are ignored since adding overlay to use uart1 doesn't change any behavior.

The setup:
* rpi-basic-image
* [raspberrypi-cm3-64.conf](https://github.com/synapticon/meta-raspberrypi/tree/feature_rpi-cm3-64)
* [kernel 4.9.39](https://github.com/synapticon/linux/tree/feature_cm3_64). I also tested 4.8.16 and have same results
* I don't use `KERNEL_IMAGETYPE=uImage`. U-boot lacks the config file. I wrote it, but I got stuck trying to edit Makefiles in the kernel source to create the uImage. From what I read, there's a way to list device tree list in uboot. It would be helpful.
* cmdline.txt: `dwc_otg.lpm_enable=0 console=tty1 console=serial0,115200 root=/dev/mmcblk0p2 rootfstype=ext4 rootwait cma=128M@64M`
* config.txt: 
    * dtparam=spi=on
    * dtparam=i2c=on
    * dtparam=i2c_arm=on
    * enable_uart=1
    * dtoverlay=pi3-disable-bt
    * dtoverlay=vc4-kms-v3d
    * gpu_mem=16
    * device_tree=[bcm2837-rpi-cm3.dtb](https://github.com/synapticon/linux/blob/feature_cm3_64/arch/arm64/boot/dts/broadcom/bcm2837-rpi-cm3.dts) (WIP)
    * core_freq=250

Here is the complete log:

    [    0.000000] Booting Linux on physical CPU 0x0
    [    0.000000] Linux version 4.9.39 (dbensoussan@ip-whatever) (gcc version 5.4.0 (GCC) ) #1 SMP PREEMPT Thu Aug 3 15:28:23 UTC 2017
    [    0.000000] Boot CPU: AArch64 Processor [410fd034]
    [    0.000000] efi: Getting EFI parameters from FDT:
    [    0.000000] efi: UEFI not found.
    [    0.000000] cma: Reserved 128 MiB at 0x0000000004000000
    [    0.000000] percpu: Embedded 22 pages/cpu @fffffff9fdf8c000 s52504 r8192 d29416 u90112
    [    0.000000] Detected VIPT I-cache on CPU0
    [    0.000000] CPU features: enabling workaround for ARM erratum 845719
    [    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 249984
    [    0.000000] Kernel command line: 8250.nr_uarts=1 bcm2708_fb.fbwidth=656 bcm2708_fb.fbheight=416 bcm2708_fb.fbdepth=16 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x3ea00000 vc_mem.mem_size=0x3f000000  dwc_otg.lpm_enable=0 console=tty1 console=ttyAMA0,115200 root=/dev/mmcblk0p2 rootfstype=ext4 rootwait cma=128M@64M drm.debug=0x1f
    [    0.000000] PID hash table entries: 4096 (order: 3, 32768 bytes)
    [    0.000000] Dentry cache hash table entries: 131072 (order: 8, 1048576 bytes)
    [    0.000000] Inode-cache hash table entries: 65536 (order: 7, 524288 bytes)
    [    0.000000] Memory: 852612K/1015808K available (6780K kernel code, 754K rwdata, 2548K rodata, 2688K init, 828K bss, 32124K reserved, 131072K cma-reserved)
    [    0.000000] Virtual kernel memory layout:
    [    0.000000]     modules : 0xffffff8000000000 - 0xffffff8008000000   (   128 MB)
    [    0.000000]     vmalloc : 0xffffff8008000000 - 0xffffffbebfff0000   (   250 GB)
    [    0.000000]       .text : 0xffffff9a55480000 - 0xffffff9a55b20000   (  6784 KB)
    [    0.000000]     .rodata : 0xffffff9a55b20000 - 0xffffff9a55db0000   (  2624 KB)
    [    0.000000]       .init : 0xffffff9a55db0000 - 0xffffff9a56050000   (  2688 KB)
    [    0.000000]       .data : 0xffffff9a56050000 - 0xffffff9a5610ca00   (   755 KB)
    [    0.000000]        .bss : 0xffffff9a5610ca00 - 0xffffff9a561dba94   (   829 KB)
    [    0.000000]     fixed   : 0xffffffbefe7fd000 - 0xffffffbefec00000   (  4108 KB)
    [    0.000000]     PCI I/O : 0xffffffbefee00000 - 0xffffffbeffe00000   (    16 MB)
    [    0.000000]     vmemmap : 0xffffffbf00000000 - 0xffffffc000000000   (     4 GB maximum)
    [    0.000000]               0xffffffbfe7000000 - 0xffffffbfe7f80000   (    15 MB actual)
    [    0.000000]     memory  : 0xfffffff9c0000000 - 0xfffffff9fe000000   (   992 MB)
    [    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
    [    0.000000] Preemptible hierarchical RCU implementation.
    [    0.000000]  Build-time adjustment of leaf fanout to 64.
    [    0.000000] NR_IRQS:64 nr_irqs:64 0
    [    0.000000] Failed to get local register map. FIQ is disabled for cpus > 1
    [    0.000000] arm_arch_timer: Architected cp15 timer(s) running at 19.20MHz (phys).
    [    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x46d987e47, max_idle_ns: 440795202767 ns
    [    0.000006] sched_clock: 56 bits at 19MHz, resolution 52ns, wraps every 4398046511078ns
    [    0.000186] Console: colour dummy device 80x25
    [    0.001397] console [tty1] enabled
    [    0.001443] Calibrating delay loop (skipped), value calculated using timer frequency.. 38.40 BogoMIPS (lpj=19200)
    [    0.001507] pid_max: default: 32768 minimum: 301
    [    0.001842] Mount-cache hash table entries: 2048 (order: 2, 16384 bytes)
    [    0.001883] Mountpoint-cache hash table entries: 2048 (order: 2, 16384 bytes)
    [    0.002833] Disabling cpuset control group subsystem
    [    0.003018] ftrace: allocating 23498 entries in 92 pages
    [    0.064943] ASID allocator initialised with 65536 entries
    [    0.072885] EFI services will not be available.
    [    0.081879] Detected VIPT I-cache on CPU1
    [    0.081942] CPU1: Booted secondary processor [410fd034]
    [    0.088988] Detected VIPT I-cache on CPU2
    [    0.089032] CPU2: Booted secondary processor [410fd034]
    [    0.096108] Detected VIPT I-cache on CPU3
    [    0.096149] CPU3: Booted secondary processor [410fd034]
    [    0.096254] Brought up 4 CPUs
    [    0.096447] SMP: Total of 4 processors activated.
    [    0.096488] CPU features: detected feature: 32-bit EL0 Support
    [    0.096591] CPU: All CPU(s) started at EL2
    [    0.096652] alternatives: patching kernel code
    [    0.097888] devtmpfs: initialized
    [    0.112872] DMI not present or invalid.
    [    0.113258] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 1911260446275000 ns
    [    0.113353] futex hash table entries: 1024 (order: 5, 131072 bytes)
    [    0.119398] pinctrl core: initialized pinctrl subsystem
    [    0.120318] NET: Registered protocol family 16
    [    0.132696] cpuidle: using governor menu
    [    0.133119] vdso: 2 pages (1 code @ ffffff9a55b27000, 1 data @ ffffff9a56054000)
    [    0.133186] hw-breakpoint: found 6 breakpoint and 4 watchpoint registers.
    [    0.135360] DMA: preallocated 256 KiB pool for atomic allocations
    [    0.135515] Serial: AMBA PL011 UART driver
    [    0.139366] bcm2835-mbox 3f00b880.mailbox: mailbox enabled
    [    0.199242] bcm2835-dma 3f007000.dma: DMA legacy API manager at ffffff800804b000, dmachans=0x1
    [    0.201861] SCSI subsystem initialized
    [    0.202106] usbcore: registered new interface driver usbfs
    [    0.202238] usbcore: registered new interface driver hub
    [    0.202419] usbcore: registered new device driver usb
    [    0.202761] dmi: Firmware registration failed.
    [    0.203702] raspberrypi-firmware soc:firmware: Attached to firmware from 2017-04-05 11:51
    [    0.205456] clocksource: Switched to clocksource arch_sys_counter
    [    0.277578] VFS: Disk quotas dquot_6.6.0
    [    0.277715] VFS: Dquot-cache hash table entries: 512 (order 0, 4096 bytes)
    [    0.278024] FS-Cache: Loaded
    [    0.278344] CacheFiles: Loaded
    [    0.293700] NET: Registered protocol family 2
    [    0.294779] TCP established hash table entries: 8192 (order: 4, 65536 bytes)
    [    0.294960] TCP bind hash table entries: 8192 (order: 5, 131072 bytes)
    [    0.295238] TCP: Hash tables configured (established 8192 bind 8192)
    [    0.295439] UDP hash table entries: 512 (order: 2, 16384 bytes)
    [    0.295545] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes)
    [    0.295899] NET: Registered protocol family 1
    [    0.296514] RPC: Registered named UNIX socket transport module.
    [    0.296551] RPC: Registered udp transport module.
    [    0.296582] RPC: Registered tcp transport module.
    [    0.296613] RPC: Registered tcp NFSv4.1 backchannel transport module.
    [    0.300305] workingset: timestamp_bits=46 max_order=18 bucket_order=0
    [    0.323323] FS-Cache: Netfs 'nfs' registered for caching
    [    0.324593] NFS: Registering the id_resolver key type
    [    0.324672] Key type id_resolver registered
    [    0.324708] Key type id_legacy registered
    [    0.327803] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 251)
    [    0.328038] io scheduler noop registered
    [    0.328077] io scheduler deadline registered
    [    0.328161] io scheduler cfq registered (default)
    [    0.431527] Serial: 8250/16550 driver, 1 ports, IRQ sharing enabled
    [    0.433682] bcm2835-rng 3f104000.rng: hwrng registered
    [    0.433934] [drm] Initialized
    [    0.434205] Unable to detect cache hierarchy from DT for CPU 0
    [    0.454385] brd: module loaded
    [    0.465704] loop: module loaded
    [    0.465753] Loading iSCSI transport class v2.0-870.
    [    0.466547] usbcore: registered new interface driver smsc95xx
    [    0.466599] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
    [    0.493122] dwc2 3f980000.usb: Configuration mismatch. dr_mode forced to host
    [    0.544090] dwc2 3f980000.usb: DWC OTG Controller
    [    0.544160] dwc2 3f980000.usb: new USB bus registered, assigned bus number 1
    [    0.544240] dwc2 3f980000.usb: irq 41, io mem 0x00000000
    [    0.544599] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
    [    0.544646] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
    [    0.544702] usb usb1: Product: DWC OTG Controller
    [    0.544741] usb usb1: Manufacturer: Linux 4.9.39 dwc2_hsotg
    [    0.544781] usb usb1: SerialNumber: 3f980000.usb
    [    0.545792] hub 1-0:1.0: USB hub found
    [    0.545869] hub 1-0:1.0: 1 port detected
    [    0.546836] usbcore: registered new interface driver usb-storage
    [    0.547183] mousedev: PS/2 mouse device common for all mice
    [    0.548835] bcm2835-wdt 3f100000.watchdog: Broadcom BCM2835 watchdog timer
    [    0.549247] bcm2835-cpufreq: min=600000 max=1275000
    [    0.549870] sdhci: Secure Digital Host Controller Interface driver
    [    0.549911] sdhci: Copyright(c) Pierre Ossman
    [    0.552205] sdhost-bcm2835 3f202000.sdhost: could not get clk, deferring probe
    [    0.552546] sdhci-pltfm: SDHCI platform and OF driver helper
    [    0.553213] ledtrig-cpu: registered to indicate activity on CPUs
    [    0.553362] hidraw: raw HID events driver (C) Jiri Kosina
    [    0.553632] usbcore: registered new interface driver usbhid
    [    0.553671] usbhid: USB HID core driver
    [    0.553960] Initializing XFRM netlink socket
    [    0.554023] NET: Registered protocol family 17
    [    0.554211] Key type dns_resolver registered
    [    0.554688] Registered cp15_barrier emulation handler
    [    0.554739] Registered setend emulation handler
    [    0.555759] registered taskstats version 1
    [    0.564587] 3f201000.serial: ttyAMA0 at MMIO 0x3f201000 (irq = 72, base_baud = 0) is a PL011 rev2
    [    1.387549] console [ttyAMA0] enabled
    [    1.396723] sdhost: log_buf @ ffffff8008111000 (c4041000)
    [    1.446492] mmc0: sdhost-bcm2835 loaded - DMA enabled (>1)
    [    1.452215] of_cfs_init
    [    1.455009] of_cfs_init: OK
    [    1.459082] uart-pl011 3f201000.serial: no DMA platform data
    [    1.465158] Waiting for root device /dev/mmcblk0p2...
    [    1.632228] mmc0: new high speed MMC card at address 0001
    [    1.638745] mmcblk0: mmc0:0001 4FPD3R 3.64 GiB
    [    1.643813] mmcblk0boot0: mmc0:0001 4FPD3R partition 1 4.00 MiB
    [    1.650321] mmcblk0boot1: mmc0:0001 4FPD3R partition 2 4.00 MiB
    [    1.656808] mmcblk0rpmb: mmc0:0001 4FPD3R partition 3 512 KiB
    [    1.664648]  mmcblk0: p1 p2
    [    1.685777] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
    [    1.694017] VFS: Mounted root (ext4 filesystem) readonly on device 179:2.
    [    1.701940] devtmpfs: mounted
    [    1.708665] Freeing unused kernel memory: 2688K (fffffff9c09b0000 - fffffff9c0c50000)
    INIT: version 2.88 booting
    Error opening /dev/fb0: No such file or directory
    Starting udev
    [    2.178478] udevd[130]: starting version 3.2
    [    2.206533] random: udevd: uninitialized urandom read (16 bytes read)
    [    2.214623] random: udevd: uninitialized urandom read (16 bytes read)
    [    2.221195] random: udevd: uninitialized urandom read (16 bytes read)
    [    2.227789] random: udevd: uninitialized urandom read (16 bytes read)
    [    2.265043] udevd[131]: starting eudev-3.2
    [    2.398370] random: udevd: uninitialized urandom read (16 bytes read)
    [    2.428769] random: udevd: uninitialized urandom read (16 bytes read)
    [    2.658507] vc4_hdmi 3f902000.hdmi: vc4-hdmi-hifi <-> 3f902000.hdmi mapping ok
    [    2.665850] random: fast init done
    [    2.678638] vc4-drm soc:gpu: bound 3f902000.hdmi (ops vc4_hdmi_ops [vc4])
    [    2.686677] vc4-drm soc:gpu: bound 3f806000.vec (ops vc4_vec_ops [vc4])
    [    2.693754] vc4-drm soc:gpu: bound 3f400000.hvs (ops vc4_hvs_ops [vc4])
    [    2.701010] vc4-drm soc:gpu: bound 3f206000.pixelvalve (ops vc4_crtc_ops [vc4])
    [    2.709097] vc4-drm soc:gpu: bound 3f207000.pixelvalve (ops vc4_crtc_ops [vc4])
    [    2.717115] vc4-drm soc:gpu: bound 3f807000.pixelvalve (ops vc4_crtc_ops [vc4])
    [    2.755979] vc4-drm soc:gpu: bound 3fc00000.v3d (ops vc4_v3d_ops [vc4])
    [    2.765084] [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
    [    2.771824] [drm] Driver supports precise vblank timestamp query.
    [    2.809488] Console: switching to colour frame buffer device 90x30
    [    2.829525] vc4-drm soc:gpu: fb0:  frame buffer device
    [    2.923954] i2c /dev entries driver
    [    2.987411] EXT4-fs (mmcblk0p2): re-mounted. Opts: data=ordered
    Populating dev cache
    Fri Aug  4 11:38:07 UTC 2017
    INIT: Entering runlevel: 5
    Configuring network interfaces... ifconfig: SIOCGIFFLAGS: No such device
    ifconfig: SIOCSIFADDR: No such device
    ifconfig: SIOCGIFFLAGS: No such device
    ifconfig: SIOCSIFADDR: No such device
    Starting Dropbear SSH server: Generating key, this may take a while...
    Public key portion is:
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvOlVjfx+9TKwtsIbWJ8fBcdyt+4aqNtAEFQWkKu6Ccz62N44xgO7Ha5hNZ/btUOPM6ydCPwhAo9Eg4UlUPFRkJ9XkcCiNQ0Dv2FTMMQWgvcsSOmSY1RO4Ho1GUY36IWvW2lcKJ7JT5zopjBncHdj0QPWMqUXw7YoLAOsn4GFRvR3D7yAMs+Kjv6cObOPonlwpuELYhG2nhHSJBD65V6u1zj5mwAJ48V8RPAEuUqLobKyw2rsVUNm7QN8eK5xDBsmbG6Ed94DxnzVPE7g16SjHtx+M8EjImPQoyckQI+IAEg7A+TM0VLfuM7P00a6U8Pxati3HK2MKE9nc53BzBgGl root@raspberrypi-cm3-64
    Fingerprint: md5 8f:6f:2c:1c:f1:8b:9e:dd:72:42:d5:5a:4c:b8:b1:62
    [    9.269227] NET: Registered protocol family 10
    dropbear.
    Starting syslogd/klogd: done
    INIT: Id "S0" respawning too fast: disabled for 5 minutes

**Comment by agherzan** [comment]
Why don't you use the default serial console? And figure it out from there.

**Comment by Minipada** [comment]
Hey @agherzan, I worked on it since last update, but I was not working for almost 3 weeks or so. I'll update the status in the next week

**Comment by Minipada** [comment]
I am almost done but I still cannot make have the HDMI working. I found out vc4 driver was not loaded. I then tried with a raspberrypi3-64 (not compute module) machine but no success, I have exactly the same issue, videocore is not loaded.I'm using the minimum layers for creating the machine and here is my setup. 

* Config.txt:

      #Enable VC4 Graphics
      dtoverlay=vc4-kms-v3d
      gpu_mem=16
      device_tree=bcm2710-rpi-3-b.dtb
      core_freq=500
      sdram_freq=600
      arm_freq=1150
      enable_uart=1

* cmdline.txt:
      net.ifnames=0 dwc_otg.lpm_enable=0 console=serial0,115200 root=/dev/mmcblk0p2 rootfstype=ext4 rootwait cma=8M

* This is my local.conf:

      MACHINE ?= "raspberrypi3-64"
      DISTRO ?= "poky"

      EXTRA_IMAGE_FEATURES = " debug-tweaks package-management tools-profile "
      BB_NUMBER_THREADS ?= "16"
      PARALLEL_MAKE ?= "-j 16"

* I am using meta-raspberrypi@8527a396d38aec7776182caca8b9a237e03c3965 rpi-basic-image

This should work. I should have the videocore loaded at least during boottime, which I don't. Is there anything I'm missing?

**Comment by betafive** [comment]
@Minipada - HDMI output not working is a known issue with raspberrypi3-64, it's now in the documentation. We're looking at get it fixed though. Khem's latest patches may help here and these have been merged to master - could you re-try with the latest master? If that doesn't work, I've got another possible solution in progress as well which we could try.

**Comment by Minipada** [comment]
@betafive Thanks for the hints, I'll try after the current tests. I managed to use the screen using the fkms, I get a warning but this is enough to debug the dts properly. I have made some progress after understanding the device tree wiki and answers from the pelwell, the rpi DT master.
Thanks to the screen (I still don't have ttyS0 access), I see the firmware loads by default the device tree starting with the trailer `bcm27`, so I have modified my config.txt to force the new bcm2837.

I discovered it today, some parts of the `bcm27` dts are not loaded on the CM3 - 64 bits. I saw this reading the device tree in /proc/device-tree. 

I will push my changes tomorrow morning and will post here where to get them.

**Comment by Minipada** [comment]
Please excuse me @betafive for the very late answer. [Here](https://github.com/synapticon/linux/tree/cm3_64) is the WIP with a description of the current status.

**Comment by betafive** [comment]
@Minipada, are you planning to upstream this to the linux-raspberrypi kernel or carry this as a patch in meta-raspberrypi? HDMI output in 64-bit mode should definitely be working now so it would be good to get support for raspberrypi-cm3-64 as a MACHINE if possible.

**Comment by Minipada** [comment]
Hello @betafive I have actually made it work and updated my PR on the raspberryi/linux repository but got no answer. I am going to push the tests in some days, the OS will be used by the team and I will have more assurance of the quality of the work done
Here is the link: https://github.com/raspberrypi/linux/pull/2147

**Comment by betafive** [comment]
Ok, let's see how it goes upstream. Give them a reminder if needed.

**Comment by agherzan** [comment]
pelwell is usually quite responsive so I think he will reply soon.

**Comment by betafive** [comment]
@Minipada, looks like upstream haven't responded :( Could you rebase and try submitting it again? If upstream is still unresponsive we could carry the patches here for now.

**Comment by kraj** [comment]
@Minipada is this still needed ? if so then the upstream pull branch needs refresh

**Comment by agherzan** [comment]
@Minipada Friendly ping on this issue.

**Comment by Minipada** [comment]
@agherzan thanks and sorry I didn't answer. I'll take a look at it tomorrow

**Comment by Minipada** [comment]
The PR on the kernel repo looks more like a draft, I got requested some changes and am working on them and doing some cleanup.

**Comment by agherzan** [comment]
@Minipada More people are asking about this. No pressure :)

**Comment by Minipada** [comment]
I updated my pull request on the linux repository and have a PR ready for sumo as soon as they review and merge it (code [here](https://github.com/synapticon/meta-raspberrypi/tree/sumo-rpi-cm3-64))

**Comment by agherzan** [comment]
Cheers @Minipanda.

**Comment by Minipada** [comment]
My PR is still without answer since some time, but I just saw this got merged https://github.com/raspberrypi/linux/commit/248e0f711ec517aff69b815bac7b884bd3a04679

Is it hope?

**Comment by stevep-korg** [comment]
Issue 304 is related to this issue.

https://github.com/agherzan/meta-raspberrypi/issues/304

As you have discovered,  the dts file now exists in the raspberrypi linux repo, and the Makefile has also been fixed up.

Once the meta-raspberry recipes can leverage this change to raspberrypi linux, then the meta-raspberrypi kernel device tree could be updated to include the cm3.

**Comment by stevep-korg** [comment]
For now, if you wish to have a functional CM3 dtb built and deployed to the boot folder for your raspberrypi3-64 target, simply add the following to your local.conf:

KERNEL_DEVICETREE_append = "broadcom/bcm2710-rpi-cm3.dtb"

It's working well for me at head of sumo, where the linux-raspberry pi kernel recipe fetches a recent enough version where the cm3 dts is present, so the build of the dtb succeeds now.

**Comment by Minipada** [comment]
I'll try asap, and close this.

**Comment by stevep-korg** [comment]
Note, I am building the 4.14 flavor in meta-raspberrypi (4.14.68), sumo branch, and that worked.

I have not built for a 4.9 flavor in some time.

**Comment by Minipada** [comment]
@stevep-korg I couldn't boot the image.
This is my local.conf:

```
MACHINE = "raspberrypi3-64"

EXTRA_IMAGE_FEATURES = " \
  allow-empty-password \
  debug-tweaks \
  empty-root-password \
  package-management \
  ssh-server-openssh \
"

BB_NUMBER_THREADS = "32"
PARALLEL_MAKE = "-j 32"

DL_DIR = "/home/build/yocto/yocto_topdir/downloads"
SSTATE_DIR = "/home/build/yocto/yocto_topdir/sstate-cache"
TMPDIR = "/home/build/yocto/yocto_topdir/tmp"

KERNEL_DEVICETREE_append = "broadcom/bcm2710-rpi-cm3.dtb"
```

The module is there. I have nothing either on the hdmi, nor on serial. I tried using rpi-basic-image and core-image-base (as I noticed the former indicated it was deprecated)

My layers:
* poky master
* meta-openembedded master
* meta-raspberrypi sumo

**Comment by stevep-korg** [comment]
OK great, glad you could boot it.

In terms of the UART communication stopping, we have not seen that.  We use the UART for MIDI.  We set the following in config.txt

# configure uart0 for serial midi (/dev/ttyAMA0)
enable_uart=1
# midi-uart0: fakes out tty driver so that baudrate 38400 yields 31250
dtoverlay=midi-uart0

BTW, I also put all repos in branch sumo that can be in sumo.  I find master to be too unstable for regular development purposes in my organization.

I build rpi-hwup-image.   I don't care right now that it's deprecated; it has what I need for now  My organization will probably update our recipes to continue to support the rpi-hwup-image. target, even if it is retired from meta-raspberry pi.  Also, beware of core-image-minimal if you need kernel modules; it doesn't package them into the image!

**Comment by Minipada** [comment]
I confirm that everything works perfectly. Thanks @stevep-korg for the simple and efficient patch. I'm now closing it
