### ISSUE TITLE
Unable to autolaunch a dbus-daemon without a $DISPLAY for X11 ?

### ISSUE THREAD

**Issue by NNEU-1** [agherzan/meta-raspberrypi#988]
Hi,

I'm having a problem where when I launch DBus monitor or any other program that needs DBus, I get the message:
'Unable to autolaunch a dbus-daemon without a $DISPLAY for X11'.

I'm not sure if this is related to this meta layer, but I never had this on any other yocto build so far.

Any help would be appreciated!

**Comment by agherzan** [comment]
@NNEU-1 It doesn't sound like a BSP issue. Nevertheless, there seems to be documentation on this https://dbus.freedesktop.org/doc/dbus-launch.1.html
