### ISSUE TITLE
Build error on Warrior branch for RPi CM4

### ISSUE THREAD

**Issue by Sourabh1107** [agherzan/meta-raspberrypi#998]
**Description**

I am working on a RPi CM4 Lite board with meta-raspberrypi Warrior branch. I am facing some difficulties to build the image. for example, I had to change SRC_URI part in recipes-bsp/bootfiles/rpi-config_git.bb from `SRC_URI = "git://github.com/Evilpaul/RPi-config.git;protocol=git;branch=master \` to `SRC_URI = "git://github.com/Evilpaul/RPi-config.git;protocol=https;branch=master \`.

I observed that these changes are required in other files also. And warrior is using "[bcm2835-bootfiles.bb](https://github.com/agherzan/meta-raspberrypi/blob/warrior/recipes-bsp/bootfiles/bcm2835-bootfiles.bb)" but recent versions have "[rpi-bootfiles.bb](https://github.com/agherzan/meta-raspberrypi/blob/hardknott/recipes-bsp/bootfiles/rpi-bootfiles.bb) ". So will this be any problem for RPi CM4 board?

Is Warrior version compatible for RPi CM4 board?

P.S: Due to limitation from other meta-layers we are working with Warrior branch.

Can anyone please let me know if this is fine?

**Steps to reproduce the issue:**
1. Chnage to Wqarrior barnch and try to build for RPi CM4

**Describe the results you received:**
Unpack failure for URL: 'git://github.com/Evilpaul/RPi-config.git;protocol=git;branch=master'.

**Describe the results you expected:**
No errors

**Additional information you deem important (e.g. issue happens only occasionally):**

**Additional details (revisions used, host distro, etc.):**
I am using Ubuntu 20.04 machine

**Comment by AkshayKurhade** [comment]
Warrior reached its EOL in June 2020. Most of the warrior repositories and bsps(meta-raspberry in this case) are not maintained anymore. 
A better option for you would be to port other meta layers to the latest dunfell(LTS) or hardknott. 
Else you can resolve the issues with warrior by manually updating the recipes(not a good choice).
 Also some devicetree symbols and a bunch of stuff changed with shift from 4.x to 5.x kernel in raspberry pi so configuring peripherals will be an issue.
