### ISSUE TITLE
Hardknott linux-firmware-rpidistro commit does not exist

### ISSUE THREAD

**Issue by AkshayKurhade** [agherzan/meta-raspberrypi#999]
**Description**

**Steps to reproduce the issue:**
1.Build the os using the hardknott branch

**Describe the results you received:**
linux-firmware-rpidistro-20190114-1+rpt11-r0 do_fetch: Fetcher failure: Unable to find revision 83938f78ca2d5a0ffe0c223bb96d72ccc7b71ca5 in branch master even from upstream

**Comment by AkshayKurhade** [comment]
The container i was using had expired certificates

**Comment by agherzan** [comment]
Interesting. I'm not sure why that will lead to this error.

**Comment by agherzan** [comment]
That explains it now. This is because you were missing the revision fixing `meta-raspberrypi` - due to an upstream rebase/restructure. Thanks for explaining.
